/- Generated by _codex_branchb_jsonl_to_lean.py.
   Branch-B certificate row data; do not edit by hand. -/

/- Generated Branch-B certificate support definitions. -/
import Mathlib

namespace Erdos23Delta0
namespace Cert

inductive BranchBCase where
  | tightZero
  | freePacketExchange
  | sparseM1BankLBypass
  | muNuk
  | muNukRepaired
  | detourResidual
deriving Repr, DecidableEq

inductive DictClass where
  | empty
  | terminalPrefixRawExtraction
  | terminalPrefixLaneAddition
  | noncrossingCoBExtraction
  | noncrossingCoBComponentAddition
deriving Repr, DecidableEq

structure ScaledEqCert where
  terms : List Int
  target : Int
  den : Nat
  proofMode : String
deriving Repr

structure ScaledGeCert where
  lhs : Int
  rhs : Int
  margin : Nat
  den : Nat
  proofMode : String
deriving Repr

def intListSum : List Int -> Int
  | [] => 0
  | x :: xs => x + intListSum xs

def natListSum : List Nat -> Nat
  | [] => 0
  | x :: xs => x + natListSum xs

def ScaledEqCert.check (c : ScaledEqCert) : Bool :=
  intListSum c.terms == c.target

def ScaledGeCert.check (c : ScaledGeCert) : Bool :=
  c.lhs + Int.ofNat c.margin == c.rhs

structure OpStepPilot where
  opClass : DictClass
  stepRole : String
  eB_XS : Int
  eM_XS : Int
  eB_XO : Int
  eM_XO : Int
  q : Int
  rho : Int
  pieceCount : Nat
  pieceContribs : List Nat
  pieceSum : Nat
deriving Repr

def OpStepPilot.expectedQ (s : OpStepPilot) : Int :=
  s.eB_XS - s.eM_XS - s.eB_XO + s.eM_XO

def OpStepPilot.expectedRho (s : OpStepPilot) : Int :=
  if s.q < 0 then 0 else 25 * s.q

def OpStepPilot.check (s : OpStepPilot) : Bool :=
  (s.q == OpStepPilot.expectedQ s) &&
  (s.rho == OpStepPilot.expectedRho s) &&
  (s.pieceContribs.length == s.pieceCount) &&
  (natListSum s.pieceContribs == s.pieceSum) &&
  (s.rho == Int.ofNat s.pieceSum)

def opStepListCheck : List OpStepPilot -> Bool
  | [] => true
  | s :: ss => OpStepPilot.check s && opStepListCheck ss

structure RowPilot where
  name : String
  n : Nat
  m : Nat
  L : Nat
  caseTag : BranchBCase
  pressure : ScaledEqCert
  finiteMargin : ScaledGeCert
  opSteps : List OpStepPilot
deriving Repr

def RowPilot.check (r : RowPilot) : Bool :=
  ScaledEqCert.check r.pressure &&
  ScaledGeCert.check r.finiteMargin &&
  opStepListCheck r.opSteps

def rowPilotListCheck : List RowPilot -> Bool
  | [] => true
  | r :: rs => RowPilot.check r && rowPilotListCheck rs

end Cert
end Erdos23Delta0

namespace Erdos23Delta0
namespace Cert

def branchBPilotRows : List RowPilot := [
  { name := "C7[1]", n := 7, m := 1, L := 7, caseTag := BranchBCase.tightZero, pressure := { terms := [], target := 0, den := 1, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 0, rhs := 0, margin := 0, den := 1, proofMode := "rfl-or-norm_num" }, opSteps := [] },
  { name := "cenG?bB`o", n := 8, m := 1, L := 7, caseTag := BranchBCase.sparseM1BankLBypass, pressure := { terms := [1, 14], target := 15, den := 1, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 11, rhs := 26, margin := 15, den := 1, proofMode := "rfl-or-norm_num" }, opSteps := [] },
  { name := "cenJ???CBoBz{?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNuk, pressure := { terms := [69], target := 69, den := 1, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 69, rhs := 116, margin := 47, den := 1, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.empty, stepRole := "add_final_part", eB_XS := 0, eM_XS := 0, eB_XO := 0, eM_XO := 0, q := 0, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }, { opClass := DictClass.terminalPrefixRawExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 1, eM_XS := 0, eB_XO := 1, eM_XO := 0, q := 0, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }] },
  { name := "cenJ???CBoBz{?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNuk, pressure := { terms := [69], target := 69, den := 1, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 69, rhs := 116, margin := 47, den := 1, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.empty, stepRole := "add_final_part", eB_XS := 0, eM_XS := 0, eB_XO := 0, eM_XO := 0, q := 0, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }, { opClass := DictClass.terminalPrefixRawExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 5, eM_XS := 0, eB_XO := 1, eM_XO := 0, q := 4, rho := 100, pieceCount := 1, pieceContribs := [100], pieceSum := 100 }] },
  { name := "cenJ??CA?{{?]?", n := 11, m := 2, L := 7, caseTag := BranchBCase.detourResidual, pressure := { terms := [19], target := 19, den := 1, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 19, rhs := 66, margin := 47, den := 1, proofMode := "rfl-or-norm_num" }, opSteps := [] },
  { name := "cenJ??CAA_^?}?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNuk, pressure := { terms := [19], target := 19, den := 1, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 19, rhs := 66, margin := 47, den := 1, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.noncrossingCoBComponentAddition, stepRole := "add_final_part", eB_XS := 1, eM_XS := 0, eB_XO := 0, eM_XO := 1, q := 2, rho := 50, pieceCount := 1, pieceContribs := [50], pieceSum := 50 }, { opClass := DictClass.noncrossingCoBExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 1, eM_XS := 0, eB_XO := 1, eM_XO := 0, q := 0, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }] },
  { name := "cenJ??CAA_^?}?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNuk, pressure := { terms := [19], target := 19, den := 1, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 19, rhs := 66, margin := 47, den := 1, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.terminalPrefixLaneAddition, stepRole := "add_final_part", eB_XS := 1, eM_XS := 0, eB_XO := 0, eM_XO := 1, q := 2, rho := 50, pieceCount := 1, pieceContribs := [50], pieceSum := 50 }, { opClass := DictClass.empty, stepRole := "remove_raw_extra_via_complement", eB_XS := 0, eM_XS := 0, eB_XO := 0, eM_XO := 0, q := 0, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }] },
  { name := "cenJ??CAA_^?}?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNuk, pressure := { terms := [19], target := 19, den := 1, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 19, rhs := 66, margin := 47, den := 1, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.noncrossingCoBComponentAddition, stepRole := "add_final_part", eB_XS := 1, eM_XS := 0, eB_XO := 0, eM_XO := 1, q := 2, rho := 50, pieceCount := 1, pieceContribs := [50], pieceSum := 50 }, { opClass := DictClass.noncrossingCoBExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 4, eM_XS := 0, eB_XO := 1, eM_XO := 0, q := 3, rho := 75, pieceCount := 1, pieceContribs := [75], pieceSum := 75 }] },
  { name := "cenJ??CAB_n?}?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNukRepaired, pressure := { terms := [44], target := 44, den := 1, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 44, rhs := 91, margin := 47, den := 1, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.empty, stepRole := "add_final_part", eB_XS := 0, eM_XS := 0, eB_XO := 0, eM_XO := 0, q := 0, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }, { opClass := DictClass.terminalPrefixRawExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 2, eM_XS := 0, eB_XO := 1, eM_XO := 0, q := 1, rho := 25, pieceCount := 1, pieceContribs := [25], pieceSum := 25 }] },
  { name := "cenJ??CAB_n?}?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNuk, pressure := { terms := [63], target := 63, den := 2, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 63, rhs := 157, margin := 94, den := 2, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.empty, stepRole := "add_final_part", eB_XS := 0, eM_XS := 0, eB_XO := 0, eM_XO := 0, q := 0, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }, { opClass := DictClass.terminalPrefixRawExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 4, eM_XS := 0, eB_XO := 1, eM_XO := 0, q := 3, rho := 75, pieceCount := 1, pieceContribs := [75], pieceSum := 75 }] },
  { name := "cenJ??CAB_n?}?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNukRepaired, pressure := { terms := [44], target := 44, den := 1, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 44, rhs := 91, margin := 47, den := 1, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.empty, stepRole := "add_final_part", eB_XS := 0, eM_XS := 0, eB_XO := 0, eM_XO := 0, q := 0, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }, { opClass := DictClass.terminalPrefixRawExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 1, eM_XS := 1, eB_XO := 1, eM_XO := 0, q := -1, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }] },
  { name := "cenJ??CAB_n?}?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNukRepaired, pressure := { terms := [44], target := 44, den := 1, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 44, rhs := 91, margin := 47, den := 1, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.noncrossingCoBComponentAddition, stepRole := "add_final_part", eB_XS := 1, eM_XS := 0, eB_XO := 0, eM_XO := 1, q := 2, rho := 50, pieceCount := 1, pieceContribs := [50], pieceSum := 50 }, { opClass := DictClass.noncrossingCoBExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 4, eM_XS := 0, eB_XO := 1, eM_XO := 0, q := 3, rho := 75, pieceCount := 1, pieceContribs := [75], pieceSum := 75 }] },
  { name := "cenJ??CE?{{?]?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNukRepaired, pressure := { terms := [63], target := 63, den := 2, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 63, rhs := 157, margin := 94, den := 2, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.noncrossingCoBComponentAddition, stepRole := "add_final_part", eB_XS := 0, eM_XS := 0, eB_XO := 2, eM_XO := 1, q := -1, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }, { opClass := DictClass.noncrossingCoBExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 6, eM_XS := 0, eB_XO := 0, eM_XO := 0, q := 6, rho := 150, pieceCount := 1, pieceContribs := [150], pieceSum := 150 }] },
  { name := "cenJ??CE?{{?]?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNukRepaired, pressure := { terms := [63], target := 63, den := 2, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 63, rhs := 157, margin := 94, den := 2, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.noncrossingCoBComponentAddition, stepRole := "add_final_part", eB_XS := 0, eM_XS := 0, eB_XO := 2, eM_XO := 1, q := -1, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }, { opClass := DictClass.noncrossingCoBExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 6, eM_XS := 0, eB_XO := 0, eM_XO := 0, q := 6, rho := 150, pieceCount := 1, pieceContribs := [150], pieceSum := 150 }] },
  { name := "cenJ??CE?{{?]?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNukRepaired, pressure := { terms := [63], target := 63, den := 2, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 63, rhs := 157, margin := 94, den := 2, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.noncrossingCoBComponentAddition, stepRole := "add_final_part", eB_XS := 0, eM_XS := 0, eB_XO := 2, eM_XO := 1, q := -1, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }, { opClass := DictClass.noncrossingCoBExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 6, eM_XS := 0, eB_XO := 0, eM_XO := 0, q := 6, rho := 150, pieceCount := 1, pieceContribs := [150], pieceSum := 150 }] },
  { name := "cenJ??CE?{{?]?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNukRepaired, pressure := { terms := [63], target := 63, den := 2, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 63, rhs := 157, margin := 94, den := 2, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.noncrossingCoBComponentAddition, stepRole := "add_final_part", eB_XS := 0, eM_XS := 0, eB_XO := 2, eM_XO := 1, q := -1, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }, { opClass := DictClass.noncrossingCoBExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 6, eM_XS := 0, eB_XO := 0, eM_XO := 0, q := 6, rho := 150, pieceCount := 1, pieceContribs := [150], pieceSum := 150 }] },
  { name := "cenJ??CE?{{?]?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNukRepaired, pressure := { terms := [63], target := 63, den := 2, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 63, rhs := 157, margin := 94, den := 2, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.noncrossingCoBComponentAddition, stepRole := "add_final_part", eB_XS := 1, eM_XS := 0, eB_XO := 2, eM_XO := 0, q := -1, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }, { opClass := DictClass.noncrossingCoBExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 1, eM_XS := 0, eB_XO := 1, eM_XO := 0, q := 0, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }] },
  { name := "cenJ??CE?{{?]?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNuk, pressure := { terms := [44], target := 44, den := 1, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 44, rhs := 91, margin := 47, den := 1, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.noncrossingCoBComponentAddition, stepRole := "add_final_part", eB_XS := 2, eM_XS := 0, eB_XO := 3, eM_XO := 0, q := -1, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }, { opClass := DictClass.empty, stepRole := "remove_raw_extra_via_complement", eB_XS := 0, eM_XS := 0, eB_XO := 0, eM_XO := 0, q := 0, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }] },
  { name := "cenJ??CE?{{?]?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNuk, pressure := { terms := [44], target := 44, den := 1, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 44, rhs := 91, margin := 47, den := 1, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.noncrossingCoBComponentAddition, stepRole := "add_final_part", eB_XS := 3, eM_XS := 0, eB_XO := 3, eM_XO := 1, q := 1, rho := 25, pieceCount := 1, pieceContribs := [25], pieceSum := 25 }, { opClass := DictClass.empty, stepRole := "remove_raw_extra_via_complement", eB_XS := 0, eM_XS := 0, eB_XO := 0, eM_XO := 0, q := 0, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }] },
  { name := "cenJ??CE?{{?]?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNukRepaired, pressure := { terms := [63], target := 63, den := 2, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 63, rhs := 157, margin := 94, den := 2, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.noncrossingCoBComponentAddition, stepRole := "add_final_part", eB_XS := 2, eM_XS := 0, eB_XO := 2, eM_XO := 1, q := 1, rho := 25, pieceCount := 1, pieceContribs := [25], pieceSum := 25 }, { opClass := DictClass.noncrossingCoBExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 1, eM_XS := 0, eB_XO := 1, eM_XO := 0, q := 0, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }] },
  { name := "cenJ??CE?{{?]?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNukRepaired, pressure := { terms := [63], target := 63, den := 2, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 63, rhs := 157, margin := 94, den := 2, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.noncrossingCoBComponentAddition, stepRole := "add_final_part", eB_XS := 1, eM_XS := 0, eB_XO := 1, eM_XO := 1, q := 1, rho := 25, pieceCount := 1, pieceContribs := [25], pieceSum := 25 }, { opClass := DictClass.noncrossingCoBExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 3, eM_XS := 1, eB_XO := 1, eM_XO := 0, q := 1, rho := 25, pieceCount := 1, pieceContribs := [25], pieceSum := 25 }] },
  { name := "cenJ??CEB_^?}?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNuk, pressure := { terms := [113], target := 113, den := 2, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 113, rhs := 207, margin := 94, den := 2, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.empty, stepRole := "add_final_part", eB_XS := 0, eM_XS := 0, eB_XO := 0, eM_XO := 0, q := 0, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }, { opClass := DictClass.terminalPrefixRawExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 2, eM_XS := 1, eB_XO := 1, eM_XO := 0, q := 0, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }] },
  { name := "cenJ??CEB_^?}?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNuk, pressure := { terms := [113], target := 113, den := 2, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 113, rhs := 207, margin := 94, den := 2, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.empty, stepRole := "add_final_part", eB_XS := 0, eM_XS := 0, eB_XO := 0, eM_XO := 0, q := 0, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }, { opClass := DictClass.terminalPrefixRawExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 3, eM_XS := 0, eB_XO := 1, eM_XO := 0, q := 2, rho := 50, pieceCount := 1, pieceContribs := [50], pieceSum := 50 }] },
  { name := "cenJ??CEB_^?}?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNuk, pressure := { terms := [69], target := 69, den := 1, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 69, rhs := 116, margin := 47, den := 1, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.empty, stepRole := "add_final_part", eB_XS := 0, eM_XS := 0, eB_XO := 0, eM_XO := 0, q := 0, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }, { opClass := DictClass.terminalPrefixRawExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 4, eM_XS := 1, eB_XO := 1, eM_XO := 0, q := 2, rho := 50, pieceCount := 1, pieceContribs := [50], pieceSum := 50 }] },
  { name := "cenJ?AAD?w[?{?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNuk, pressure := { terms := [13], target := 13, den := 2, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 13, rhs := 107, margin := 94, den := 2, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.noncrossingCoBComponentAddition, stepRole := "add_final_part", eB_XS := 1, eM_XS := 0, eB_XO := 0, eM_XO := 1, q := 2, rho := 50, pieceCount := 1, pieceContribs := [50], pieceSum := 50 }, { opClass := DictClass.noncrossingCoBExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 2, eM_XS := 0, eB_XO := 1, eM_XO := 0, q := 1, rho := 25, pieceCount := 1, pieceContribs := [25], pieceSum := 25 }] },
  { name := "cenJ?AAD@oV@s?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNuk, pressure := { terms := [19], target := 19, den := 1, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 19, rhs := 66, margin := 47, den := 1, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.empty, stepRole := "add_final_part", eB_XS := 0, eM_XS := 0, eB_XO := 0, eM_XO := 0, q := 0, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }, { opClass := DictClass.terminalPrefixRawExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 3, eM_XS := 1, eB_XO := 1, eM_XO := 0, q := 1, rho := 25, pieceCount := 1, pieceContribs := [25], pieceSum := 25 }] },
  { name := "two-lane-L8", n := 27, m := 4, L := 7, caseTag := BranchBCase.freePacketExchange, pressure := { terms := [], target := 0, den := 1, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 0, rhs := 1125, margin := 1125, den := 2, proofMode := "rfl-or-norm_num" }, opSteps := [] }
]

theorem branchBPilotRows_length : branchBPilotRows.length = 27 := by
  rfl

set_option maxRecDepth 20000 in
theorem branchBPilotRows_check : rowPilotListCheck branchBPilotRows = true := by
  rfl

end Cert
end Erdos23Delta0
