import Mathlib

/-!
Scratch formalization for the residual-Hall replacement of the archived
no-two-hole / single-miss route.

The geometric work is not in this file.  This file only machine-checks the
counting wrapper used by the blue-closed extra graph route:

* a deficient residual Hall set has `|X|>|Y|`;
* max-cut gives `|delta_M(U)| <= |delta_B(U)|`;
* the prefix hull gives `X` plus the extra bad boundary inside `delta_M(U)`;
* the blue boundary is contained in `Y` plus the extra blue boundary;
* a side-door/corner injection gives `|Bextra| <= |Mextra|`.

These hypotheses are contradictory.  Thus the remaining theorem is exactly
the geometric extra-charge statement, not component-local single-miss.
-/

namespace Erdos23
namespace ResidualHall

/-! ## Generic finite descent wrapper for reduced deficient cores -/

/--
If every deficient non-reduced object descends to a strictly smaller deficient
object, then any deficient object has a reduced deficient descendant.

In the residual-Hall application, `x` is a door set `Z`, `Def x` says
`|N(Z)|<|Z|`, `Reduced x` says every neighboring bad edge has at least two
`Z`-doors, and `size x` is `|Z|`.
-/
theorem exists_reduced_deficient_of_descent
    {Obj : Type*} (Def Reduced : Obj → Prop) (size : Obj → Nat)
    (h0 : ∃ x, Def x)
    (hdesc :
      ∀ x, Def x → ¬ Reduced x →
        ∃ y, Def y ∧ size y < size x) :
    ∃ x, Def x ∧ Reduced x := by
  classical
  let P : Nat → Prop := fun n => ∃ x, Def x ∧ size x = n
  have hP : ∃ n, P n := by
    rcases h0 with ⟨x, hx⟩
    exact ⟨size x, x, hx, rfl⟩
  let n := Nat.find hP
  rcases Nat.find_spec hP with ⟨x, hxDef, hxSize⟩
  refine ⟨x, hxDef, ?_⟩
  by_contra hxNotReduced
  rcases hdesc x hxDef hxNotReduced with ⟨y, hyDef, hyLt⟩
  have hyP : P (size y) := ⟨y, hyDef, rfl⟩
  have hmin : n ≤ size y := Nat.find_min' hP hyP
  omega

/--
Contrapositive form: if no reduced deficient object exists and every
non-reduced deficient object descends, then no deficient object exists.
-/
theorem no_deficient_of_descent_and_no_reduced
    {Obj : Type*} (Def Reduced : Obj → Prop) (size : Obj → Nat)
    (hdesc :
      ∀ x, Def x → ¬ Reduced x →
        ∃ y, Def y ∧ size y < size x)
    (hnoReduced : ∀ x, Def x → ¬ Reduced x) :
    ∀ x, ¬ Def x := by
  intro x hx
  have h0 : ∃ x, Def x := ⟨x, hx⟩
  rcases exists_reduced_deficient_of_descent Def Reduced size h0 hdesc with
    ⟨y, hyDef, hyReduced⟩
  exact hnoReduced y hyDef hyReduced

/--
If every reduced deficient core descends to a strictly smaller reduced
deficient core, then no reduced deficient core exists.

This is the abstract finite-descent wrapper for the no-naked-leaf step: a
positive-Euler reduced fan core has a leaf branch; NL supplies a strictly
trapped bad edge inside that branch, producing a smaller reduced deficient
core.  Iteration is impossible in a finite size measure.
-/
theorem no_reduced_deficient_of_reduced_descent
    {Obj : Type*} (Def Reduced : Obj → Prop) (size : Obj → Nat)
    (hdesc :
      ∀ x, Def x → Reduced x →
        ∃ y, Def y ∧ Reduced y ∧ size y < size x) :
    ∀ x, Def x → ¬ Reduced x := by
  classical
  intro x hxDef hxReduced
  let P : Nat → Prop := fun n => ∃ x, Def x ∧ Reduced x ∧ size x = n
  have hP : ∃ n, P n := ⟨size x, x, hxDef, hxReduced, rfl⟩
  let n := Nat.find hP
  rcases Nat.find_spec hP with ⟨y, hyDef, hyReduced, hySize⟩
  rcases hdesc y hyDef hyReduced with ⟨z, hzDef, hzReduced, hzLt⟩
  have hzP : P (size z) := ⟨z, hzDef, hzReduced, rfl⟩
  have hmin : n ≤ size z := Nat.find_min' hP hzP
  omega

/--
The pure cardinal contradiction behind the residual Hall proof.

Interpretation:

* `X` is a Hall-deficient row set;
* `Y` is its residual witness-neighborhood;
* `deltaM` and `deltaB` are the bad/blue boundaries of the blue-closed prefix
  hull generated by `X`;
* `Mextra` and `Bextra` are the boundaries not already counted by `X` and `Y`.

If max-cut says `deltaM.card <= deltaB.card`, but the geometry supplies enough
extra bad boundary to pay every extra blue boundary, then `Y.card < X.card` is
impossible.
-/
theorem deficient_set_contradicts_extra_charge
    {Row Exit EdgeM EdgeB : Type*}
    (X : Finset Row) (Y : Finset Exit)
    (deltaM Mextra : Finset EdgeM) (deltaB Bextra : Finset EdgeB)
    (hMlower : X.card + Mextra.card ≤ deltaM.card)
    (hBupper : deltaB.card ≤ Y.card + Bextra.card)
    (hExtra : Bextra.card ≤ Mextra.card)
    (hMaxCut : deltaM.card ≤ deltaB.card)
    (hDef : Y.card < X.card) :
    False := by
  omega

/--
Same wrapper with the strict deficiency written in successor form.  This is
often the form produced by finite Hall searches.
-/
theorem deficient_set_contradicts_extra_charge_succ
    {Row Exit EdgeM EdgeB : Type*}
    (X : Finset Row) (Y : Finset Exit)
    (deltaM Mextra : Finset EdgeM) (deltaB Bextra : Finset EdgeB)
    (hMlower : X.card + Mextra.card ≤ deltaM.card)
    (hBupper : deltaB.card ≤ Y.card + Bextra.card)
    (hExtra : Bextra.card ≤ Mextra.card)
    (hMaxCut : deltaM.card ≤ deltaB.card)
    (hDef : Y.card + 1 ≤ X.card) :
    False := by
  omega

/--
If every nonempty Hall-deficient set admits a blue-closed prefix hull satisfying
the extra-charge inequalities, then no Hall-deficient set exists.

This is deliberately abstract: the callable hypothesis `hcharge` is exactly the
remaining geometry theorem.
-/
theorem no_hall_deficient_set_of_extra_charge
    {Row Exit EdgeM EdgeB : Type*}
    (Nbr : Finset Row → Finset Exit)
    (deltaM Mextra : Finset Row → Finset EdgeM)
    (deltaB Bextra : Finset Row → Finset EdgeB)
    (hcharge :
      ∀ X : Finset Row,
        (Nbr X).card < X.card →
        X.card + (Mextra X).card ≤ (deltaM X).card ∧
        (deltaB X).card ≤ (Nbr X).card + (Bextra X).card ∧
        (Bextra X).card ≤ (Mextra X).card ∧
        (deltaM X).card ≤ (deltaB X).card) :
    ∀ X : Finset Row, ¬ (Nbr X).card < X.card := by
  intro X hDef
  rcases hcharge X hDef with ⟨hMlower, hBupper, hExtra, hMaxCut⟩
  exact deficient_set_contradicts_extra_charge
    X (Nbr X) (deltaM X) (Mextra X) (deltaB X) (Bextra X)
    hMlower hBupper hExtra hMaxCut hDef

/--
Final proof-facing wrapper for the reduced fan-core route.

It is enough to prove:

* a descent/peeling step: every deficient non-reduced set has a smaller
  deficient descendant;
* an extra-charge certificate for every reduced deficient set.

Then there are no Hall-deficient residual sets.
-/
theorem no_hall_deficient_set_of_reduced_extra_charge
    {Row Exit EdgeM EdgeB : Type*}
    (Nbr : Finset Row → Finset Exit)
    (Reduced : Finset Row → Prop)
    (deltaM Mextra : Finset Row → Finset EdgeM)
    (deltaB Bextra : Finset Row → Finset EdgeB)
    (hdesc :
      ∀ X : Finset Row,
        (Nbr X).card < X.card → ¬ Reduced X →
        ∃ Y : Finset Row, (Nbr Y).card < Y.card ∧ Y.card < X.card)
    (hchargeReduced :
      ∀ X : Finset Row,
        (Nbr X).card < X.card → Reduced X →
        X.card + (Mextra X).card ≤ (deltaM X).card ∧
        (deltaB X).card ≤ (Nbr X).card + (Bextra X).card ∧
        (Bextra X).card ≤ (Mextra X).card ∧
        (deltaM X).card ≤ (deltaB X).card) :
    ∀ X : Finset Row, ¬ (Nbr X).card < X.card := by
  intro X hDef
  have h0 :
      ∃ X : Finset Row, (Nbr X).card < X.card := ⟨X, hDef⟩
  rcases exists_reduced_deficient_of_descent
      (fun X : Finset Row => (Nbr X).card < X.card)
      Reduced (fun X : Finset Row => X.card) h0 hdesc with
    ⟨Y, hYDef, hYReduced⟩
  rcases hchargeReduced Y hYDef hYReduced with
    ⟨hMlower, hBupper, hExtra, hMaxCut⟩
  exact deficient_set_contradicts_extra_charge
    Y (Nbr Y) (deltaM Y) (Mextra Y) (deltaB Y) (Bextra Y)
    hMlower hBupper hExtra hMaxCut hYDef

/--
NL-facing version of the residual-Hall wrapper.

It proves residual Hall from two descents:

* non-reduced deficient sets descend by the one-door peeling step;
* reduced deficient sets descend by the no-naked-leaf geometry.

This is separate from `no_hall_deficient_set_of_reduced_extra_charge`, which
uses cardinal extra-charge inequalities on reduced cores instead.
-/
theorem no_hall_deficient_set_of_reduced_descent
    {Row Exit : Type*}
    (Nbr : Finset Row → Finset Exit)
    (Reduced : Finset Row → Prop)
    (hdescNonReduced :
      ∀ X : Finset Row,
        (Nbr X).card < X.card → ¬ Reduced X →
        ∃ Y : Finset Row, (Nbr Y).card < Y.card ∧ Y.card < X.card)
    (hdescReduced :
      ∀ X : Finset Row,
        (Nbr X).card < X.card → Reduced X →
        ∃ Y : Finset Row,
          (Nbr Y).card < Y.card ∧ Reduced Y ∧ Y.card < X.card) :
    ∀ X : Finset Row, ¬ (Nbr X).card < X.card := by
  have hnoReduced :
      ∀ X : Finset Row, (Nbr X).card < X.card → ¬ Reduced X := by
    exact no_reduced_deficient_of_reduced_descent
      (fun X : Finset Row => (Nbr X).card < X.card)
      Reduced (fun X : Finset Row => X.card) hdescReduced
  exact no_deficient_of_descent_and_no_reduced
    (fun X : Finset Row => (Nbr X).card < X.card)
    Reduced (fun X : Finset Row => X.card)
    hdescNonReduced hnoReduced

/-! ## Componentwise reduced-fan expansion wrapper -/

/--
Pure cardinal form of the CRFE target.

Interpretation:

* `Z` is a reduced extra-door set;
* `H` is its neighboring extra-bad-edge set;
* `C` indexes the connected components of the chosen fan complex;
* `ZK c` and `HK c` are the doors and rows in component `c`.

If the component counts sum to the global counts and every component has at
least as many rows as doors, then `Z` cannot be Hall-deficient.
The geometry is exactly the componentwise expansion hypothesis; this theorem
only checks the counting consequence.
-/
theorem deficient_set_contradicts_componentwise_expansion
    {Door Bad Comp : Type*}
    (Z : Finset Door) (H : Finset Bad) (C : Finset Comp)
    (ZK : Comp → Finset Door) (HK : Comp → Finset Bad)
    (hZsum : Z.card = C.sum (fun c => (ZK c).card))
    (hHsum : H.card = C.sum (fun c => (HK c).card))
    (hExpand :
      ∀ c ∈ C, (ZK c).card ≤ (HK c).card)
    (hDef : H.card < Z.card) :
    False := by
  have hsum : C.sum (fun c => (ZK c).card) ≤ C.sum (fun c => (HK c).card) :=
    Finset.sum_le_sum hExpand
  omega

/--
An explicit componentwise SDR/injection implies the component cardinal
inequality used by CRFE.

In the fan application, `assign` sends each door in one fan component to a row
of the same component that opens it.  Injectivity says no two doors are assigned
to the same row.
-/
theorem component_expansion_of_injection
    {Door Bad : Type*}
    (ZK : Finset Door) (HK : Finset Bad) (assign : Door → Bad)
    (hmem : ∀ z, z ∈ ZK → assign z ∈ HK)
    (hinj : Set.InjOn assign (ZK : Set Door)) :
    ZK.card ≤ HK.card := by
  classical
  exact Finset.card_le_card_of_injOn assign (by
    intro z hz
    exact hmem z hz) hinj

/--
SDR-facing version of the componentwise CRFE contradiction.

Instead of assuming the component count inequality directly, this wrapper
assumes an explicit injective assignment from component doors to component
rows, component by component.  This is the formal target corresponding to the
`_crfe_matching_probe.py` gate.
-/
theorem deficient_set_contradicts_componentwise_sdr
    {Door Bad Comp : Type*}
    (Z : Finset Door) (H : Finset Bad) (C : Finset Comp)
    (ZK : Comp → Finset Door) (HK : Comp → Finset Bad)
    (assign : Comp → Door → Bad)
    (hZsum : Z.card = C.sum (fun c => (ZK c).card))
    (hHsum : H.card = C.sum (fun c => (HK c).card))
    (hmem :
      ∀ c ∈ C, ∀ z, z ∈ ZK c → assign c z ∈ HK c)
    (hinj :
      ∀ c ∈ C, Set.InjOn (assign c) (ZK c : Set Door))
    (hDef : H.card < Z.card) :
    False := by
  refine deficient_set_contradicts_componentwise_expansion
    Z H C ZK HK hZsum hHsum ?_ hDef
  intro c hc
  exact component_expansion_of_injection
    (ZK c) (HK c) (assign c) (hmem c hc) (hinj c hc)

end ResidualHall
end Erdos23
