#!/usr/bin/env python3
"""Exact census for subclosures generated by finite verified multipliers."""

from __future__ import annotations

import argparse
from bisect import bisect_right

from search_periodic_core import generate_a


def fixed_closure(limit: int, multipliers: tuple[int, ...]) -> bytearray:
    """Return the least set through limit containing D and closed under f_d."""
    member = bytearray(limit + 1)
    for multiplier in multipliers:
        if multiplier <= limit:
            member[multiplier] = 1
    for n in range(2, limit + 1):
        if member[n]:
            continue
        shifted = n + 1
        for multiplier in multipliers:
            if multiplier > shifted:
                break
            if shifted % multiplier:
                continue
            parent = shifted // multiplier
            if parent != multiplier and member[parent]:
                member[n] = 1
                break
    return member


def census(member: bytearray, checkpoints: tuple[int, ...]) -> tuple[int, int]:
    count = 0
    previous = None
    max_gap = 0
    checkpoint_set = set(checkpoints)
    for n in range(1, len(member)):
        if member[n]:
            count += 1
            if previous is not None:
                max_gap = max(max_gap, n - previous)
            previous = n
        if n in checkpoint_set:
            print(f"  N={n} count={count} density={count / n:.12f}")
    return count, max_gap


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit", type=int, default=1_000_000)
    parser.add_argument("--cutoffs", nargs="+", type=int, required=True)
    args = parser.parse_args()

    full = generate_a(max(args.cutoffs))
    values = tuple(n for n, bit in enumerate(full) if bit)
    checkpoints = tuple(
        10**exponent
        for exponent in range(1, 12)
        if 10**exponent <= args.limit
    )
    for cutoff in args.cutoffs:
        multipliers = values[: bisect_right(values, cutoff)]
        member = fixed_closure(args.limit, multipliers)
        print(
            f"K={cutoff} |D|={len(multipliers)} "
            f"Dmax={multipliers[-1]} sum_recip={sum(1 / d for d in multipliers):.12f}"
        )
        count, max_gap = census(member, checkpoints)
        print(f"  final_count={count} max_gap={max_gap}")


if __name__ == "__main__":
    main()
