/- Generated by _codex_o14_chunked_cone_to_lean_sharded.py; do not edit by hand. -/
import Erdos23Delta0.O14.ChunkedConeWitness

namespace Erdos23Delta0
namespace O14
namespace Generated
namespace ChartPayloads
namespace Chart000Cone
namespace Support

open PolyCert
open ODLFull
open ConeEvalBridge
open ChunkedCone

set_option maxHeartbeats 0
set_option maxRecDepth 2000000

theorem list_all_append_true {α : Type} (p : α → Bool) :
    ∀ xs ys : List α, (xs.all p = true) → (ys.all p = true) → ((xs ++ ys).all p = true)
  | [], ys, _, hy => by simpa using hy
  | x :: xs, ys, hx, hy => by
      simp only [List.all_cons, Bool.and_eq_true] at hx
      change (p x && (xs ++ ys).all p) = true
      rw [hx.1, list_all_append_true p xs ys hx.2 hy]
      rfl

theorem nf_allCoeffNonneg_append_true (f g : NF)
    (hf : NF.allCoeffNonneg f = true) (hg : NF.allCoeffNonneg g = true) :
    NF.allCoeffNonneg (f ++ g) = true := by
  unfold NF.allCoeffNonneg at hf hg ⊢
  exact list_all_append_true _ f g hf hg

theorem nf_allCoeffNonneg_flatten_true :
    ∀ chunks : List NF, chunks.all NF.allCoeffNonneg = true → NF.allCoeffNonneg chunks.flatten = true
  | [], _ => by rfl
  | c :: cs, h => by
      simp only [List.all_cons, Bool.and_eq_true] at h
      simp only [List.flatten_cons]
      exact nf_allCoeffNonneg_append_true c cs.flatten h.1 (nf_allCoeffNonneg_flatten_true cs h.2)

theorem all_nf_allCoeffNonneg_flatten_true :
    ∀ chunks : List (List NF),
      chunks.all (fun xs => xs.all NF.allCoeffNonneg) = true →
      chunks.flatten.all NF.allCoeffNonneg = true
  | [], _ => by rfl
  | c :: cs, h => by
      simp only [List.all_cons, Bool.and_eq_true] at h
      simp only [List.flatten_cons]
      exact list_all_append_true NF.allCoeffNonneg c cs.flatten h.1
        (all_nf_allCoeffNonneg_flatten_true cs h.2)

theorem checkEqPairs_append_true : ∀ xs ys : List (NF × NF),
    checkEqPairs xs = true → checkEqPairs ys = true → checkEqPairs (xs ++ ys) = true
  | [], ys, _, hy => by simpa [checkEqPairs] using hy
  | p :: xs, ys, hx, hy => by
      simp only [checkEqPairs, Bool.and_eq_true] at hx
      change (checkEq p.1 p.2 && checkEqPairs (xs ++ ys)) = true
      rw [hx.1, checkEqPairs_append_true xs ys hx.2 hy]
      rfl

theorem checkEqPairs_flatten_true :
    ∀ chunks : List (List (NF × NF)), chunks.all checkEqPairs = true → checkEqPairs chunks.flatten = true
  | [], _ => by rfl
  | c :: cs, h => by
      simp only [List.all_cons, Bool.and_eq_true] at h
      simp only [List.flatten_cons]
      exact checkEqPairs_append_true c cs.flatten h.1 (checkEqPairs_flatten_true cs h.2)


end Support
end Chart000Cone
end ChartPayloads
end Generated
end O14
end Erdos23Delta0

