/- Generated by _codex_o14_chunked_cone_to_lean_sharded.py; do not edit by hand. -/
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeBase
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS000
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS001
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS002
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS003
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS004
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS005
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS006
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS007
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS008
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS009
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS010
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS011
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS012
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS013
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS014
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS015
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS016
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS017
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS018
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS019
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS020
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS021
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS022
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS023
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS024
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS025
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS026
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS027
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS028
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS029
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS030
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS031
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS032
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS033
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS034
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS035
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS036
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS037
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS038
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS039
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS040
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS041
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS042
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS043
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS044
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs000
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs001
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs002
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs003
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs004
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs005
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs006
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs007
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs008
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs009
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs010
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs011
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs012
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs013
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs014
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs015
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs016
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs017
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs018
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs019
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs020
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs021
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs022
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs023
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs024
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs025
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs026
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs027
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs028
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs029
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs030
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs031
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs032
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs033
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs034
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs035
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs036
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs037
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs038
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs039
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs040
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs041
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs042
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs043
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs044
import Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs045

namespace Erdos23Delta0
namespace O14
namespace Generated
namespace ChartPayloads
namespace Chart000Cone
namespace Main

open PolyCert
open ODLFull
open ConeEvalBridge
open ChunkedCone

set_option maxHeartbeats 0
set_option maxRecDepth 2000000

def slot : Nat := 0
def sourceChart : Nat := 5
def dominant : Nat := 13
def sourceColumns : Nat := 1414
def rawComboTerms : Nat := 46521
def comboOrderChunks : Nat := 727

def base : NF := Base.base
theorem hbase : NF.allCoeffNonneg base = true := by exact Base.hbase

def multShards : List (List NF) := [
  MS000.mults,
  MS001.mults,
  MS002.mults,
  MS003.mults,
  MS004.mults,
  MS005.mults,
  MS006.mults,
  MS007.mults,
  MS008.mults,
  MS009.mults,
  MS010.mults,
  MS011.mults,
  MS012.mults,
  MS013.mults,
  MS014.mults,
  MS015.mults,
  MS016.mults,
  MS017.mults,
  MS018.mults,
  MS019.mults,
  MS020.mults,
  MS021.mults,
  MS022.mults,
  MS023.mults,
  MS024.mults,
  MS025.mults,
  MS026.mults,
  MS027.mults,
  MS028.mults,
  MS029.mults,
  MS030.mults,
  MS031.mults,
  MS032.mults,
  MS033.mults,
  MS034.mults,
  MS035.mults,
  MS036.mults,
  MS037.mults,
  MS038.mults,
  MS039.mults,
  MS040.mults,
  MS041.mults,
  MS042.mults,
  MS043.mults,
  MS044.mults
]

def slackShards : List (List NF) := [
  MS000.slacks,
  MS001.slacks,
  MS002.slacks,
  MS003.slacks,
  MS004.slacks,
  MS005.slacks,
  MS006.slacks,
  MS007.slacks,
  MS008.slacks,
  MS009.slacks,
  MS010.slacks,
  MS011.slacks,
  MS012.slacks,
  MS013.slacks,
  MS014.slacks,
  MS015.slacks,
  MS016.slacks,
  MS017.slacks,
  MS018.slacks,
  MS019.slacks,
  MS020.slacks,
  MS021.slacks,
  MS022.slacks,
  MS023.slacks,
  MS024.slacks,
  MS025.slacks,
  MS026.slacks,
  MS027.slacks,
  MS028.slacks,
  MS029.slacks,
  MS030.slacks,
  MS031.slacks,
  MS032.slacks,
  MS033.slacks,
  MS034.slacks,
  MS035.slacks,
  MS036.slacks,
  MS037.slacks,
  MS038.slacks,
  MS039.slacks,
  MS040.slacks,
  MS041.slacks,
  MS042.slacks,
  MS043.slacks,
  MS044.slacks
]

def mults : List NF := multShards.flatten
def slacks : List NF := slackShards.flatten

theorem hmultShards : multShards.all (fun xs => xs.all NF.allCoeffNonneg) = true := by
  simp [multShards, MS000.hmults, MS001.hmults, MS002.hmults, MS003.hmults, MS004.hmults, MS005.hmults, MS006.hmults, MS007.hmults, MS008.hmults, MS009.hmults, MS010.hmults, MS011.hmults, MS012.hmults, MS013.hmults, MS014.hmults, MS015.hmults, MS016.hmults, MS017.hmults, MS018.hmults, MS019.hmults, MS020.hmults, MS021.hmults, MS022.hmults, MS023.hmults, MS024.hmults, MS025.hmults, MS026.hmults, MS027.hmults, MS028.hmults, MS029.hmults, MS030.hmults, MS031.hmults, MS032.hmults, MS033.hmults, MS034.hmults, MS035.hmults, MS036.hmults, MS037.hmults, MS038.hmults, MS039.hmults, MS040.hmults, MS041.hmults, MS042.hmults, MS043.hmults, MS044.hmults]

theorem hmults : mults.all NF.allCoeffNonneg = true := by
  exact Support.all_nf_allCoeffNonneg_flatten_true multShards hmultShards

def pairShards : List (List (NF × NF)) := [
  Pairs000.pairs,
  Pairs001.pairs,
  Pairs002.pairs,
  Pairs003.pairs,
  Pairs004.pairs,
  Pairs005.pairs,
  Pairs006.pairs,
  Pairs007.pairs,
  Pairs008.pairs,
  Pairs009.pairs,
  Pairs010.pairs,
  Pairs011.pairs,
  Pairs012.pairs,
  Pairs013.pairs,
  Pairs014.pairs,
  Pairs015.pairs,
  Pairs016.pairs,
  Pairs017.pairs,
  Pairs018.pairs,
  Pairs019.pairs,
  Pairs020.pairs,
  Pairs021.pairs,
  Pairs022.pairs,
  Pairs023.pairs,
  Pairs024.pairs,
  Pairs025.pairs,
  Pairs026.pairs,
  Pairs027.pairs,
  Pairs028.pairs,
  Pairs029.pairs,
  Pairs030.pairs,
  Pairs031.pairs,
  Pairs032.pairs,
  Pairs033.pairs,
  Pairs034.pairs,
  Pairs035.pairs,
  Pairs036.pairs,
  Pairs037.pairs,
  Pairs038.pairs,
  Pairs039.pairs,
  Pairs040.pairs,
  Pairs041.pairs,
  Pairs042.pairs,
  Pairs043.pairs,
  Pairs044.pairs,
  Pairs045.pairs
]

def pairs : List (NF × NF) := pairShards.flatten

theorem hpairShards : pairShards.all checkEqPairs = true := by
  simp [pairShards, Pairs000.hchunks, Pairs001.hchunks, Pairs002.hchunks, Pairs003.hchunks, Pairs004.hchunks, Pairs005.hchunks, Pairs006.hchunks, Pairs007.hchunks, Pairs008.hchunks, Pairs009.hchunks, Pairs010.hchunks, Pairs011.hchunks, Pairs012.hchunks, Pairs013.hchunks, Pairs014.hchunks, Pairs015.hchunks, Pairs016.hchunks, Pairs017.hchunks, Pairs018.hchunks, Pairs019.hchunks, Pairs020.hchunks, Pairs021.hchunks, Pairs022.hchunks, Pairs023.hchunks, Pairs024.hchunks, Pairs025.hchunks, Pairs026.hchunks, Pairs027.hchunks, Pairs028.hchunks, Pairs029.hchunks, Pairs030.hchunks, Pairs031.hchunks, Pairs032.hchunks, Pairs033.hchunks, Pairs034.hchunks, Pairs035.hchunks, Pairs036.hchunks, Pairs037.hchunks, Pairs038.hchunks, Pairs039.hchunks, Pairs040.hchunks, Pairs041.hchunks, Pairs042.hchunks, Pairs043.hchunks, Pairs044.hchunks, Pairs045.hchunks]

theorem hchunks : checkEqPairs pairs = true := by
  exact Support.checkEqPairs_flatten_true pairShards hpairShards

def chart000Witness
    {G : CertGraph.GraphData} {c : CertGraph.CutData}
    {rows : CertGraph.RowDB} {Q : CertGraph.RowCert}
    (core : ODLCoreData G c rows Q) (env : Var → ℚ)
    (hvars : ∀ v, 0 ≤ env v)
    (hslacks : ∀ s ∈ slacks, 0 ≤ NF.eval env s)
    (hcombo :
      NF.eval env ((pairs.map Prod.snd).flatten) =
        NF.eval env (comboNF base mults slacks))
    (htarget : NF.eval env ((pairs.map Prod.fst).flatten) = coreDefect core) :
    Witness core where
  pairs := pairs
  base := base
  mults := mults
  slacks := slacks
  env := env
  hvars := hvars
  hbase := hbase
  hmults := hmults
  hslacks := hslacks
  hchunks := hchunks
  hcombo := hcombo
  htarget := htarget

end Main
end Chart000Cone
end ChartPayloads
end Generated
end O14
end Erdos23Delta0

