#include <algorithm>
#include <array>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <map>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

using Clause = std::vector<int>;
static int f5(int x) { return (x % 5 + 5) % 5; }

static int independent_class(int dx, int dy) {
  // Canonical classes, listed independently rather than generated by +/-.
  static const std::pair<int, int> rep[12] = {
      {0, 1}, {0, 2}, {1, 0}, {1, 1}, {1, 2}, {1, 3},
      {1, 4}, {2, 0}, {2, 1}, {2, 2}, {2, 3}, {2, 4}};
  const std::pair<int, int> a{f5(dx), f5(dy)};
  const std::pair<int, int> b{f5(-dx), f5(-dy)};
  const auto target = std::min(a, b);
  for (int k = 0; k < 12; ++k)
    if (rep[k] == target) return k;
  throw std::runtime_error("unknown difference class");
}

static int xvar(int k, int h) { return 5 * k + h + 1; }

static bool advance(std::array<int, 6> &s) {
  for (int i = 5; i >= 0; --i) {
    if (s[i] != 20 + i) {
      ++s[i];
      for (int j = i + 1; j < 6; ++j) s[j] = s[j - 1] + 1;
      return true;
    }
  }
  return false;
}

static std::map<Clause, int> reconstruct(int &coverage, int &tautologies) {
  std::map<Clause, int> expected;
  for (int k = 0; k < 12; ++k) {
    Clause atleast;
    for (int h = 0; h < 5; ++h) atleast.push_back(xvar(k, h));
    ++expected[atleast];
    for (int h = 0; h < 5; ++h)
      for (int j = h + 1; j < 5; ++j)
        ++expected[Clause{-xvar(k, h), -xvar(k, j)}];
  }
  coverage = tautologies = 0;
  std::array<int, 6> s{0, 1, 2, 3, 4, 5};
  do {
    bool already_zero = false;
    Clause clause;
    if (s[5] == 25)
      for (int i = 0; i < 5; ++i)
        if (s[i] / 5 == 0) already_zero = true;
    for (int i = 0; i < 6; ++i)
      for (int j = i + 1; j < 6; ++j) {
        const int u = s[i], v = s[j];
        if (v == 25) continue;
        const int ux = u / 5, uy = u % 5, vx = v / 5, vy = v % 5;
        const int k = independent_class(vx - ux, vy - uy);
        const int target = f5(-3 * (ux + vx));
        clause.push_back(xvar(k, target));
      }
    std::sort(clause.begin(), clause.end());
    clause.erase(std::unique(clause.begin(), clause.end()), clause.end());
    if (already_zero) {
      ++tautologies;
    } else {
      ++expected[clause];
      ++coverage;
    }
  } while (advance(s));
  return expected;
}

static std::map<Clause, int> parse(const std::string &path, int &vars,
                                   int &clauses) {
  std::ifstream in(path);
  if (!in) throw std::runtime_error("cannot read CNF");
  std::map<Clause, int> got;
  bool header = false;
  int parsed = 0;
  std::string line;
  while (std::getline(in, line)) {
    if (line.empty() || line[0] == 'c') continue;
    if (line[0] == 'p') {
      std::istringstream s(line);
      char p;
      std::string cnf, extra;
      if (header || !(s >> p >> cnf >> vars >> clauses) || (s >> extra) ||
          cnf != "cnf")
        throw std::runtime_error("bad header");
      header = true;
      continue;
    }
    if (!header) throw std::runtime_error("clause before header");
    std::istringstream s(line);
    Clause clause;
    int literal;
    bool zero = false;
    while (s >> literal) {
      if (!literal) {
        zero = true;
        std::string extra;
        if (s >> extra) throw std::runtime_error("data after zero");
        break;
      }
      if (std::abs(literal) > vars) throw std::runtime_error("literal range");
      clause.push_back(literal);
    }
    if (!zero || clause.empty()) throw std::runtime_error("bad clause");
    ++got[clause];
    ++parsed;
  }
  if (!header || parsed != clauses) throw std::runtime_error("count mismatch");
  return got;
}

int main(int argc, char **argv) {
  try {
    if (argc != 2) {
      std::cerr << "usage: audit_covariant_cnf INSTANCE.cnf\n";
      return 64;
    }
    int coverage = 0, tautologies = 0, vars = 0, clauses = 0;
    const auto want = reconstruct(coverage, tautologies);
    const auto got = parse(argv[1], vars, clauses);
    if (vars != 60 || got != want)
      throw std::runtime_error("clause multiset differs");
    std::cout << "COVARIANT_CNF_AUDIT_OK vars=60 clauses=" << clauses
              << " classes=12 alo=12 amo=120 coverage=" << coverage
              << " fixed_tautologies=" << tautologies
              << " symmetry_breakers=0\n";
    return 0;
  } catch (const std::exception &e) {
    std::cerr << "COVARIANT_CNF_AUDIT_FAIL " << e.what() << "\n";
    return 1;
  }
}
