#!/usr/bin/env python3
"""Exact audit of maximum-induced-tree degree/girth bounds.

The input corpus is generated by nauty ``geng -ctfq``.  We retain precisely
the biconnected multicyclic graphs of girth at least five and compute the
largest order of an induced tree by exhaustive vertex-subset enumeration.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

import networkx as nx

HERE = Path(__file__).resolve().parent
IND2 = HERE.parent / "attack_ind2_multicycle"
sys.path.insert(0, str(IND2))
from analyze_tight_deletions import cycle_rank, girth, records  # noqa: E402


def maximum_induced_tree(graph: nx.Graph) -> tuple[int, list[int]]:
    """Return exact maximum order and one witness, using bit masks."""
    vertices = list(graph)
    n = len(vertices)
    index = {v: i for i, v in enumerate(vertices)}
    adjacency = [0] * n
    for u, v in graph.edges():
        i, j = index[u], index[v]
        adjacency[i] |= 1 << j
        adjacency[j] |= 1 << i

    def is_tree(mask: int, order: int) -> bool:
        edge_twice = sum((adjacency[i] & mask).bit_count() for i in range(n) if mask >> i & 1)
        if edge_twice != 2 * (order - 1):
            return False
        seen = 0
        frontier = mask & -mask
        while frontier:
            seen |= frontier
            neighbours = 0
            work = frontier
            while work:
                bit = work & -work
                work ^= bit
                neighbours |= adjacency[bit.bit_length() - 1]
            frontier = neighbours & mask & ~seen
        return seen == mask

    masks_by_order: list[list[int]] = [[] for _ in range(n + 1)]
    for mask in range(1, 1 << n):
        masks_by_order[mask.bit_count()].append(mask)
    for order in range(n, 0, -1):
        for mask in masks_by_order[order]:
            if is_tree(mask, order):
                return order, [vertices[i] for i in range(n) if mask >> i & 1]
    raise AssertionError("a singleton is always an induced tree")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--max-n", type=int, default=13)
    parser.add_argument("--output", type=Path, default=HERE / "degree_girth_audit.json")
    args = parser.parse_args()

    counts = Counter()
    first_plus_one = None
    first_plus_two = None
    minimum_slack_plus_two = None
    equality_plus_two = None
    per_order: dict[int, int] = {}

    for n in range(5, args.max_n + 1):
        order_count = 0
        for code, graph in records(n):
            g = girth(graph)
            if g is None or g < 5 or cycle_rank(graph) < 2 or not nx.is_biconnected(graph):
                continue
            order_count += 1
            counts["graphs"] += 1
            delta = max(dict(graph.degree()).values())
            tree, witness = maximum_induced_tree(graph)
            record = {
                "graph6": code.decode(),
                "n": n,
                "m": graph.number_of_edges(),
                "girth": g,
                "maximum_degree": delta,
                "tree": tree,
                "witness": sorted(witness),
                "slack_plus_g_minus_1": tree - (delta + g - 1),
                "slack_plus_g_minus_2": tree - (delta + g - 2),
                "edges": sorted([min(u, v), max(u, v)] for u, v in graph.edges()),
            }
            if record["slack_plus_g_minus_1"] < 0:
                counts["fails_plus_g_minus_1"] += 1
                if first_plus_one is None:
                    first_plus_one = record
            if record["slack_plus_g_minus_2"] < 0:
                counts["fails_plus_g_minus_2"] += 1
                if first_plus_two is None:
                    first_plus_two = record
            slack = record["slack_plus_g_minus_2"]
            if minimum_slack_plus_two is None or slack < minimum_slack_plus_two:
                minimum_slack_plus_two = slack
                equality_plus_two = record
        per_order[n] = order_count

    result = {
        "scope": "all biconnected multicyclic unlabeled simple graphs of girth at least five generated by geng -ctfq",
        "max_n": args.max_n,
        "per_order": per_order,
        "counts": dict(counts),
        "minimum_slack_plus_g_minus_2": minimum_slack_plus_two,
        "first_failure_plus_g_minus_1": first_plus_one,
        "first_failure_plus_g_minus_2": first_plus_two,
        "first_minimum_slack_plus_g_minus_2": equality_plus_two,
    }
    args.output.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
