#!/usr/bin/env python3
"""Exact obstruction to an additive/nonnegative closed-cone ear deletion.

The witness is an actual side-four hive.  One of its edges has exactly two
tight, adjacent B-rhombi, B(0,2) and B(1,2).  Its closed normal cone is
generated by

    u = (1,-1,0),  v = (0,-1,1).

Deleting either endpoint rhombus leaves an actual facet normal ray.  The
orthogonal projection required by the fixed Berline--Vergne complement map
is half-integral, and the exact BV correction is negative even after the
natural 1/2 normalization for the deleted one-dimensional factor.

All decisions use integers/Fraction only.
"""

from fractions import Fraction
from math import gcd
from pathlib import Path
import sys


HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE / "r4_reeve"))
sys.path.insert(0, str(HERE / "r5_rational"))

from hive4 import _affine_rank, _dot, build_hive4, facets, vertices  # noqa: E402
from hiveR import fixed_A  # noqa: E402


LAMBDA = (3, 2, 1, 0)
MU = (3, 2, 1, 0)
NU = (5, 4, 2, 1)
TARGET_TAGS = (("B", 0, 2), ("B", 1, 2))
EXPECTED_NORMALS = ((1, -1, 0), (0, -1, 1))


def dot(left, right):
    return sum(a * b for a, b in zip(left, right))


def saturation_index_two(rows):
    divisor = 0
    for i in range(3):
        for j in range(i + 1, 3):
            determinant = rows[0][i] * rows[1][j] - rows[0][j] * rows[1][i]
            divisor = gcd(divisor, abs(determinant))
    return divisor


def alpha_two_saturated(u, v):
    """BV constant from the exact normal-pair formula."""
    a = dot(u, u)
    b = dot(v, v)
    c = dot(u, v)
    return Fraction(1, 4) - Fraction(c, 12) * (Fraction(1, a) + Fraction(1, b))


def main():
    polytope = build_hive4(LAMBDA, MU, NU)
    assert polytope["ok"]
    verts = vertices(polytope["A"], polytope["b"])
    assert _affine_rank(verts) == 3

    atlas_rows, _, atlas_tags = fixed_A(4)
    assert atlas_rows == polytope["A"]
    target_rows = tuple(atlas_tags.index(tag) for tag in TARGET_TAGS)
    normals = tuple(tuple(polytope["A"][i]) for i in target_rows)
    assert normals == EXPECTED_NORMALS

    edge = [
        vertex for vertex in verts
        if all(_dot(polytope["A"][i], vertex) == polytope["b"][i]
               for i in target_rows)
    ]
    assert _affine_rank(edge) == 1
    assert tuple(tuple(x) for x in edge) == ((7, 8, 10), (8, 9, 11))

    active = tuple(
        i for i, (row, rhs) in enumerate(zip(polytope["A"], polytope["b"]))
        if all(_dot(row, vertex) == rhs for vertex in edge)
    )
    # This is an actual closed cone: there are no further forced tight rows.
    assert active == target_rows == (4, 11)

    # Deleting either endpoint gives an actual facet containing the edge.
    facet_data = facets(polytope["A"], polytope["b"], verts)
    facet_normals = {tuple(row) for row, _ in facet_data}
    assert set(normals).issubset(facet_normals)
    for row_index in target_rows:
        facet_vertices = [
            vertex for vertex in verts
            if _dot(polytope["A"][row_index], vertex) == polytope["b"][row_index]
        ]
        assert _affine_rank(facet_vertices) == 2
        centroid = tuple(
            sum(vertex[j] for vertex in facet_vertices) / len(facet_vertices)
            for j in range(3)
        )
        assert all(
            _dot(row, centroid) < rhs
            for i, (row, rhs) in enumerate(zip(polytope["A"], polytope["b"]))
            if i != row_index
        )

    u, v = normals
    assert set(i for i, value in enumerate(u) if value) & set(
        i for i, value in enumerate(v) if value
    ) == {1}
    assert saturation_index_two(normals) == 1
    assert dot(u, u) == dot(v, v) == 2
    assert dot(u, v) == 1

    alpha_cone = alpha_two_saturated(u, v)
    alpha_ray = Fraction(1, 2)
    assert alpha_cone == Fraction(1, 6)

    # The literal additive deletion required by Route B has negative
    # correction.  Even inserting the natural alpha(ray)=1/2 factor for the
    # deleted one-dimensional direction leaves a negative correction.
    additive_correction = alpha_cone - alpha_ray
    factor_normalized_correction = alpha_cone - alpha_ray * alpha_ray
    assert additive_correction == Fraction(-1, 3)
    assert factor_normalized_correction == Fraction(-1, 12)

    # The fixed BV complement is Euclidean.  Orthogonal projection from the
    # saturated normal plane to either retained primitive ray is half-integral:
    # proj_u(v)=(<u,v>/<u,u>)u=u/2, and symmetrically for proj_v(u).
    projection_coefficient_uv = Fraction(dot(u, v), dot(u, u))
    projection_coefficient_vu = Fraction(dot(u, v), dot(v, v))
    assert projection_coefficient_uv == projection_coefficient_vu == Fraction(1, 2)
    assert projection_coefficient_uv.denominator != 1
    assert projection_coefficient_vu.denominator != 1

    print("PASS")
    print(f"triple={LAMBDA};{MU};{NU}")
    print(f"edge={tuple(tuple(x) for x in edge)}")
    print(f"active_rows={active} active_tags={TARGET_TAGS}")
    print(f"normal_rays={normals} saturation_index=1")
    print("gram=((2,1),(1,2))")
    print(f"alpha_closed_cone={alpha_cone}")
    print(f"alpha_deleted_ray={alpha_ray}")
    print(f"additive_correction={additive_correction}")
    print(f"factor_normalized_correction={factor_normalized_correction}")
    print(f"orthogonal_projection_coefficients=({projection_coefficient_uv},{projection_coefficient_vu})")
    print("verdict=INCOMPATIBLE_LATTICE_AND_NEGATIVE_CORRECTION")


if __name__ == "__main__":
    main()

