/- Generated by _codex_branchb_jsonl_to_lean.py.
   Branch-B certificate row data; do not edit by hand. -/

/- Generated Branch-B certificate support definitions. -/
import Mathlib

namespace Erdos23Delta0
namespace Cert

inductive BranchBCase where
  | tightZero
  | freePacketExchange
  | sparseM1BankLBypass
  | muNuk
  | muNukRepaired
  | detourResidual
deriving Repr, DecidableEq

inductive DictClass where
  | empty
  | terminalPrefixRawExtraction
  | terminalPrefixLaneAddition
  | noncrossingCoBExtraction
  | noncrossingCoBComponentAddition
deriving Repr, DecidableEq

inductive GateBCandidate where
  | none
  | candidateV1
  | candidateV2
deriving Repr, DecidableEq

def GateBCandidate.expectsOps : GateBCandidate -> Bool
  | GateBCandidate.none => false
  | GateBCandidate.candidateV1 => true
  | GateBCandidate.candidateV2 => true

structure ScaledEqCert where
  terms : List Int
  target : Int
  den : Nat
  proofMode : String
deriving Repr

structure ScaledGeCert where
  lhs : Int
  rhs : Int
  margin : Nat
  den : Nat
  proofMode : String
deriving Repr

def intListSum : List Int -> Int
  | [] => 0
  | x :: xs => x + intListSum xs

def natListSum : List Nat -> Nat
  | [] => 0
  | x :: xs => x + natListSum xs

def ScaledEqCert.check (c : ScaledEqCert) : Bool :=
  (c.den != 0) && (intListSum c.terms == c.target)

def ScaledGeCert.check (c : ScaledGeCert) : Bool :=
  (c.den != 0) && (c.lhs + Int.ofNat c.margin == c.rhs)

structure OpStepPilot where
  opClass : DictClass
  stepRole : String
  eB_XS : Int
  eM_XS : Int
  eB_XO : Int
  eM_XO : Int
  q : Int
  rho : Int
  pieceCount : Nat
  pieceContribs : List Nat
  pieceSum : Nat
deriving Repr

def OpStepPilot.expectedQ (s : OpStepPilot) : Int :=
  s.eB_XS - s.eM_XS - s.eB_XO + s.eM_XO

def OpStepPilot.expectedRho (s : OpStepPilot) : Int :=
  if s.q < 0 then 0 else 25 * s.q

def OpStepPilot.check (s : OpStepPilot) : Bool :=
  (s.q == OpStepPilot.expectedQ s) &&
  (s.rho == OpStepPilot.expectedRho s) &&
  (s.pieceContribs.length == s.pieceCount) &&
  (natListSum s.pieceContribs == s.pieceSum) &&
  (s.rho == Int.ofNat s.pieceSum)

def opStepListCheck : List OpStepPilot -> Bool
  | [] => true
  | s :: ss => OpStepPilot.check s && opStepListCheck ss

structure RowPilot where
  name : String
  n : Nat
  m : Nat
  L : Nat
  caseTag : BranchBCase
  gateBCandidate : GateBCandidate
  pressure : ScaledEqCert
  finiteMargin : ScaledGeCert
  opSteps : List OpStepPilot
deriving Repr

def RowPilot.candidateCheck (r : RowPilot) : Bool :=
  GateBCandidate.expectsOps r.gateBCandidate == !r.opSteps.isEmpty

def RowPilot.check (r : RowPilot) : Bool :=
  ScaledEqCert.check r.pressure &&
  ScaledGeCert.check r.finiteMargin &&
  RowPilot.candidateCheck r &&
  opStepListCheck r.opSteps

def rowPilotListCheck : List RowPilot -> Bool
  | [] => true
  | r :: rs => RowPilot.check r && rowPilotListCheck rs

end Cert
end Erdos23Delta0

namespace Erdos23Delta0
namespace Cert

def branchBRowsShard000 : List RowPilot := [
  { name := "cenJ???CBoBz{?", n := 11, m := 2, L := 7, caseTag := BranchBCase.muNuk, gateBCandidate := GateBCandidate.candidateV2, pressure := { terms := [69], target := 69, den := 1, proofMode := "rfl-or-norm_num" }, finiteMargin := { lhs := 69, rhs := 116, margin := 47, den := 1, proofMode := "rfl-or-norm_num" }, opSteps := [{ opClass := DictClass.empty, stepRole := "add_final_part", eB_XS := 0, eM_XS := 0, eB_XO := 0, eM_XO := 0, q := 0, rho := 0, pieceCount := 0, pieceContribs := [], pieceSum := 0 }, { opClass := DictClass.terminalPrefixRawExtraction, stepRole := "remove_raw_extra_via_complement", eB_XS := 5, eM_XS := 0, eB_XO := 1, eM_XO := 0, q := 4, rho := 100, pieceCount := 1, pieceContribs := [100], pieceSum := 100 }] }
]

set_option maxRecDepth 20000 in
theorem branchBRowsShard000_check : rowPilotListCheck branchBRowsShard000 = true := by
  rfl

end Cert
end Erdos23Delta0
