/- Generated by _codex_branchb_dictionary_audit_to_lean.py.
   Compact dictionary-signature audit for Branch-B JSONL. -/
import Erdos23Delta0.Cert.BranchBSupport

namespace Erdos23Delta0
namespace Cert

structure RatLit where
  num : Int
  den : Nat
deriving Repr

def RatLit.valid (a : RatLit) : Bool :=
  a.den != 0

def RatLit.mulEq (a b c : RatLit) : Bool :=
  RatLit.valid a && RatLit.valid b && RatLit.valid c &&
    a.num * b.num * Int.ofNat c.den == c.num * Int.ofNat a.den * Int.ofNat b.den

inductive RowDictClass where
  | sparseM1DirectIdentity
  | terminalPrefix
  | bConnectedSegmentNoncrossingCoB
  | detourComponentDeficit
  | terminalPrefixNoncrossingCoB
deriving Repr, DecidableEq

inductive OpDictClass where
  | terminalPrefixRawExtraction
  | terminalPrefixLaneAddition
  | noncrossingCoBExtraction
  | noncrossingCoBComponentAddition
deriving Repr, DecidableEq

structure RowDictSignature where
  dictionaryClass : RowDictClass
  value : RatLit
  coeff : RatLit
  contribution : RatLit
  multiplicity : Nat
deriving Repr

structure OpDictSignature where
  dictionaryClass : OpDictClass
  value : RatLit
  coeff : RatLit
  contribution : RatLit
  multiplicity : Nat
deriving Repr

def RowDictSignature.check (s : RowDictSignature) : Bool :=
  RatLit.mulEq s.value s.coeff s.contribution

def OpDictSignature.check (s : OpDictSignature) : Bool :=
  RatLit.mulEq s.value s.coeff s.contribution

def rowDictSignatureListCheck : List RowDictSignature -> Bool
  | [] => true
  | s :: ss => RowDictSignature.check s && rowDictSignatureListCheck ss

def opDictSignatureListCheck : List OpDictSignature -> Bool
  | [] => true
  | s :: ss => OpDictSignature.check s && opDictSignatureListCheck ss

def rowDictMultiplicitySum : List RowDictSignature -> Nat
  | [] => 0
  | s :: ss => s.multiplicity + rowDictMultiplicitySum ss

def opDictMultiplicitySum : List OpDictSignature -> Nat
  | [] => 0
  | s :: ss => s.multiplicity + opDictMultiplicitySum ss

def branchBRowDictSignatures : List RowDictSignature := [
  { dictionaryClass := RowDictClass.terminalPrefix, value := { num := 75, den := 1 }, coeff := { num := 23, den := 25 }, contribution := { num := 69, den := 1 }, multiplicity := 1 }
]

def branchBOpDictSignatures : List OpDictSignature := [
  { dictionaryClass := OpDictClass.terminalPrefixRawExtraction, value := { num := 25, den := 1 }, coeff := { num := 4, den := 1 }, contribution := { num := 100, den := 1 }, multiplicity := 1 }
]

set_option maxRecDepth 20000 in
theorem branchBRowDictSignatures_check :
    rowDictSignatureListCheck branchBRowDictSignatures = true := by
  rfl

set_option maxRecDepth 20000 in
theorem branchBOpDictSignatures_check :
    opDictSignatureListCheck branchBOpDictSignatures = true := by
  rfl

theorem branchBRowDictSignatureCount : branchBRowDictSignatures.length = 1 := by
  rfl

theorem branchBOpDictSignatureCount : branchBOpDictSignatures.length = 1 := by
  rfl

set_option maxRecDepth 20000 in
theorem branchBRowDictOccurrenceTotal :
    rowDictMultiplicitySum branchBRowDictSignatures = 1 := by
  rfl

set_option maxRecDepth 20000 in
theorem branchBOpDictOccurrenceTotal :
    opDictMultiplicitySum branchBOpDictSignatures = 1 := by
  rfl

end Cert
end Erdos23Delta0
