/- Generated by _codex_branchb_dictionary_audit_to_lean.py.
   Compact dictionary-signature audit for Branch-B JSONL. -/
import Erdos23Delta0.Cert.BranchBSupport

namespace Erdos23Delta0
namespace Cert

structure RatLit where
  num : Int
  den : Nat
deriving Repr

def RatLit.valid (a : RatLit) : Bool :=
  a.den != 0

def RatLit.mulEq (a b c : RatLit) : Bool :=
  RatLit.valid a && RatLit.valid b && RatLit.valid c &&
    a.num * b.num * Int.ofNat c.den == c.num * Int.ofNat a.den * Int.ofNat b.den

inductive RowDictClass where
  | sparseM1DirectIdentity
  | terminalPrefix
  | bConnectedSegmentNoncrossingCoB
  | detourComponentDeficit
  | terminalPrefixNoncrossingCoB
deriving Repr, DecidableEq

inductive OpDictClass where
  | terminalPrefixRawExtraction
  | terminalPrefixLaneAddition
  | noncrossingCoBExtraction
  | noncrossingCoBComponentAddition
deriving Repr, DecidableEq

structure RowDictSignature where
  dictionaryClass : RowDictClass
  value : RatLit
  coeff : RatLit
  contribution : RatLit
  multiplicity : Nat
deriving Repr

structure OpDictSignature where
  dictionaryClass : OpDictClass
  value : RatLit
  coeff : RatLit
  contribution : RatLit
  multiplicity : Nat
deriving Repr

def RowDictSignature.check (s : RowDictSignature) : Bool :=
  RatLit.mulEq s.value s.coeff s.contribution

def OpDictSignature.check (s : OpDictSignature) : Bool :=
  RatLit.mulEq s.value s.coeff s.contribution

def rowDictSignatureListCheck : List RowDictSignature -> Bool
  | [] => true
  | s :: ss => RowDictSignature.check s && rowDictSignatureListCheck ss

def opDictSignatureListCheck : List OpDictSignature -> Bool
  | [] => true
  | s :: ss => OpDictSignature.check s && opDictSignatureListCheck ss

def rowDictMultiplicitySum : List RowDictSignature -> Nat
  | [] => 0
  | s :: ss => s.multiplicity + rowDictMultiplicitySum ss

def opDictMultiplicitySum : List OpDictSignature -> Nat
  | [] => 0
  | s :: ss => s.multiplicity + opDictMultiplicitySum ss

def branchBRowDictSignatures : List RowDictSignature := [
  { dictionaryClass := RowDictClass.bConnectedSegmentNoncrossingCoB, value := { num := 147, den := 1 }, coeff := { num := 3, den := 14 }, contribution := { num := 63, den := 2 }, multiplicity := 24 },
  { dictionaryClass := RowDictClass.bConnectedSegmentNoncrossingCoB, value := { num := 147, den := 1 }, coeff := { num := 44, den := 147 }, contribution := { num := 44, den := 1 }, multiplicity := 120 },
  { dictionaryClass := RowDictClass.detourComponentDeficit, value := { num := 1, den := 1 }, coeff := { num := 19, den := 1 }, contribution := { num := 19, den := 1 }, multiplicity := 136 },
  { dictionaryClass := RowDictClass.sparseM1DirectIdentity, value := { num := 1, den := 1 }, coeff := { num := 1, den := 1 }, contribution := { num := 1, den := 1 }, multiplicity := 24 },
  { dictionaryClass := RowDictClass.sparseM1DirectIdentity, value := { num := 4, den := 1 }, coeff := { num := 1, den := 1 }, contribution := { num := 4, den := 1 }, multiplicity := 312 },
  { dictionaryClass := RowDictClass.sparseM1DirectIdentity, value := { num := 9, den := 1 }, coeff := { num := 1, den := 1 }, contribution := { num := 9, den := 1 }, multiplicity := 882 },
  { dictionaryClass := RowDictClass.sparseM1DirectIdentity, value := { num := 14, den := 1 }, coeff := { num := 1, den := 1 }, contribution := { num := 14, den := 1 }, multiplicity := 10 },
  { dictionaryClass := RowDictClass.sparseM1DirectIdentity, value := { num := 16, den := 1 }, coeff := { num := 1, den := 1 }, contribution := { num := 16, den := 1 }, multiplicity := 8245 },
  { dictionaryClass := RowDictClass.sparseM1DirectIdentity, value := { num := 18, den := 1 }, coeff := { num := 1, den := 1 }, contribution := { num := 18, den := 1 }, multiplicity := 14 },
  { dictionaryClass := RowDictClass.sparseM1DirectIdentity, value := { num := 28, den := 1 }, coeff := { num := 1, den := 1 }, contribution := { num := 28, den := 1 }, multiplicity := 112 },
  { dictionaryClass := RowDictClass.sparseM1DirectIdentity, value := { num := 36, den := 1 }, coeff := { num := 1, den := 1 }, contribution := { num := 36, den := 1 }, multiplicity := 200 },
  { dictionaryClass := RowDictClass.sparseM1DirectIdentity, value := { num := 42, den := 1 }, coeff := { num := 1, den := 1 }, contribution := { num := 42, den := 1 }, multiplicity := 882 },
  { dictionaryClass := RowDictClass.sparseM1DirectIdentity, value := { num := 56, den := 1 }, coeff := { num := 1, den := 1 }, contribution := { num := 56, den := 1 }, multiplicity := 8245 },
  { dictionaryClass := RowDictClass.terminalPrefix, value := { num := 50, den := 1 }, coeff := { num := 13, den := 100 }, contribution := { num := 13, den := 2 }, multiplicity := 6 },
  { dictionaryClass := RowDictClass.terminalPrefix, value := { num := 75, den := 1 }, coeff := { num := 19, den := 75 }, contribution := { num := 19, den := 1 }, multiplicity := 45 },
  { dictionaryClass := RowDictClass.terminalPrefix, value := { num := 75, den := 1 }, coeff := { num := 21, den := 50 }, contribution := { num := 63, den := 2 }, multiplicity := 9 },
  { dictionaryClass := RowDictClass.terminalPrefix, value := { num := 75, den := 1 }, coeff := { num := 44, den := 75 }, contribution := { num := 44, den := 1 }, multiplicity := 6 },
  { dictionaryClass := RowDictClass.terminalPrefix, value := { num := 75, den := 1 }, coeff := { num := 113, den := 150 }, contribution := { num := 113, den := 2 }, multiplicity := 6 },
  { dictionaryClass := RowDictClass.terminalPrefix, value := { num := 75, den := 1 }, coeff := { num := 23, den := 25 }, contribution := { num := 69, den := 1 }, multiplicity := 27 },
  { dictionaryClass := RowDictClass.terminalPrefix, value := { num := 98, den := 1 }, coeff := { num := 13, den := 196 }, contribution := { num := 13, den := 2 }, multiplicity := 155 },
  { dictionaryClass := RowDictClass.terminalPrefix, value := { num := 98, den := 1 }, coeff := { num := 19, den := 98 }, contribution := { num := 19, den := 1 }, multiplicity := 99 },
  { dictionaryClass := RowDictClass.terminalPrefix, value := { num := 98, den := 1 }, coeff := { num := 9, den := 28 }, contribution := { num := 63, den := 2 }, multiplicity := 68 },
  { dictionaryClass := RowDictClass.terminalPrefix, value := { num := 98, den := 1 }, coeff := { num := 22, den := 49 }, contribution := { num := 44, den := 1 }, multiplicity := 67 },
  { dictionaryClass := RowDictClass.terminalPrefix, value := { num := 98, den := 1 }, coeff := { num := 113, den := 196 }, contribution := { num := 113, den := 2 }, multiplicity := 15 },
  { dictionaryClass := RowDictClass.terminalPrefix, value := { num := 98, den := 1 }, coeff := { num := 69, den := 98 }, contribution := { num := 69, den := 1 }, multiplicity := 3 },
  { dictionaryClass := RowDictClass.terminalPrefix, value := { num := 123, den := 1 }, coeff := { num := 13, den := 246 }, contribution := { num := 13, den := 2 }, multiplicity := 6 },
  { dictionaryClass := RowDictClass.terminalPrefix, value := { num := 147, den := 1 }, coeff := { num := 3, den := 14 }, contribution := { num := 63, den := 2 }, multiplicity := 8 },
  { dictionaryClass := RowDictClass.terminalPrefix, value := { num := 147, den := 1 }, coeff := { num := 44, den := 147 }, contribution := { num := 44, den := 1 }, multiplicity := 40 },
  { dictionaryClass := RowDictClass.terminalPrefix, value := { num := 196, den := 1 }, coeff := { num := 13, den := 392 }, contribution := { num := 13, den := 2 }, multiplicity := 72 },
  { dictionaryClass := RowDictClass.terminalPrefix, value := { num := 196, den := 1 }, coeff := { num := 19, den := 196 }, contribution := { num := 19, den := 1 }, multiplicity := 24 },
  { dictionaryClass := RowDictClass.terminalPrefixNoncrossingCoB, value := { num := 75, den := 1 }, coeff := { num := 44, den := 75 }, contribution := { num := 44, den := 1 }, multiplicity := 9 },
  { dictionaryClass := RowDictClass.terminalPrefixNoncrossingCoB, value := { num := 75, den := 1 }, coeff := { num := 113, den := 150 }, contribution := { num := 113, den := 2 }, multiplicity := 6 },
  { dictionaryClass := RowDictClass.terminalPrefixNoncrossingCoB, value := { num := 98, den := 1 }, coeff := { num := 13, den := 196 }, contribution := { num := 13, den := 2 }, multiplicity := 24 },
  { dictionaryClass := RowDictClass.terminalPrefixNoncrossingCoB, value := { num := 98, den := 1 }, coeff := { num := 19, den := 98 }, contribution := { num := 19, den := 1 }, multiplicity := 16 },
  { dictionaryClass := RowDictClass.terminalPrefixNoncrossingCoB, value := { num := 98, den := 1 }, coeff := { num := 9, den := 28 }, contribution := { num := 63, den := 2 }, multiplicity := 21 },
  { dictionaryClass := RowDictClass.terminalPrefixNoncrossingCoB, value := { num := 98, den := 1 }, coeff := { num := 22, den := 49 }, contribution := { num := 44, den := 1 }, multiplicity := 15 },
  { dictionaryClass := RowDictClass.terminalPrefixNoncrossingCoB, value := { num := 98, den := 1 }, coeff := { num := 113, den := 196 }, contribution := { num := 113, den := 2 }, multiplicity := 3 },
  { dictionaryClass := RowDictClass.terminalPrefixNoncrossingCoB, value := { num := 147, den := 1 }, coeff := { num := 3, den := 14 }, contribution := { num := 63, den := 2 }, multiplicity := 32 }
]

def branchBOpDictSignatures : List OpDictSignature := [
  { dictionaryClass := OpDictClass.noncrossingCoBComponentAddition, value := { num := 25, den := 1 }, coeff := { num := 1, den := 1 }, contribution := { num := 25, den := 1 }, multiplicity := 68 },
  { dictionaryClass := OpDictClass.noncrossingCoBComponentAddition, value := { num := 25, den := 1 }, coeff := { num := 2, den := 1 }, contribution := { num := 50, den := 1 }, multiplicity := 110 },
  { dictionaryClass := OpDictClass.noncrossingCoBExtraction, value := { num := 25, den := 1 }, coeff := { num := 1, den := 1 }, contribution := { num := 25, den := 1 }, multiplicity := 18 },
  { dictionaryClass := OpDictClass.noncrossingCoBExtraction, value := { num := 25, den := 1 }, coeff := { num := 3, den := 1 }, contribution := { num := 75, den := 1 }, multiplicity := 30 },
  { dictionaryClass := OpDictClass.noncrossingCoBExtraction, value := { num := 25, den := 1 }, coeff := { num := 6, den := 1 }, contribution := { num := 150, den := 1 }, multiplicity := 4 },
  { dictionaryClass := OpDictClass.terminalPrefixLaneAddition, value := { num := 25, den := 1 }, coeff := { num := 2, den := 1 }, contribution := { num := 50, den := 1 }, multiplicity := 9 },
  { dictionaryClass := OpDictClass.terminalPrefixRawExtraction, value := { num := 25, den := 1 }, coeff := { num := 1, den := 1 }, contribution := { num := 25, den := 1 }, multiplicity := 167 },
  { dictionaryClass := OpDictClass.terminalPrefixRawExtraction, value := { num := 25, den := 1 }, coeff := { num := 2, den := 1 }, contribution := { num := 50, den := 1 }, multiplicity := 121 },
  { dictionaryClass := OpDictClass.terminalPrefixRawExtraction, value := { num := 25, den := 1 }, coeff := { num := 3, den := 1 }, contribution := { num := 75, den := 1 }, multiplicity := 162 },
  { dictionaryClass := OpDictClass.terminalPrefixRawExtraction, value := { num := 25, den := 1 }, coeff := { num := 4, den := 1 }, contribution := { num := 100, den := 1 }, multiplicity := 24 }
]

set_option maxRecDepth 20000 in
theorem branchBRowDictSignatures_check :
    rowDictSignatureListCheck branchBRowDictSignatures = true := by
  rfl

set_option maxRecDepth 20000 in
theorem branchBOpDictSignatures_check :
    opDictSignatureListCheck branchBOpDictSignatures = true := by
  rfl

theorem branchBRowDictSignatureCount : branchBRowDictSignatures.length = 38 := by
  rfl

theorem branchBOpDictSignatureCount : branchBOpDictSignatures.length = 10 := by
  rfl

set_option maxRecDepth 20000 in
theorem branchBRowDictOccurrenceTotal :
    rowDictMultiplicitySum branchBRowDictSignatures = 19988 := by
  rfl

set_option maxRecDepth 20000 in
theorem branchBOpDictOccurrenceTotal :
    opDictMultiplicitySum branchBOpDictSignatures = 713 := by
  rfl

end Cert
end Erdos23Delta0
