/- Generated by _codex_core_signatures_to_lean.py.
   Proof-critical Branch-B core operation signatures; do not edit by hand. -/

import Mathlib

namespace Erdos23Delta0
namespace Cert

inductive CoreOpClass where
  | empty
  | terminalPrefixRawExtraction
  | terminalPrefixLaneAddition
  | noncrossingCoBExtraction
  | noncrossingCoBComponentAddition
deriving DecidableEq, Repr

inductive CoreDictClass where
  | empty
  | terminalPrefixRawExtraction
  | terminalPrefixLaneAddition
  | noncrossingCoBExtraction
  | noncrossingCoBComponentAddition
deriving DecidableEq, Repr

inductive CoreStepRole where
  | addFinalPart
  | removeRawExtraViaComplement
deriving DecidableEq, Repr

structure CoreDictDecomp where
  coeff : Int
  contribution : Int
  dictionaryClass : CoreDictClass
  generator : String
  value : Int
deriving Repr

def decompTotal : List CoreDictDecomp -> Int
  | [] => 0
  | d :: ds => d.contribution + decompTotal ds

structure CoreOpSignature where
  signatureId : String
  occurrences : Nat
  opClass : CoreOpClass
  stepRole : CoreStepRole
  eB_XS : Int
  eM_XS : Int
  eB_XO : Int
  eM_XO : Int
  exchangeQ : Int
  rhoA : Int
  decomp : List CoreDictDecomp
deriving Repr

def coreSignatures : List CoreOpSignature := [
  { signatureId := "opcore_e39ab9d89244eccd", occurrences := 679, opClass := CoreOpClass.empty, stepRole := CoreStepRole.addFinalPart, eB_XS := 0, eM_XS := 0, eB_XO := 0, eM_XO := 0, exchangeQ := 0, rhoA := 0, decomp := [] },
  { signatureId := "opcore_520c1b04b823e197", occurrences := 239, opClass := CoreOpClass.empty, stepRole := CoreStepRole.removeRawExtraViaComplement, eB_XS := 0, eM_XS := 0, eB_XO := 0, eM_XO := 0, exchangeQ := 0, rhoA := 0, decomp := [] },
  { signatureId := "opcore_5b48f662a0c9aa14", occurrences := 162, opClass := CoreOpClass.terminalPrefixRawExtraction, stepRole := CoreStepRole.removeRawExtraViaComplement, eB_XS := 4, eM_XS := 0, eB_XO := 1, eM_XO := 0, exchangeQ := 3, rhoA := 75, decomp := [{ coeff := 3, contribution := 75, dictionaryClass := CoreDictClass.terminalPrefixRawExtraction, generator := "unit_positive_exchange_25", value := 25 }] },
  { signatureId := "opcore_11e369889ded31e9", occurrences := 139, opClass := CoreOpClass.terminalPrefixRawExtraction, stepRole := CoreStepRole.removeRawExtraViaComplement, eB_XS := 2, eM_XS := 0, eB_XO := 1, eM_XO := 0, exchangeQ := 1, rhoA := 25, decomp := [{ coeff := 1, contribution := 25, dictionaryClass := CoreDictClass.terminalPrefixRawExtraction, generator := "unit_positive_exchange_25", value := 25 }] },
  { signatureId := "opcore_ffe4ba1f125e6c16", occurrences := 115, opClass := CoreOpClass.terminalPrefixRawExtraction, stepRole := CoreStepRole.removeRawExtraViaComplement, eB_XS := 3, eM_XS := 0, eB_XO := 1, eM_XO := 0, exchangeQ := 2, rhoA := 50, decomp := [{ coeff := 2, contribution := 50, dictionaryClass := CoreDictClass.terminalPrefixRawExtraction, generator := "unit_positive_exchange_25", value := 25 }] },
  { signatureId := "opcore_cb507a62e40039d0", occurrences := 110, opClass := CoreOpClass.noncrossingCoBComponentAddition, stepRole := CoreStepRole.addFinalPart, eB_XS := 1, eM_XS := 0, eB_XO := 0, eM_XO := 1, exchangeQ := 2, rhoA := 50, decomp := [{ coeff := 2, contribution := 50, dictionaryClass := CoreDictClass.noncrossingCoBComponentAddition, generator := "unit_positive_exchange_25", value := 25 }] },
  { signatureId := "opcore_398526891957ae15", occurrences := 48, opClass := CoreOpClass.noncrossingCoBComponentAddition, stepRole := CoreStepRole.addFinalPart, eB_XS := 2, eM_XS := 0, eB_XO := 3, eM_XO := 0, exchangeQ := -1, rhoA := 0, decomp := [] },
  { signatureId := "opcore_45bb7b8fb8731c5f", occurrences := 48, opClass := CoreOpClass.noncrossingCoBComponentAddition, stepRole := CoreStepRole.addFinalPart, eB_XS := 3, eM_XS := 0, eB_XO := 3, eM_XO := 1, exchangeQ := 1, rhoA := 25, decomp := [{ coeff := 1, contribution := 25, dictionaryClass := CoreDictClass.noncrossingCoBComponentAddition, generator := "unit_positive_exchange_25", value := 25 }] },
  { signatureId := "opcore_3345fa59570e3943", occurrences := 45, opClass := CoreOpClass.terminalPrefixRawExtraction, stepRole := CoreStepRole.removeRawExtraViaComplement, eB_XS := 1, eM_XS := 0, eB_XO := 1, eM_XO := 0, exchangeQ := 0, rhoA := 0, decomp := [] },
  { signatureId := "opcore_6debe75aac518868", occurrences := 45, opClass := CoreOpClass.terminalPrefixRawExtraction, stepRole := CoreStepRole.removeRawExtraViaComplement, eB_XS := 2, eM_XS := 1, eB_XO := 1, eM_XO := 0, exchangeQ := 0, rhoA := 0, decomp := [] },
  { signatureId := "opcore_98f0a8e209b89fe6", occurrences := 42, opClass := CoreOpClass.noncrossingCoBExtraction, stepRole := CoreStepRole.removeRawExtraViaComplement, eB_XS := 1, eM_XS := 0, eB_XO := 1, eM_XO := 0, exchangeQ := 0, rhoA := 0, decomp := [] },
  { signatureId := "opcore_f132b261c73365f1", occurrences := 30, opClass := CoreOpClass.noncrossingCoBExtraction, stepRole := CoreStepRole.removeRawExtraViaComplement, eB_XS := 4, eM_XS := 0, eB_XO := 1, eM_XO := 0, exchangeQ := 3, rhoA := 75, decomp := [{ coeff := 3, contribution := 75, dictionaryClass := CoreDictClass.noncrossingCoBExtraction, generator := "unit_positive_exchange_25", value := 25 }] },
  { signatureId := "opcore_c2851d0836ebd479", occurrences := 29, opClass := CoreOpClass.terminalPrefixRawExtraction, stepRole := CoreStepRole.removeRawExtraViaComplement, eB_XS := 1, eM_XS := 1, eB_XO := 1, eM_XO := 0, exchangeQ := -1, rhoA := 0, decomp := [] },
  { signatureId := "opcore_82194a57748e7527", occurrences := 28, opClass := CoreOpClass.terminalPrefixRawExtraction, stepRole := CoreStepRole.removeRawExtraViaComplement, eB_XS := 3, eM_XS := 1, eB_XO := 1, eM_XO := 0, exchangeQ := 1, rhoA := 25, decomp := [{ coeff := 1, contribution := 25, dictionaryClass := CoreDictClass.terminalPrefixRawExtraction, generator := "unit_positive_exchange_25", value := 25 }] },
  { signatureId := "opcore_1594caf2667e3ee7", occurrences := 24, opClass := CoreOpClass.terminalPrefixRawExtraction, stepRole := CoreStepRole.removeRawExtraViaComplement, eB_XS := 5, eM_XS := 0, eB_XO := 1, eM_XO := 0, exchangeQ := 4, rhoA := 100, decomp := [{ coeff := 4, contribution := 100, dictionaryClass := CoreDictClass.terminalPrefixRawExtraction, generator := "unit_positive_exchange_25", value := 25 }] },
  { signatureId := "opcore_a8d35a090d33c589", occurrences := 12, opClass := CoreOpClass.noncrossingCoBExtraction, stepRole := CoreStepRole.removeRawExtraViaComplement, eB_XS := 3, eM_XS := 1, eB_XO := 1, eM_XO := 0, exchangeQ := 1, rhoA := 25, decomp := [{ coeff := 1, contribution := 25, dictionaryClass := CoreDictClass.noncrossingCoBExtraction, generator := "unit_positive_exchange_25", value := 25 }] },
  { signatureId := "opcore_b56607667b610c13", occurrences := 12, opClass := CoreOpClass.noncrossingCoBComponentAddition, stepRole := CoreStepRole.addFinalPart, eB_XS := 1, eM_XS := 0, eB_XO := 1, eM_XO := 1, exchangeQ := 1, rhoA := 25, decomp := [{ coeff := 1, contribution := 25, dictionaryClass := CoreDictClass.noncrossingCoBComponentAddition, generator := "unit_positive_exchange_25", value := 25 }] },
  { signatureId := "opcore_9b10d1b3b87b1b63", occurrences := 9, opClass := CoreOpClass.terminalPrefixLaneAddition, stepRole := CoreStepRole.addFinalPart, eB_XS := 1, eM_XS := 0, eB_XO := 0, eM_XO := 1, exchangeQ := 2, rhoA := 50, decomp := [{ coeff := 2, contribution := 50, dictionaryClass := CoreDictClass.terminalPrefixLaneAddition, generator := "unit_positive_exchange_25", value := 25 }] },
  { signatureId := "opcore_9060d5536919b019", occurrences := 8, opClass := CoreOpClass.noncrossingCoBComponentAddition, stepRole := CoreStepRole.addFinalPart, eB_XS := 1, eM_XS := 0, eB_XO := 2, eM_XO := 0, exchangeQ := -1, rhoA := 0, decomp := [] },
  { signatureId := "opcore_f4da989c2c13bc90", occurrences := 8, opClass := CoreOpClass.noncrossingCoBComponentAddition, stepRole := CoreStepRole.addFinalPart, eB_XS := 2, eM_XS := 0, eB_XO := 2, eM_XO := 1, exchangeQ := 1, rhoA := 25, decomp := [{ coeff := 1, contribution := 25, dictionaryClass := CoreDictClass.noncrossingCoBComponentAddition, generator := "unit_positive_exchange_25", value := 25 }] },
  { signatureId := "opcore_84bec13e67e7119b", occurrences := 6, opClass := CoreOpClass.terminalPrefixRawExtraction, stepRole := CoreStepRole.removeRawExtraViaComplement, eB_XS := 4, eM_XS := 1, eB_XO := 1, eM_XO := 0, exchangeQ := 2, rhoA := 50, decomp := [{ coeff := 2, contribution := 50, dictionaryClass := CoreDictClass.terminalPrefixRawExtraction, generator := "unit_positive_exchange_25", value := 25 }] },
  { signatureId := "opcore_a649570f766344e7", occurrences := 6, opClass := CoreOpClass.noncrossingCoBExtraction, stepRole := CoreStepRole.removeRawExtraViaComplement, eB_XS := 2, eM_XS := 0, eB_XO := 1, eM_XO := 0, exchangeQ := 1, rhoA := 25, decomp := [{ coeff := 1, contribution := 25, dictionaryClass := CoreDictClass.noncrossingCoBExtraction, generator := "unit_positive_exchange_25", value := 25 }] },
  { signatureId := "opcore_0e869bc080f7b1b1", occurrences := 4, opClass := CoreOpClass.noncrossingCoBComponentAddition, stepRole := CoreStepRole.addFinalPart, eB_XS := 0, eM_XS := 0, eB_XO := 2, eM_XO := 1, exchangeQ := -1, rhoA := 0, decomp := [] },
  { signatureId := "opcore_d5c79ded794a6ff6", occurrences := 4, opClass := CoreOpClass.noncrossingCoBExtraction, stepRole := CoreStepRole.removeRawExtraViaComplement, eB_XS := 6, eM_XS := 0, eB_XO := 0, eM_XO := 0, exchangeQ := 6, rhoA := 150, decomp := [{ coeff := 6, contribution := 150, dictionaryClass := CoreDictClass.noncrossingCoBExtraction, generator := "unit_positive_exchange_25", value := 25 }] }
]

theorem coreSignatures_length : coreSignatures.length = 24 := by
  rfl

def coreSignatureDecompAudit : List (Int × Int) :=
  coreSignatures.map (fun s => (decompTotal s.decomp, s.rhoA))

theorem coreSignatureDecompAudit_expected :
    coreSignatureDecompAudit = [(0, 0), (0, 0), (75, 75), (25, 25), (50, 50), (50, 50), (0, 0), (25, 25), (0, 0), (0, 0), (0, 0), (75, 75), (0, 0), (25, 25), (100, 100), (25, 25), (25, 25), (50, 50), (0, 0), (25, 25), (50, 50), (25, 25), (0, 0), (150, 150)] := by
  rfl

def coreSignatureDecompMargins : List Int :=
  coreSignatures.map (fun s => s.rhoA - decompTotal s.decomp)

theorem coreSignatureDecompMargins_zero :
    coreSignatureDecompMargins = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] := by
  rfl

end Cert
end Erdos23Delta0
