/- Generated by _codex_tau0_rawpoly_shards_to_lean.py.
   tau_0 MCERT shard manifest data; term payloads live in RowXX.lean. -/

import Mathlib

namespace Erdos23Delta0
namespace Cert

structure Tau0RowMeta where
  index : Nat
  row : List Nat
  termCount : Nat
  totalDegree : Nat
deriving Repr

def tau0Graph : String := "I?BD@g]Qo"
def tau0Side : String := "0001111000"
def tau0VariableNames : List String := ["w0", "w1", "w2", "w3", "w4", "w5", "w6", "w7", "w8", "w9", "z"]
def tau0ActiveRow : List Nat := [7, 5, 8, 6, 9]

def tau0RowsMeta : List Tau0RowMeta := [
  { index := 0, row := [1, 5, 0, 6, 9], termCount := 2077, totalDegree := 17 },
  { index := 1, row := [1, 5, 8, 4, 9], termCount := 2380, totalDegree := 17 },
  { index := 2, row := [1, 5, 8, 6, 9], termCount := 1810, totalDegree := 17 },
  { index := 3, row := [7, 5, 0, 6, 2], termCount := 2077, totalDegree := 17 },
  { index := 4, row := [7, 5, 8, 6, 2], termCount := 1810, totalDegree := 17 },
  { index := 5, row := [7, 3, 8, 6, 2], termCount := 2380, totalDegree := 17 },
  { index := 6, row := [7, 5, 0, 6, 9], termCount := 1710, totalDegree := 17 },
  { index := 7, row := [7, 5, 8, 4, 9], termCount := 2013, totalDegree := 17 },
  { index := 8, row := [7, 5, 8, 6, 9], termCount := 1443, totalDegree := 17 },
  { index := 9, row := [7, 3, 8, 4, 9], termCount := 2583, totalDegree := 17 },
  { index := 10, row := [7, 3, 8, 6, 9], termCount := 2013, totalDegree := 17 }
]

theorem tau0RowsMeta_length : tau0RowsMeta.length = 11 := by
  rfl

end Cert
end Erdos23Delta0
