import Erdos23Delta0.Gamma.WeakProbeClassTightness
import Erdos23Delta0.Gamma.CanonicalCollisionLexSelection
import Erdos23Delta0.Gamma.CanonicalCollisionProgress
import Erdos23Delta0.Gamma.CollisionDefectGraphAdapter
import Erdos23Delta0.Gamma.CanonicalCollisionGraphSelection

#print axioms Erdos23Delta0.Gamma.WeakProbeClassTightness.one_class_zero_of_pair_sum_lt_two
#print axioms Erdos23Delta0.Gamma.CanonicalCollisionGraphSelection.feasibility_iff_canonical_total
#print axioms Erdos23Delta0.Gamma.CanonicalCollisionGraphSelection.finiteAuditCode_injective
