import Erdos23Delta0.BankedWallLPRestricted

/-!
# Strict restricted duals force weighted routing failure

This is the R3 bookkeeping step between a singleton/allowed almost-squeeze
and the closed weighted Hall layer.  If a restricted dual is strict, but an
allowed nonnegative cut combination already dominates its α-mass and respects
the unit short-edge capacities, then the γ-weighted port load produced by that
combination must exceed the δ-weighted bank capacity.
-/

namespace Erdos23Delta0
namespace Wall

open scoped BigOperators

variable {I : BankedWallLP}

/-- A squeeze before bank routing: it uses only allowed cuts, dominates the
dual α objective, and respects the in-support short-edge capacities. -/
structure DualAlmostSqueeze (I : BankedWallLP) (Allowed : I.Cut → Prop)
    (d : Dual I) where
  theta : I.Cut → ℚ
  theta_nonneg : ∀ X, 0 ≤ theta X
  theta_allowed : ∀ X, theta X ≠ 0 → Allowed X
  alpha_dominated : totalAlpha d ≤ ∑ X : I.Cut, theta X * cutAlpha d X
  short_coeff : ∀ f : I.Short, (∑ X : I.Cut, theta X * I.useShort X f) ≤ 1

/-- Port load generated by an almost-squeeze. -/
def DualAlmostSqueeze.portLoad
    {Allowed : I.Cut → Prop} {d : Dual I}
    (Z : DualAlmostSqueeze I Allowed d) (p : I.Port) : ℚ :=
  ∑ X : I.Cut, Z.theta X * I.cutPort X p

/-- Weighted routing failure for a port load against a checked dual. -/
def WeightedRoutingFailure (d : Dual I) (L : I.Port → ℚ) : Prop :=
  totalDeltaCap d < ∑ p : I.Port, L p * d.gamma p

/-- The β part of an almost-squeeze is at most the dual β budget. -/
private theorem almostSqueeze_beta_le_total
    {Allowed : I.Cut → Prop} {d : Dual I}
    (hd : d.RestrictedChecked Allowed) (Z : DualAlmostSqueeze I Allowed d) :
    (∑ X : I.Cut, Z.theta X * cutBeta d X) ≤ totalBeta d := by
  have hswapb : (∑ X : I.Cut, Z.theta X * cutBeta d X)
      = ∑ f : I.Short, (∑ X : I.Cut, Z.theta X * I.useShort X f) * d.beta f := by
    simp only [cutBeta, Finset.mul_sum, Finset.sum_mul, mul_assoc]
    rw [Finset.sum_comm]
  rw [hswapb]
  refine Finset.sum_le_sum fun f _ => ?_
  calc (∑ X : I.Cut, Z.theta X * I.useShort X f) * d.beta f
      ≤ 1 * d.beta f := mul_le_mul_of_nonneg_right (Z.short_coeff f) (hd.beta_nonneg f)
    _ = d.beta f := one_mul _

/-- Restricted D1 plus an almost-squeeze bounds α by β plus generated γ-port
load. -/
private theorem totalAlpha_le_beta_plus_portGamma
    {Allowed : I.Cut → Prop} {d : Dual I}
    (hd : d.RestrictedChecked Allowed) (Z : DualAlmostSqueeze I Allowed d) :
    totalAlpha d ≤ totalBeta d +
      ∑ p : I.Port, Z.portLoad p * d.gamma p := by
  have hD1 : (∑ X : I.Cut, Z.theta X * cutAlpha d X)
      ≤ ∑ X : I.Cut, Z.theta X * (cutBeta d X + cutGamma d X) := by
    refine Finset.sum_le_sum fun X _ => ?_
    by_cases htheta : Z.theta X = 0
    · simp [htheta]
    · exact mul_le_mul_of_nonneg_left
        (hd.d1_allowed X (Z.theta_allowed X htheta)) (Z.theta_nonneg X)
  have hsplit : (∑ X : I.Cut, Z.theta X * (cutBeta d X + cutGamma d X))
      = (∑ X : I.Cut, Z.theta X * cutBeta d X) +
        ∑ X : I.Cut, Z.theta X * cutGamma d X := by
    rw [← Finset.sum_add_distrib]
    exact Finset.sum_congr rfl fun X _ => mul_add _ _ _
  have hgamma : (∑ X : I.Cut, Z.theta X * cutGamma d X)
      = ∑ p : I.Port, Z.portLoad p * d.gamma p := by
    unfold DualAlmostSqueeze.portLoad
    simp only [cutGamma, Finset.mul_sum, Finset.sum_mul, mul_assoc]
    rw [Finset.sum_comm]
  have hbeta := almostSqueeze_beta_le_total hd Z
  calc totalAlpha d
      ≤ ∑ X : I.Cut, Z.theta X * cutAlpha d X := Z.alpha_dominated
    _ ≤ ∑ X : I.Cut, Z.theta X * (cutBeta d X + cutGamma d X) := hD1
    _ = (∑ X : I.Cut, Z.theta X * cutBeta d X) +
        ∑ X : I.Cut, Z.theta X * cutGamma d X := hsplit
    _ ≤ totalBeta d + ∑ p : I.Port, Z.portLoad p * d.gamma p := by
      rw [hgamma]
      exact add_le_add hbeta (le_refl _)

/-- R3 bookkeeping: a strict restricted dual and an allowed almost-squeeze
force weighted routing failure. -/
theorem strictRestrictedDual_gives_weightedRoutingFailure
    {Allowed : I.Cut → Prop} {d : Dual I}
    (hd : d.RestrictedChecked Allowed) (Z : DualAlmostSqueeze I Allowed d)
    (hstrict : d.StrictGap) :
    WeightedRoutingFailure d Z.portLoad := by
  unfold WeightedRoutingFailure
  have hα := totalAlpha_le_beta_plus_portGamma hd Z
  unfold Dual.StrictGap at hstrict
  linarith

end Wall
end Erdos23Delta0
