import Erdos23Delta0.ClosedShoreProperSplit
import Mathlib.Combinatorics.SimpleGraph.Connectivity.WalkCounting

/-!
# Port-component separation for the abstract closed-shore split

This module formalizes only the exact abstract part of the R11 port-component
construction.  A parameter `primitive` records adjacency inside primitive
full-escape blocks.  `Coupled` symmetrizes that relation and also joins ports
with a common legal bank sink.  The right shore is the union of coupling
components meeting `seedR`; the left shore is its complement in `parent`.

The resulting shores form a strict closed partition with disjoint legal sink
neighborhoods whenever both seeds are nonempty, no coupling component meets
both seeds, and the supplied closure interface recognizes primitive-block
saturated subsets.  The final split uses
`properClosedBankSplitOfDisjointNeighbors` at the original load.

No theorem in this file constructs the real extractor data or proves its
no-mixed-component property.  `RealExtractorNMCBlockSaturationProvider` is the
explicit open provider contract for exactly those two facts.
-/

namespace Erdos23Delta0
namespace Wall
namespace ClosedShore

open PortHall

variable {I : BankedWallLP} {Q : AbstractEscapeQuotient I}

local instance legalDecidable (p : I.Port) (s : I.Sink) :
    Decidable (I.legal p s) := I.legalDecidable p s

/-- Symmetric adjacency generated by the supplied primitive-block relation. -/
def PrimitiveCoupled (primitive : I.Port → I.Port → Prop) (p q : I.Port) : Prop :=
  primitive p q ∨ primitive q p

theorem primitiveCoupled_symmetric (primitive : I.Port → I.Port → Prop) :
    Symmetric (PrimitiveCoupled primitive) := by
  intro p q hpq
  simpa only [PrimitiveCoupled, or_comm] using hpq

/-- Two parent ports are coupled when they lie in one primitive full-escape
block or have a common legal bank sink. -/
def Coupled (I : BankedWallLP) (primitive : I.Port → I.Port → Prop)
    (parent : Finset I.Port) (p q : I.Port) : Prop :=
  p ∈ parent ∧ q ∈ parent ∧
    (PrimitiveCoupled primitive p q ∨
      ∃ s : I.Sink, I.legal p s ∧ I.legal q s)

theorem coupled_symmetric (primitive : I.Port → I.Port → Prop)
    (parent : Finset I.Port) : Symmetric (Coupled I primitive parent) := by
  intro p q hpq
  rcases hpq with ⟨hp, hq, hcoupled⟩
  refine And.intro hq (And.intro hp ?_)
  rcases hcoupled with hprimitive | hsink
  . exact Or.inl (primitiveCoupled_symmetric primitive hprimitive)
  . rcases hsink with ⟨s, hps, hqs⟩
    exact Or.inr (Exists.intro s (And.intro hqs hps))

/-- With decidable primitive adjacency, `Coupled` is a decidable relation on
the finite port type. -/
instance instDecidableCoupled (I : BankedWallLP)
    (primitive : I.Port → I.Port → Prop) (parent : Finset I.Port)
    [DecidableEq I.Port] [DecidableRel primitive] :
    DecidableRel (Coupled I primitive parent) := by
  intro p q
  unfold Coupled PrimitiveCoupled
  infer_instance

/-- The finite simple graph generated by `Coupled`.  `fromRel` removes loops;
reachability below restores reflexivity and takes the transitive closure. -/
def couplingGraph (I : BankedWallLP) (primitive : I.Port → I.Port → Prop)
    (parent : Finset I.Port) : SimpleGraph I.Port :=
  SimpleGraph.fromRel (Coupled I primitive parent)

instance instDecidableCouplingGraphAdj (I : BankedWallLP)
    (primitive : I.Port → I.Port → Prop) (parent : Finset I.Port)
    [DecidableEq I.Port] [DecidableRel primitive] :
    DecidableRel (couplingGraph I primitive parent).Adj := by
  change DecidableRel (SimpleGraph.fromRel (Coupled I primitive parent)).Adj
  infer_instance


theorem coupled_reachable (primitive : I.Port → I.Port → Prop)
    (parent : Finset I.Port) {p q : I.Port}
    (hpq : Coupled I primitive parent p q) :
    (couplingGraph I primitive parent).Reachable p q := by
  by_cases hpq_ne : p = q
  . subst q
    exact SimpleGraph.Reachable.refl p
  . apply SimpleGraph.Adj.reachable
    exact (SimpleGraph.fromRel_adj (Coupled I primitive parent) p q).2
      (And.intro hpq_ne (Or.inl hpq))

theorem coupling_reachable_iff_reflTransGen
    (primitive : I.Port → I.Port → Prop) (parent : Finset I.Port)
    (p q : I.Port) :
    (couplingGraph I primitive parent).Reachable p q ↔
      Relation.ReflTransGen (couplingGraph I primitive parent).Adj p q :=
  SimpleGraph.reachable_iff_reflTransGen _ _

/-- No coupling component contains both a left seed and a right seed. -/
def NoMixedCornerPortComponent (I : BankedWallLP)
    (primitive : I.Port → I.Port → Prop)
    (parent seedL seedR : Finset I.Port) : Prop :=
  ∀ p ∈ seedL, ∀ q ∈ seedR,
    ¬(couplingGraph I primitive parent).Reachable p q

instance instDecidableNoMixedCornerPortComponent (I : BankedWallLP)
    (primitive : I.Port → I.Port → Prop)
    (parent seedL seedR : Finset I.Port)
    [DecidableEq I.Port] [DecidableRel primitive] :
    Decidable (NoMixedCornerPortComponent I primitive parent seedL seedR) := by
  unfold NoMixedCornerPortComponent
  infer_instance

/-- Exact finite Boolean checker for `NoMixedCornerPortComponent`. -/
def noMixedCornerPortComponentBool (I : BankedWallLP)
    (primitive : I.Port → I.Port → Prop)
    (parent seedL seedR : Finset I.Port)
    [DecidableEq I.Port] [DecidableRel primitive] : Bool :=
  decide (NoMixedCornerPortComponent I primitive parent seedL seedR)

theorem noMixedCornerPortComponentBool_eq_true_iff
    (I : BankedWallLP) (primitive : I.Port → I.Port → Prop)
    (parent seedL seedR : Finset I.Port)
    [DecidableEq I.Port] [DecidableRel primitive] :
    noMixedCornerPortComponentBool I primitive parent seedL seedR = true ↔
      NoMixedCornerPortComponent I primitive parent seedL seedR := by
  simp only [noMixedCornerPortComponentBool, decide_eq_true_eq]

theorem noMixedCornerPortComponentBool_eq_false_iff
    (I : BankedWallLP) (primitive : I.Port → I.Port → Prop)
    (parent seedL seedR : Finset I.Port)
    [DecidableEq I.Port] [DecidableRel primitive] :
    noMixedCornerPortComponentBool I primitive parent seedL seedR = false ↔
      ¬NoMixedCornerPortComponent I primitive parent seedL seedR := by
  simp only [noMixedCornerPortComponentBool, decide_eq_false_iff_not]

attribute [local instance] PortHall.portDecEq

open Classical in
/-- Parent ports in a coupling component meeting the right seed. -/
noncomputable def rightPorts (I : BankedWallLP)
    (primitive : I.Port → I.Port → Prop)
    (parent seedR : Finset I.Port) : Finset I.Port :=
  parent.filter fun p =>
    ∃ q ∈ seedR,
      (couplingGraph I primitive parent).Reachable p q

/-- All remaining parent ports; unseeded components are assigned left. -/
noncomputable def leftPorts (I : BankedWallLP)
    (primitive : I.Port → I.Port → Prop)
    (parent seedR : Finset I.Port) : Finset I.Port :=
  parent \ rightPorts I primitive parent seedR

theorem mem_rightPorts (primitive : I.Port → I.Port → Prop)
    {parent seedR : Finset I.Port} {p : I.Port} :
    p ∈ rightPorts I primitive parent seedR ↔
      p ∈ parent ∧ ∃ q ∈ seedR,
        (couplingGraph I primitive parent).Reachable p q := by
  classical
  simp only [rightPorts, Finset.mem_filter]

theorem mem_leftPorts (primitive : I.Port → I.Port → Prop)
    {parent seedR : Finset I.Port} {p : I.Port} :
    p ∈ leftPorts I primitive parent seedR ↔
      p ∈ parent ∧ p ∉ rightPorts I primitive parent seedR := by
  classical
  simp only [leftPorts, Finset.mem_sdiff]

theorem rightPorts_subset_parent (primitive : I.Port → I.Port → Prop)
    (parent seedR : Finset I.Port) :
    rightPorts I primitive parent seedR ⊆ parent := by
  intro p hp
  exact (mem_rightPorts primitive).mp hp |>.1

theorem leftPorts_subset_parent (primitive : I.Port → I.Port → Prop)
    (parent seedR : Finset I.Port) :
    leftPorts I primitive parent seedR ⊆ parent := by
  intro p hp
  exact (mem_leftPorts primitive).mp hp |>.1

theorem seedR_subset_rightPorts (primitive : I.Port → I.Port → Prop)
    {parent seedR : Finset I.Port} (hseedR : seedR ⊆ parent) :
    seedR ⊆ rightPorts I primitive parent seedR := by
  intro q hq
  apply (mem_rightPorts primitive).2
  exact And.intro (hseedR hq)
    (Exists.intro q (And.intro hq (SimpleGraph.Reachable.refl q)))

theorem seedL_subset_leftPorts (primitive : I.Port → I.Port → Prop)
    {parent seedL seedR : Finset I.Port}
    (hseedL : seedL ⊆ parent)
    (hNMC : NoMixedCornerPortComponent I primitive parent seedL seedR) :
    seedL ⊆ leftPorts I primitive parent seedR := by
  intro p hp
  apply (mem_leftPorts primitive).2
  refine And.intro (hseedL hp) ?_
  intro hpright
  rcases (mem_rightPorts primitive).1 hpright with ⟨_, q, hq, hpq⟩
  exact hNMC p hp q hq hpq

theorem rightPorts_closed_under_coupled
    (primitive : I.Port → I.Port → Prop)
    {parent seedR : Finset I.Port} {p q : I.Port}
    (hp : p ∈ rightPorts I primitive parent seedR)
    (hpq : Coupled I primitive parent p q) :
    q ∈ rightPorts I primitive parent seedR := by
  rcases (mem_rightPorts primitive).1 hp with ⟨_, r, hr, hpr⟩
  apply (mem_rightPorts primitive).2
  refine And.intro hpq.2.1 (Exists.intro r (And.intro hr ?_))
  exact SimpleGraph.Reachable.trans
    (SimpleGraph.Reachable.symm (coupled_reachable primitive parent hpq)) hpr

theorem leftPorts_closed_under_coupled
    (primitive : I.Port → I.Port → Prop)
    {parent seedR : Finset I.Port} {p q : I.Port}
    (hp : p ∈ leftPorts I primitive parent seedR)
    (hpq : Coupled I primitive parent p q) :
    q ∈ leftPorts I primitive parent seedR := by
  apply (mem_leftPorts primitive).2
  refine And.intro hpq.2.1 ?_
  intro hqright
  exact (mem_leftPorts primitive).1 hp |>.2
    (rightPorts_closed_under_coupled primitive hqright
      (coupled_symmetric primitive parent hpq))

/-- Saturation under all coupling edges, equivalently being a union of
coupling components inside `parent`. -/
def CouplingSaturatedIn (I : BankedWallLP)
    (primitive : I.Port → I.Port → Prop)
    (parent S : Finset I.Port) : Prop :=
  ∀ {p q}, p ∈ S → Coupled I primitive parent p q → q ∈ S

theorem rightPorts_couplingSaturated
    (primitive : I.Port → I.Port → Prop)
    (parent seedR : Finset I.Port) :
    CouplingSaturatedIn I primitive parent
      (rightPorts I primitive parent seedR) := by
  intro p q hp hpq
  exact rightPorts_closed_under_coupled primitive hp hpq

theorem leftPorts_couplingSaturated
    (primitive : I.Port → I.Port → Prop)
    (parent seedR : Finset I.Port) :
    CouplingSaturatedIn I primitive parent
      (leftPorts I primitive parent seedR) := by
  intro p q hp hpq
  exact leftPorts_closed_under_coupled primitive hp hpq

/-- Direct closure hypothesis: every parent subset that is a union of coupling
components is a `ClosedPortSet`. -/
def CouplingComponentUnionsClosed (Q : AbstractEscapeQuotient I)
    (primitive : I.Port → I.Port → Prop)
    (parent : Finset I.Port) : Prop :=
  ∀ S : Finset I.Port, S ⊆ parent →
    CouplingSaturatedIn I primitive parent S → ClosedPortSet Q S

/-- Saturation under the symmetrized primitive full-escape block relation. -/
def PrimitiveBlockSaturatedIn (primitive : I.Port → I.Port → Prop)
    (parent S : Finset I.Port) : Prop :=
  ∀ {p q}, p ∈ S → q ∈ parent →
    PrimitiveCoupled primitive p q → q ∈ S

/-- Exact localized representation hypothesis: among subsets of `parent`,
closed port sets are exactly the primitive-block-saturated sets. -/
def PrimitiveBlockClosureExactOn (Q : AbstractEscapeQuotient I)
    (primitive : I.Port → I.Port → Prop)
    (parent : Finset I.Port) : Prop :=
  ∀ S : Finset I.Port, S ⊆ parent →
    (ClosedPortSet Q S ↔ PrimitiveBlockSaturatedIn primitive parent S)

theorem couplingComponentUnionsClosed_of_primitiveBlockClosureExactOn
    (primitive : I.Port → I.Port → Prop) (parent : Finset I.Port)
    (hblocks : PrimitiveBlockClosureExactOn Q primitive parent) :
    CouplingComponentUnionsClosed Q primitive parent := by
  intro S hS hsaturated
  apply (hblocks S hS).2
  intro p q hp hq hprimitive
  apply hsaturated hp
  exact And.intro (hS hp) (And.intro hq (Or.inl hprimitive))

theorem left_right_disjoint (primitive : I.Port → I.Port → Prop)
    (parent seedR : Finset I.Port) :
    Disjoint (leftPorts I primitive parent seedR)
      (rightPorts I primitive parent seedR) := by
  classical
  unfold leftPorts
  exact Finset.sdiff_disjoint (t := parent)
    (s := rightPorts I primitive parent seedR)

theorem left_union_right (primitive : I.Port → I.Port → Prop)
    (parent seedR : Finset I.Port) :
    leftPorts I primitive parent seedR ∪
      rightPorts I primitive parent seedR = parent := by
  classical
  unfold leftPorts
  exact Finset.sdiff_union_of_subset
    (rightPorts_subset_parent primitive parent seedR)

theorem rightPorts_nonempty (primitive : I.Port → I.Port → Prop)
    {parent seedR : Finset I.Port} (hseedRne : seedR.Nonempty)
    (hseedR : seedR ⊆ parent) :
    (rightPorts I primitive parent seedR).Nonempty :=
  hseedRne.mono (seedR_subset_rightPorts primitive hseedR)

theorem leftPorts_nonempty (primitive : I.Port → I.Port → Prop)
    {parent seedL seedR : Finset I.Port} (hseedLne : seedL.Nonempty)
    (hseedL : seedL ⊆ parent)
    (hNMC : NoMixedCornerPortComponent I primitive parent seedL seedR) :
    (leftPorts I primitive parent seedR).Nonempty :=
  hseedLne.mono (seedL_subset_leftPorts primitive hseedL hNMC)

theorem leftPorts_ssubset_parent (primitive : I.Port → I.Port → Prop)
    {parent seedR : Finset I.Port} (hseedRne : seedR.Nonempty)
    (hseedR : seedR ⊆ parent) :
    leftPorts I primitive parent seedR ⊂ parent := by
  rw [Finset.ssubset_iff_subset_ne]
  refine And.intro (leftPorts_subset_parent primitive parent seedR) ?_
  intro heq
  rcases rightPorts_nonempty primitive hseedRne hseedR with ⟨q, hqright⟩
  have hqparent := rightPorts_subset_parent primitive parent seedR hqright
  have hqleft : q ∈ leftPorts I primitive parent seedR := by
    rw [heq]
    exact hqparent
  exact (mem_leftPorts primitive).1 hqleft |>.2 hqright

theorem rightPorts_ssubset_parent (primitive : I.Port → I.Port → Prop)
    {parent seedL seedR : Finset I.Port} (hseedLne : seedL.Nonempty)
    (hseedL : seedL ⊆ parent)
    (hNMC : NoMixedCornerPortComponent I primitive parent seedL seedR) :
    rightPorts I primitive parent seedR ⊂ parent := by
  rw [Finset.ssubset_iff_subset_ne]
  refine And.intro (rightPorts_subset_parent primitive parent seedR) ?_
  intro heq
  rcases leftPorts_nonempty primitive hseedLne hseedL hNMC with ⟨p, hpleft⟩
  have hpparent := leftPorts_subset_parent primitive parent seedR hpleft
  have hpright : p ∈ rightPorts I primitive parent seedR := by
    rw [heq]
    exact hpparent
  exact (mem_leftPorts primitive).1 hpleft |>.2 hpright

theorem rightPorts_closed (primitive : I.Port → I.Port → Prop)
    (parent seedR : Finset I.Port)
    (hclosed : CouplingComponentUnionsClosed Q primitive parent) :
    ClosedPortSet Q (rightPorts I primitive parent seedR) :=
  hclosed _ (rightPorts_subset_parent primitive parent seedR)
    (rightPorts_couplingSaturated primitive parent seedR)

theorem leftPorts_closed (primitive : I.Port → I.Port → Prop)
    (parent seedR : Finset I.Port)
    (hclosed : CouplingComponentUnionsClosed Q primitive parent) :
    ClosedPortSet Q (leftPorts I primitive parent seedR) :=
  hclosed _ (leftPorts_subset_parent primitive parent seedR)
    (leftPorts_couplingSaturated primitive parent seedR)

/-- Common legal-sink adjacency in `Coupled` forces the two component unions
to have disjoint legal sink neighborhoods. -/
theorem legalNbr_left_right_disjoint
    (primitive : I.Port → I.Port → Prop) (parent seedR : Finset I.Port) :
    Disjoint (legalNbr I (leftPorts I primitive parent seedR))
      (legalNbr I (rightPorts I primitive parent seedR)) := by
  classical
  rw [Finset.disjoint_left]
  intro s hsleft hsright
  rcases mem_legalNbr.1 hsleft with ⟨p, hpleft, hplegal⟩
  rcases mem_legalNbr.1 hsright with ⟨q, hqright, hqlegal⟩
  have hqp : Coupled I primitive parent q p :=
    And.intro (rightPorts_subset_parent primitive parent seedR hqright)
      (And.intro (leftPorts_subset_parent primitive parent seedR hpleft)
        (Or.inr (Exists.intro s (And.intro hqlegal hplegal))))
  have hpright := rightPorts_closed_under_coupled primitive hqright hqp
  exact (mem_leftPorts primitive).1 hpleft |>.2 hpright

/-- The exact abstract R11 construction with the direct component-union
closure hypothesis.  The resulting split is at the same load `L`. -/
noncomputable def properClosedBankSplitOfNoMixedCornerPortComponent
    (L : I.Port → ℚ) (primitive : I.Port → I.Port → Prop)
    (parent seedL seedR : Finset I.Port)
    (hseedLne : seedL.Nonempty) (hseedRne : seedR.Nonempty)
    (hseedL : seedL ⊆ parent) (hseedR : seedR ⊆ parent)
    (hNMC : NoMixedCornerPortComponent I primitive parent seedL seedR)
    (hclosed : CouplingComponentUnionsClosed Q primitive parent) :
    ProperClosedBankSplit Q L parent :=
  properClosedBankSplitOfDisjointNeighbors (I := I) (Q := Q) L
    (parent := parent) (left := leftPorts I primitive parent seedR)
    (right := rightPorts I primitive parent seedR)
    (left_right_disjoint primitive parent seedR)
    (left_union_right primitive parent seedR)
    (leftPorts_closed primitive parent seedR hclosed)
    (rightPorts_closed primitive parent seedR hclosed)
    (leftPorts_ssubset_parent primitive hseedRne hseedR)
    (rightPorts_ssubset_parent primitive hseedLne hseedL hNMC)
    (legalNbr_left_right_disjoint primitive parent seedR)

/-- Variant using the exact primitive-block saturation characterization. -/
noncomputable def properClosedBankSplitOfPrimitiveBlockSaturation
    (L : I.Port → ℚ) (primitive : I.Port → I.Port → Prop)
    (parent seedL seedR : Finset I.Port)
    (hseedLne : seedL.Nonempty) (hseedRne : seedR.Nonempty)
    (hseedL : seedL ⊆ parent) (hseedR : seedR ⊆ parent)
    (hNMC : NoMixedCornerPortComponent I primitive parent seedL seedR)
    (hblocks : PrimitiveBlockClosureExactOn Q primitive parent) :
    ProperClosedBankSplit Q L parent :=
  properClosedBankSplitOfNoMixedCornerPortComponent L primitive parent seedL seedR
    hseedLne hseedRne hseedL hseedR hNMC
    (couplingComponentUnionsClosed_of_primitiveBlockClosureExactOn
      primitive parent hblocks)

/-- **Open real-extractor provider contract.**  A downstream concrete adapter
must prove these fields from the real extractor.  This module supplies no value
of this structure and therefore claims neither NMC nor block saturation for the
real extractor. -/
structure RealExtractorNMCBlockSaturationProvider
    (Q : AbstractEscapeQuotient I)
    (primitive : I.Port → I.Port → Prop)
    (parent seedL seedR : Finset I.Port) : Prop where
  no_mixed : NoMixedCornerPortComponent I primitive parent seedL seedR
  block_saturation : PrimitiveBlockClosureExactOn Q primitive parent

/-- Conditional packaging through the open real-extractor provider contract. -/
noncomputable def properClosedBankSplitOfRealExtractorProvider
    (L : I.Port → ℚ) (primitive : I.Port → I.Port → Prop)
    (parent seedL seedR : Finset I.Port)
    (hseedLne : seedL.Nonempty) (hseedRne : seedR.Nonempty)
    (hseedL : seedL ⊆ parent) (hseedR : seedR ⊆ parent)
    (provider : RealExtractorNMCBlockSaturationProvider
      Q primitive parent seedL seedR) :
    ProperClosedBankSplit Q L parent :=
  properClosedBankSplitOfPrimitiveBlockSaturation L primitive parent seedL seedR
    hseedLne hseedRne hseedL hseedR provider.no_mixed provider.block_saturation

end ClosedShore
end Wall
end Erdos23Delta0
