import Erdos23Delta0.CollisionTokenAssignment

/-!
# Residual-source matching to collision tokens

This module implements the constructive half of the repaired collision route.
At Hall scale, one free ordered-pair source contributes one twenty-fifth unit
while one endpoint need slot costs one half-unit.  We therefore atomize at
micro-unit scale: each free source and each collision debit has two copies,
while each need slot has twenty-five copies.  All debit and need micro-copies
must inject disjointly into free micro-sources.

Existence of the residual-source matching is intentionally not asserted here.
-/

namespace Erdos23Delta0
namespace ResidualSourceTokenization

open scoped BigOperators
open CollisionTokenAssignment

variable {V Source Debit Slot Comp : Type*}
  [Fintype V] [DecidableEq V]
  [Fintype Source] [Fintype Debit]
  [Fintype Slot] [DecidableEq Slot]

/-- Exact finite matching data.  Collision debits and token need slots occupy
distinct positive residual sources, so cancelling a debit cannot also fund a
positive token. -/
structure Data where
  owner : Slot → V
  source :
    ((Debit × Fin 2) ⊕ (Slot × Fin 25)) ↪ (Source × Fin 2)
  vertexComp : V → Comp
  debitComp : Debit → Comp
  sourceComp : Source → Comp
  source_component :
    ∀ x, sourceComp (source x).1 =
      Sum.elim (fun d => debitComp d.1)
        (fun s => vertexComp (owner s.1)) x
  unit : ℚ
  unit_pos : 0 < unit

/-- The corrected scalar budget is exactly enough to construct a finite
no-reuse matching between collision debits plus token needs and free sources. -/
theorem matching_exists_of_card_budget
    (h : 2 * Fintype.card Debit + 25 * Fintype.card Slot ≤
      2 * Fintype.card Source) :
    Nonempty
      (((Debit × Fin 2) ⊕ (Slot × Fin 25)) ↪ (Source × Fin 2)) := by
  apply Function.Embedding.nonempty_of_card_le
  simpa [Nat.mul_comm, Nat.mul_left_comm, Nat.mul_assoc] using h

namespace Data

variable (D : Data (V := V) (Source := Source) (Debit := Debit)
  (Slot := Slot) (Comp := Comp))

/-- One token per matched need slot. -/
abbrev Token := Slot

/-- A token is legal at exactly the edges incident with its owner. -/
def legal (e : Sym2 V) (s : Slot) : Prop :=
  D.owner s ∈ e

/-- Each token owns twenty-five residual micro-units, i.e. one Hall half-unit
when the micro-unit is one over fifty times the row-choice denominator. -/
def cap (_s : Slot) : ℚ :=
  25 * D.unit

/-- Token mass is assigned only to the owner vertex. -/
def eta (x : V) (s : Slot) : ℚ :=
  if D.owner s = x then 25 * D.unit else 0

/-- Pointwise reserve generated by the matched slots at a vertex. -/
def need (x : V) : ℚ :=
  ∑ s : Slot, D.eta x s

theorem eta_nonneg (x : V) (s : Slot) :
    0 ≤ D.eta x s := by
  unfold eta
  split
  · exact mul_nonneg (by norm_num) (le_of_lt D.unit_pos)
  · exact le_rfl

theorem token_spend_eq_cap (s : Slot) :
    (∑ x : V, D.eta x s) = D.cap s := by
  classical
  simp [eta, cap]

theorem no_double_spend (s : Slot) :
    (∑ x : V, D.eta x s) ≤ D.cap s := by
  rw [D.token_spend_eq_cap]

theorem pays_need (x : V) :
    D.need x ≤ ∑ s : Slot, D.eta x s := by
  rfl

theorem legal_at_endpoint
    (x : V) (s : Slot) (hpos : 0 < D.eta x s)
    (e : Sym2 V) (_he : e ∈ Finset.univ) (hxe : x ∈ e) :
    D.legal e s := by
  have howner : D.owner s = x := by
    by_contra hne
    simp [eta, hne] at hpos
  simpa [legal, howner] using hxe

/-- The residual matching canonically supplies the generic collision-token
assignment consumed by the Hall adapter. -/
def assignment :
    Assignment (Finset.univ : Finset (Sym2 V)) D.legal D.cap D.need where
  eta := D.eta
  eta_nonneg := D.eta_nonneg
  no_double_spend := D.no_double_spend
  pays_need := D.pays_need
  legal_at_endpoint := D.legal_at_endpoint

theorem source_component_of_token (s : Slot) :
    ∀ i : Fin 25,
      D.sourceComp (D.source (Sum.inr (s, i))).1 =
        D.vertexComp (D.owner s) := by
  intro i
  simpa using D.source_component (Sum.inr (s, i))

theorem distinct_need_microcopies_have_distinct_sources
    {s t : Slot × Fin 25} (hst : s ≠ t) :
    D.source (Sum.inr s) ≠ D.source (Sum.inr t) := by
  exact fun h => hst (Sum.inr.inj (D.source.injective h))

/-- The corrected matching uses a distinct source for every collision debit
and every positive token need. -/
theorem debit_add_token_card_le_source
    (D : Data (V := V) (Source := Source) (Debit := Debit)
      (Slot := Slot) (Comp := Comp)) :
    2 * Fintype.card Debit + 25 * Fintype.card Slot ≤
      2 * Fintype.card Source := by
  have h :
      Fintype.card ((Debit × Fin 2) ⊕ (Slot × Fin 25)) ≤
        Fintype.card (Source × Fin 2) :=
    Fintype.card_le_of_injective D.source D.source.injective
  simpa [Nat.mul_comm, Nat.mul_left_comm, Nat.mul_assoc] using h

/-- Consequently the total token cap fits in the positive-source mass left
after all collision debits are cancelled. -/
theorem token_cap_le_residual_source_mass :
    (Fintype.card Slot : ℚ) * (25 * D.unit) ≤
      (2 * ((Fintype.card Source : ℚ) -
        (Fintype.card Debit : ℚ))) * D.unit := by
  have hNat := debit_add_token_card_le_source D
  have hQ :
      2 * (Fintype.card Debit : ℚ) +
          25 * (Fintype.card Slot : ℚ) ≤
        2 * (Fintype.card Source : ℚ) := by
    exact_mod_cast hNat
  calc
    (Fintype.card Slot : ℚ) * (25 * D.unit) =
        (25 * (Fintype.card Slot : ℚ)) * D.unit := by ring
    _ ≤ (2 * ((Fintype.card Source : ℚ) -
          (Fintype.card Debit : ℚ))) * D.unit := by
      apply mul_le_mul_of_nonneg_right
      · linarith
      · exact le_of_lt D.unit_pos

#print axioms token_spend_eq_cap
#print axioms assignment
#print axioms distinct_need_microcopies_have_distinct_sources
#print axioms debit_add_token_card_le_source
#print axioms token_cap_le_residual_source_mass
#print axioms matching_exists_of_card_budget

end Data
end ResidualSourceTokenization
end Erdos23Delta0
