#!/usr/bin/env python3
"""Exact audit for the W144 eta-minimal induced-subgraph route.

For each connected multicyclic graph G of girth at least five generated by
nauty geng, test whether some vertex v leaves G-v connected and cyclic with
eta(G-v) >= eta(G), where eta is the maximum distance to the full center set.
This one-step statement implies that no multicyclic graph in the audited
corpus is inclusion-minimal among induced connected cyclic subgraphs under a
nondecreasing eta threshold.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import networkx as nx

HERE = Path(__file__).resolve().parent
IND2 = HERE.parent / "attack_ind2_multicycle"
sys.path.insert(0, str(IND2))
from analyze_tight_deletions import center_depth, cycle_rank, girth, records  # noqa: E402


def audit(min_n: int, max_n: int) -> dict:
    corpus_hash = hashlib.sha256()
    witness_hash = hashlib.sha256()
    per_order: dict[str, dict] = {}
    total = 0
    tight_total = 0
    global_minimum: int | None = None
    failure: dict | None = None

    for n in range(min_n, max_n + 1):
        checked = 0
        tight = 0
        minimum: int | None = None
        for code, graph in records(n):
            g = girth(graph)
            if g is None or g < 5 or cycle_rank(graph) < 2:
                continue
            checked += 1
            total += 1
            corpus_hash.update(code + b"\n")
            eta, center = center_depth(graph)
            rows: list[dict] = []
            for v in sorted(graph):
                subgraph = graph.copy()
                subgraph.remove_node(v)
                if not nx.is_connected(subgraph) or cycle_rank(subgraph) < 1:
                    continue
                eta_h, center_h = center_depth(subgraph)
                girth_h = girth(subgraph)
                assert girth_h is not None and girth_h >= g
                rows.append(
                    {
                        "v": v,
                        "degree": graph.degree[v],
                        "girth": girth_h,
                        "eta": eta_h,
                        "delta_eta": eta_h - eta,
                        "center": sorted(center_h),
                    }
                )
            if not rows:
                raise AssertionError((code.decode(), "no admissible deletion"))
            best = max(row["delta_eta"] for row in rows)
            minimum = best if minimum is None else min(minimum, best)
            global_minimum = best if global_minimum is None else min(global_minimum, best)
            if best == 0:
                tight += 1
                tight_total += 1
            good = [row for row in rows if row["delta_eta"] >= 0]
            if not good:
                failure = {
                    "graph6": code.decode(),
                    "n": n,
                    "m": graph.number_of_edges(),
                    "rank": cycle_rank(graph),
                    "girth": g,
                    "eta": eta,
                    "center": sorted(center),
                    "edges": sorted([min(u, v), max(u, v)] for u, v in graph.edges()),
                    "deletions": rows,
                }
                break
            witness = good[0]
            witness_hash.update(
                (
                    f"{code.decode()}:{witness['v']}:{g}:{eta}:"
                    f"{witness['girth']}:{witness['eta']}\n"
                ).encode()
            )
        per_order[str(n)] = {
            "checked": checked,
            "minimum_best_delta_eta": minimum,
            "tight": tight,
        }
        if failure is not None:
            break

    return {
        "statement": "exists v: G-v connected cyclic and eta(G-v)>=eta(G)",
        "generator": "geng -ctfq",
        "min_n": min_n,
        "max_n": max_n,
        "per_order": per_order,
        "total_checked": total,
        "minimum_best_delta_eta": global_minimum,
        "tight_total": tight_total,
        "corpus_sha256": corpus_hash.hexdigest(),
        "canonical_first_witness_sha256": witness_hash.hexdigest(),
        "failure": failure,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--min-n", type=int, default=5)
    parser.add_argument("--max-n", type=int, default=13)
    parser.add_argument(
        "--output",
        type=Path,
        default=HERE / "eta_minimal_audit_results.json",
    )
    args = parser.parse_args()
    result = audit(args.min_n, args.max_n)
    args.output.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(result, indent=2))
    if result["failure"] is not None:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
