#!/usr/bin/env python3
"""
band10 wave-2: INDEPENDENT re-derivation of the weight-independent Reeve bound.

THE ARGUMENT (all steps but (1) are proved here; (1) is verified, not proved)

 (1) HYPOTHESIS  every vertex of an r=4 hive polytope Q is a lattice point.
     [verified over 1.65e9 exhaustive gap classes + 3.3e8 random classes with
      gaps up to 1e9; NOT proved -- 49 of the 517 non-singular row triples have
      |det| in {2,4}, so integrality is not an identity in the right-hand side.]

 (2) dim Q = 3 and c = #(Q cap Z^3) = 4.  A 3-dimensional lattice polytope has
     at least 4 vertices, and by (1) every vertex is one of the 4 lattice
     points, so Q is a 3-simplex whose only lattice points are its vertices:
     an EMPTY lattice 3-simplex.

 (3) In an empty lattice simplex every edge is primitive (an interior lattice
     point of an edge would be a 5th lattice point).  Hence the tangent cone at
     each vertex is generated by the three primitive edge vectors, and its
     lattice index equals |det| of those vectors = the normalized volume V.
     So ALL FOUR vertex cones have the SAME index, namely V.

 (4) Every facet normal of Q is one of the 15 fixed primitive rhombus
     directions (independent of lam, mu, nu -- only the right-hand side moves).
     A simplex is cut out by exactly 4 of them, and its four tangent cones are
     the four cones spanned by the four 3-subsets.

 (5) ENUMERATION (this file): over all 4-subsets of the 15 directions that
     positively span R^3 (the boundedness requirement), compute the four
     vertex-cone indices exactly.  If no 4-subset has all four indices equal to
     the same value q >= 2, then V >= 2 is impossible at c = 4 AT EVERY WEIGHT.

All arithmetic exact integer.  No floating point.
"""
import itertools
import json
import os
import sys
from fractions import Fraction

HERE = os.path.dirname(os.path.abspath(__file__))
R4 = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, R4)
import hive4  # noqa: E402


def gcd3(v):
    from math import gcd
    return gcd(gcd(abs(v[0]), abs(v[1])), abs(v[2]))


def prim(v):
    g = gcd3(v)
    return tuple(x // g for x in v) if g else tuple(v)


def cross(u, v):
    return (u[1] * v[2] - u[2] * v[1],
            u[2] * v[0] - u[0] * v[2],
            u[0] * v[1] - u[1] * v[0])


def dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def det3(a, b, c):
    return (a[0] * (b[1] * c[2] - b[2] * c[1])
            - a[1] * (b[0] * c[2] - b[2] * c[0])
            + a[2] * (b[0] * c[1] - b[1] * c[0]))


def cone_index(n1, n2, n3):
    """
    Lattice index of the simplicial cone {x : n_i . x <= 0}, i.e. |det| of its
    three PRIMITIVE extreme-ray generators.  Returns None if the normals are
    linearly dependent (not a simple vertex).
    """
    if det3(n1, n2, n3) == 0:
        return None
    N = [n1, n2, n3]
    rays = []
    for k in range(3):
        i, j = [t for t in range(3) if t != k]
        r = prim(cross(N[i], N[j]))
        if dot(N[k], r) > 0:
            r = tuple(-x for x in r)
        if dot(N[k], r) == 0:
            return None
        rays.append(r)
    return abs(det3(*rays))


def positively_spans(S):
    """
    The 4 normals positively span R^3  <=>  {x : n.x <= 0 for all n in S} = {0}
    <=>  every polytope they bound is bounded.  Exact test: the cone is
    non-trivial iff some extreme ray survives; every extreme ray of a pointed
    cone in R^3 lies on the kernel of two independent normals.
    """
    for i, j in itertools.combinations(range(4), 2):
        d = cross(S[i], S[j])
        if d == (0, 0, 0):
            continue
        for s in (1, -1):
            ray = tuple(s * x for x in d)
            if all(dot(n, ray) <= 0 for n in S):
                return False
    # also need the 4 normals to span R^3 linearly
    if all(det3(*[S[t] for t in tri]) == 0
           for tri in itertools.combinations(range(4), 3)):
        return False
    return True


def main():
    # the fixed 18 rhombus rows (independent of lam,mu,nu) -> 15 directions
    H = hive4.build_hive4([9, 7, 6, 0], [9, 2, 1, 0], [10, 9, 8, 7])
    assert H["ok"]
    dirs = sorted(set(tuple(r) for r in H["A"]))
    # confirm weight-independence of A on random triples
    import random
    rng = random.Random(101010)
    for _ in range(200):
        while True:
            lam = sorted([rng.randint(0, 40) for _ in range(4)], reverse=True)
            mu = sorted([rng.randint(0, 40) for _ in range(4)], reverse=True)
            s = sum(lam) + sum(mu)
            nu = sorted([rng.randint(0, 60) for _ in range(3)], reverse=True)
            last = s - sum(nu)
            if last < 0 or last > nu[-1]:
                continue
            nu = nu + [last]
            break
        H2 = hive4.build_hive4(lam, mu, nu)
        if not H2["ok"]:
            continue
        assert sorted(set(tuple(r) for r in H2["A"])) == dirs, (lam, mu, nu)

    out = {"n_rows": len(H["A"]), "n_distinct_directions": len(dirs),
           "directions": [list(d) for d in dirs],
           "all_primitive": all(gcd3(d) == 1 for d in dirs),
           "A_weight_independent_on_200_random_triples": True}

    # index of every 3-subset
    tri_idx = {}
    hist = {}
    for tri in itertools.combinations(range(len(dirs)), 3):
        m = cone_index(*[dirs[t] for t in tri])
        tri_idx[tri] = m
        hist[str(m)] = hist.get(str(m), 0) + 1
    out["cone_index_histogram_over_3subsets"] = hist

    # every 4-subset that positively spans
    good = []
    profiles = {}
    for quad in itertools.combinations(range(len(dirs)), 4):
        S = [dirs[t] for t in quad]
        if not positively_spans(S):
            continue
        idxs = []
        ok = True
        for k in range(4):
            tri = tuple(sorted(t for t in quad if t != quad[k]))
            m = tri_idx[tri]
            if m is None:
                ok = False
                break
            idxs.append(m)
        if not ok:
            continue          # a non-simple vertex: not a simplex
        prof = tuple(sorted(idxs))
        profiles[str(prof)] = profiles.get(str(prof), 0) + 1
        good.append({"quad": [list(dirs[t]) for t in quad], "indices": idxs,
                     "constant": len(set(idxs)) == 1, "V": idxs[0]})
    out["n_4subsets_positively_spanning_and_simple"] = len(good)
    out["index_profiles"] = profiles
    const = [q for q in good if q["constant"]]
    out["n_with_constant_index"] = len(const)
    out["constant_index_values"] = sorted(set(q["V"] for q in const))
    out["max_constant_index"] = max([q["V"] for q in const], default=None)

    out["verdict"] = (
        "Under hypothesis (1) (integral vertices), an r=4 hive polytope with "
        "dim 3 and c = 4 is an empty lattice 3-simplex, all four of whose "
        "vertex-cone indices equal its normalized volume V.  Over ALL "
        "positively-spanning simple 4-subsets of the 15 fixed rhombus "
        "directions, the only constant index profile is (1,1,1,1).  Hence "
        "V = 1, at EVERY weight: the Reeve mechanism (which needs V = q >= 13) "
        "cannot fire in the r = 4 cell.  This is a bound on the mechanism, NOT "
        "evidence for the King-Tollu-Toumazet conjecture.")

    with open(os.path.join(HERE, "b10w2_atlas.json"), "w") as f:
        json.dump(out, f, indent=1)
    for k in ("n_rows", "n_distinct_directions", "all_primitive",
              "cone_index_histogram_over_3subsets",
              "n_4subsets_positively_spanning_and_simple", "index_profiles",
              "n_with_constant_index", "constant_index_values",
              "max_constant_index"):
        print(k, "=", out[k])
    print()
    print(out["verdict"])


if __name__ == "__main__":
    main()
