#!/usr/bin/env python3
"""
kt4.py -- INDEPENDENT r=4 hive engine, written from first principles.

Everything exact (Python int / Fraction).  Nothing is imported from the prior
run's code.  The rhombus system is generated by enumerating adjacent pairs of
unit triangles of the side-4 triangulated triangle, so no convention is
inherited.

Provides:
  hive_rows(lam,mu,nu)  -> (A, b)  with Q = {h in R^3 : A h <= b}
  gap_rows(g)           -> (A, b)  directly from the 9-gap vector
  verts(A,b)            -> exact vertices + tight sets
  ehrhart_brion(A,b)    -> exact [a0,a1,a2,a3] via Brion at unimodular
                           simple vertices (scale-free, no lattice walking)
  count_lattice(A,b,n)  -> brute lattice count of n*Q  (validation only)
"""
import itertools, math, sys
from fractions import Fraction

R = 4
PTS = [(x, y) for x in range(R + 1) for y in range(R + 1) if x + y <= R]
INTERIOR = [(1, 1), (1, 2), (2, 1)]
IDX = {p: i for i, p in enumerate(INTERIOR)}

# ---------------------------------------------------------------- rhombi
def _triangles():
    up = [frozenset({(x, y), (x + 1, y), (x, y + 1)})
          for x in range(R) for y in range(R) if x + y <= R - 1]
    dn = [frozenset({(x + 1, y), (x, y + 1), (x + 1, y + 1)})
          for x in range(R) for y in range(R) if x + y <= R - 2]
    return up, dn

def rhombi():
    """All unit rhombi as (shared_pair, other_pair).  Concavity:
       sum(shared) >= sum(other)."""
    up, dn = _triangles()
    out = []
    for U in up:
        for D in dn:
            S = U & D
            if len(S) == 2:
                a = list(U - S)[0]
                b = list(D - S)[0]
                out.append((sorted(S), sorted([a, b])))
    return out

RH = rhombi()
assert len(RH) == 18, len(RH)

# ---------------------------------------------------------------- boundary
def _bnd(lam, mu, nu):
    ps = lambda p, k: sum(p[:k])
    B = {}
    for y in range(R + 1):
        B[(0, y)] = ps(lam, y)
    for x in range(R + 1):
        B[(x, R - x)] = sum(lam) + ps(mu, x)
    for x in range(R + 1):
        B[(x, 0)] = ps(nu, x)
    B[(0, 0)] = 0
    return B

def rows_from_boundary(B):
    """Q = {h : A h <= b} from a dict B of the boundary values."""
    A, b = [], []
    const_bad = False
    for shared, other in RH:
        co = [0, 0, 0]
        const = 0                      # inequality: sum(other) - sum(shared) <= 0
        for v in other:
            if v in IDX: co[IDX[v]] += 1
            else:        const += B[v]
        for v in shared:
            if v in IDX: co[IDX[v]] -= 1
            else:        const -= B[v]
        if co == [0, 0, 0]:
            if const > 0: const_bad = True
            continue
        A.append(tuple(co)); b.append(-const)
    return A, b, const_bad

def hive_rows(lam, mu, nu):
    lam = list(lam) + [0] * (R - len(lam))
    mu  = list(mu)  + [0] * (R - len(mu))
    nu  = list(nu)  + [0] * (R - len(nu))
    B = _bnd(lam, mu, nu)
    return rows_from_boundary(B)

def realizable(g):
    """gap vector realisable by genuine partitions iff 4 | (Aw + Bw - Cw)."""
    a1, a2, a3, b1, b2, b3, c1, c2, c3 = g
    return ((a1 + 2 * a2 + 3 * a3) + (b1 + 2 * b2 + 3 * b3)
            - (c1 + 2 * c2 + 3 * c3)) % 4 == 0

def realise(g):
    """lam,mu,nu with nonneg integer parts having exactly these gaps.
       Requires realizable(g).  lam4 = mu4 = 0, nu4 shifted up if needed."""
    a1, a2, a3, b1, b2, b3, c1, c2, c3 = g
    Aw = a1 + 2 * a2 + 3 * a3; Bw = b1 + 2 * b2 + 3 * b3
    Cw = c1 + 2 * c2 + 3 * c3
    D = Aw + Bw - Cw
    assert D % 4 == 0, "gap vector not realisable"
    n4 = D // 4
    t = 0
    if n4 < 0:
        t = -n4          # raise lam4 = mu4 = 0 -> l4 = t keeps 4|D and n4 += t
        n4 = 0
        # l4 = t adds 4t to Aw's weight, so nu4 = (D + 4t)/4 = 0
    lam = [t + a1 + a2 + a3, t + a2 + a3, t + a3, t]
    mu  = [b1 + b2 + b3, b2 + b3, b3, 0]
    nu  = [n4 + c1 + c2 + c3, n4 + c2 + c3, n4 + c3, n4]
    assert sum(lam) + sum(mu) == sum(nu), (lam, mu, nu)
    return lam, mu, nu

def fix_gap(g):
    """nudge c1 up by (Aw+Bw-Cw) mod 4 so that g becomes realisable"""
    g = list(g)
    a1, a2, a3, b1, b2, b3, c1, c2, c3 = g
    D = (a1 + 2 * a2 + 3 * a3 + b1 + 2 * b2 + 3 * b3
         - (c1 + 2 * c2 + 3 * c3)) % 4
    g[6] += D
    return tuple(g)

def gap_rows(g):
    """g = (a1,a2,a3, b1,b2,b3, c1,c2,c3) consecutive-part gaps of lam,mu,nu.
       g must be realisable (integrality of the translation matters for the
       LATTICE point count, not just for the shape of Q)."""
    lam, mu, nu = realise(g)
    B = _bnd(lam, mu, nu)
    A, b, bad = rows_from_boundary(B)
    return A, b, bad

# ---------------------------------------------------------------- reduce rows
def reduce_rows(A, b):
    """keep one row per distinct direction, with the tightest rhs"""
    best = {}
    for d, r in zip(A, b):
        if d not in best or r < best[d]:
            best[d] = r
    ds = sorted(best)
    return ds, [best[d] for d in ds]

# ---------------------------------------------------------------- linear alg
def det3(m):
    (a, b, c), (d, e, f), (g, h, i) = m
    return a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)

def cross(u, v):
    return (u[1] * v[2] - u[2] * v[1], u[2] * v[0] - u[0] * v[2],
            u[0] * v[1] - u[1] * v[0])

def dot(a, x):
    return a[0] * x[0] + a[1] * x[1] + a[2] * x[2]

def adj3(M):
    def minor(r, c):
        rs = [x for x in range(3) if x != r]; cs = [x for x in range(3) if x != c]
        return (M[rs[0]][cs[0]] * M[rs[1]][cs[1]] - M[rs[0]][cs[1]] * M[rs[1]][cs[0]])
    return [[(-1) ** (r + c) * minor(c, r) for c in range(3)] for r in range(3)]

_CR = {}
def cramer_table(ds):
    key = tuple(ds)
    if key in _CR: return _CR[key]
    out = []
    for i, j, k in itertools.combinations(range(len(ds)), 3):
        M = [list(ds[i]), list(ds[j]), list(ds[k])]
        D = det3(M)
        if D == 0: continue
        Ad = adj3(M)
        if D < 0:
            D = -D; Ad = [[-x for x in row] for row in Ad]
        out.append((i, j, k, D, Ad))
    _CR[key] = out
    return out

# ---------------------------------------------------------------- vertices
def verts(ds, bs):
    """returns dict  vertex(tuple of Fraction) -> frozenset(tight row idx)"""
    tab = cramer_table(ds)
    seen = {}
    for i, j, k, D, Ad in tab:
        b3 = (bs[i], bs[j], bs[k])
        num = [Ad[t][0] * b3[0] + Ad[t][1] * b3[1] + Ad[t][2] * b3[2] for t in range(3)]
        ok = True
        tight = []
        for t, (d, r) in enumerate(zip(ds, bs)):
            s = d[0] * num[0] + d[1] * num[1] + d[2] * num[2]
            rr = r * D
            if s > rr:
                ok = False; break
            if s == rr:
                tight.append(t)
        if not ok: continue
        v = (Fraction(num[0], D), Fraction(num[1], D), Fraction(num[2], D))
        seen[v] = frozenset(tight)
    return seen

# ---------------------------------------------------------------- volume
def affine_rank(pts):
    if not pts: return -1
    p0 = pts[0]
    rows = [[p[t] - p0[t] for t in range(3)] for p in pts[1:]]
    # gaussian elimination over Q
    r = 0
    M = [list(map(Fraction, row)) for row in rows]
    for c in range(3):
        piv = None
        for i in range(r, len(M)):
            if M[i][c] != 0: piv = i; break
        if piv is None: continue
        M[r], M[piv] = M[piv], M[r]
        pv = M[r][c]
        for i in range(len(M)):
            if i != r and M[i][c] != 0:
                f = M[i][c] / pv
                M[i] = [M[i][t] - f * M[r][t] for t in range(3)]
        r += 1
        if r == len(M): break
    return r

# ---------------------------------------------------------------- Brion
def cone_rays(ds, T):
    """extreme rays (primitive) of C = {x : ds[i].x <= 0 for i in T}"""
    rays = set()
    Tl = sorted(T)
    for i, j in itertools.combinations(Tl, 2):
        u = cross(ds[i], ds[j])
        if u == (0, 0, 0):
            continue
        for s in (1, -1):
            w = tuple(s * t for t in u)
            if all(dot(ds[k], w) <= 0 for k in Tl):
                gg = math.gcd(math.gcd(abs(w[0]), abs(w[1])), abs(w[2]))
                rays.add(tuple(t // gg for t in w))
    return sorted(rays)

def _cyclic_order(rays):
    """cyclic order of the rays of a pointed 3-d cone (exact)"""
    import functools
    z = [sum(r[t] for r in rays) for t in range(3)]
    p = (1, 0, 0)
    e1 = cross(tuple(z), p)
    if e1 == (0, 0, 0):
        e1 = cross(tuple(z), (0, 1, 0))
    e2 = cross(tuple(z), e1)
    co = [(dot(e1, r), dot(e2, r)) for r in rays]
    def half(q): return 0 if (q[1] > 0 or (q[1] == 0 and q[0] > 0)) else 1
    def cf(i, j):
        if half(co[i]) != half(co[j]): return -1 if half(co[i]) < half(co[j]) else 1
        cr = co[i][0] * co[j][1] - co[i][1] * co[j][0]
        return -1 if cr > 0 else (1 if cr < 0 else 0)
    return sorted(range(len(rays)), key=functools.cmp_to_key(cf))

def tangent_pieces(ds, T):
    """
    Half-open simplicial decomposition of the tangent cone
    C = {x : ds[i].x <= 0, i in T}, as a fan triangulation from one ray with
    the shared facet removed from every piece after the first, so the pieces
    PARTITION C exactly.
    Returns list of (u1, u2, u3, open_idx) where open_idx is None (closed) or
    the index (0/1/2) of the generator whose coefficient must be > 0.
    The starting ray is chosen to minimise the largest piece index.
    """
    rays = cone_rays(ds, T)
    if len(rays) < 3:
        return None
    if len(rays) == 3:
        if det3([list(r) for r in rays]) == 0:
            return None
        return [(rays[0], rays[1], rays[2], None)]
    order = _cyclic_order(rays)
    rc = [rays[i] for i in order]
    m = len(rc)
    best = None
    for start in range(m):
        r = rc[start:] + rc[:start]
        pieces = []
        mx = 1
        okc = True
        for j in range(1, m - 1):
            u = (r[0], r[j], r[j + 1])
            dd = abs(det3([list(t) for t in u]))
            if dd == 0:
                okc = False; break
            mx = max(mx, dd)
            pieces.append((u[0], u[1], u[2], None if j == 1 else 2))
        if not okc:
            continue
        if mx == 1:
            return pieces
        if best is None or mx < best[1]:
            best = (pieces, mx)
    return None if best is None else best[0]

_PARA = {}
def parallelepiped(u1, u2, u3):
    """lattice points of the half-open fundamental parallelepiped of the
       simplicial cone cone(u1,u2,u3): list of (point, (a1,a2,a3)) with
       a_i in [0,1) rational.  Exact.  Returns None if the index is > 64."""
    key = (u1, u2, u3)
    got = _PARA.get(key)
    if got is not None:
        return got
    m = abs(det3([list(u1), list(u2), list(u3)]))
    if m == 0 or m > 64:
        return None
    out = []
    for i in range(m):
        for j in range(m):
            for k in range(m):
                px = i * u1[0] + j * u2[0] + k * u3[0]
                py = i * u1[1] + j * u2[1] + k * u3[1]
                pz = i * u1[2] + j * u2[2] + k * u3[2]
                if px % m or py % m or pz % m:
                    continue
                out.append(((px // m, py // m, pz // m),
                            (Fraction(i, m), Fraction(j, m), Fraction(k, m))))
    assert len(out) == m, (u1, u2, u3, m, len(out))
    _PARA[key] = out
    return out

def ehrhart_brion(ds, bs, xi=(1, 71, 5041)):
    """
    EXACT Ehrhart polynomial [a0,a1,a2,a3] of Q = {ds.h <= bs} in R^3 by
    Brion's theorem.  Every tangent cone is cut into HALF-OPEN simplicial
    cones that partition it; each simplicial cone of index m contributes the
    m lattice points of its half-open fundamental parallelepiped.  No
    unimodularity is assumed anywhere.
    Cost is O(#vertices), INDEPENDENT of the size of Q.
    """
    V = verts(ds, bs)
    if not V:
        return {"status": "empty"}
    pts = [list(v) for v in V]
    d = affine_rank(pts)
    if d < 3:
        return {"status": "lowdim", "dim": d, "nv": len(V)}
    terms = []          # (apex_shifted, (u1,u2,u3))
    nonsimple = 0
    maxidx = 1
    for v, T in V.items():
        if any(c.denominator != 1 for c in v):
            return {"status": "nonintegral_vertex", "v": tuple(map(str, v)),
                    "T": sorted(T), "nv": len(V)}
        vi = tuple(int(c) for c in v)
        pcs = tangent_pieces(ds, T)
        if pcs is None:
            return {"status": "cone_failure", "v": vi, "T": sorted(T)}
        if len(pcs) > 1:
            nonsimple += 1
        for u1, u2, u3, op in pcs:
            us = (u1, u2, u3)
            m = abs(det3([list(u1), list(u2), list(u3)]))
            maxidx = max(maxidx, m)
            par = parallelepiped(u1, u2, u3)
            if par is None:
                return {"status": "index_too_large", "v": vi, "m": m}
            for pp, aa in par:
                sh = list(pp)
                if op is not None and aa[op] == 0:
                    for t in range(3):
                        sh[t] += us[op][t]
                terms.append((vi, tuple(sh), us))
    A0 = A1 = A2 = A3 = Fraction(0)
    for v, sh, us in terms:
        Av = dot(xi, v)                  # apex of nQ is n*v + sh
        s0 = dot(xi, sh)
        w = [dot(xi, u) for u in us]
        if any(x == 0 for x in w):
            return {"status": "xi_not_generic"}
        W = w[0] * w[1] * w[2]
        S1 = w[0] + w[1] + w[2]
        S2 = w[0] * w[1] + w[0] * w[2] + w[1] * w[2]
        SQ = w[0] ** 2 + w[1] ** 2 + w[2] ** 2
        g1 = Fraction(-S1, 2)
        g2 = Fraction(SQ, 12) + Fraction(S2, 4)
        ss = 0
        for jj in range(3):
            for kk in range(3):
                if jj != kk:
                    ss += w[jj] ** 2 * w[kk]
        g3 = Fraction(-ss, 24) - Fraction(W, 8)
        c = Fraction(-1, W)
        # [t^3] of exp(t*(n*Av + s0)) * prod_j f(t*w_j),  f = x/(e^x-1)
        A3 += c * Fraction(Av ** 3, 6)
        A2 += c * (Fraction(Av ** 2 * s0, 2) + Fraction(Av ** 2, 2) * g1)
        A1 += c * (Fraction(Av * s0 ** 2, 2) + Av * s0 * g1 + Av * g2)
        A0 += c * (Fraction(s0 ** 3, 6) + Fraction(s0 ** 2, 2) * g1
                   + s0 * g2 + g3)
    return {"status": "ok", "poly": [A0, A1, A2, A3], "nv": len(V),
            "nonsimple": nonsimple, "maxidx": maxidx}

# ---------------------------------------------------------------- volume by triangulation
def normalized_volume(ds, bs):
    V = verts(ds, bs)
    pts = [list(v) for v in V]
    if len(pts) < 4 or affine_rank(pts) < 3:
        return Fraction(0)
    c = [sum(p[t] for p in pts) / Fraction(len(pts)) for t in range(3)]
    tot = Fraction(0)
    # facets
    keys = {}
    for t, (d, r) in enumerate(zip(ds, bs)):
        S = [i for i, p in enumerate(pts) if dot(d, p) == r]
        if len(S) < 3: continue
        if affine_rank([pts[i] for i in S]) != 2: continue
        keys.setdefault(frozenset(S), (d, S))
    for d, S in keys.values():
        P = [pts[i] for i in S]
        fc = [sum(p[t] for p in P) / Fraction(len(P)) for t in range(3)]
        e1 = None
        for p in P:
            dd = [p[t] - fc[t] for t in range(3)]
            if any(x != 0 for x in dd): e1 = dd; break
        e2 = cross(tuple(map(Fraction, d)), tuple(e1))
        co = []
        for p in P:
            dd = [p[t] - fc[t] for t in range(3)]
            co.append((dot(e1, dd), dot(e2, dd)))
        import functools
        def half(p): return 0 if (p[1] > 0 or (p[1] == 0 and p[0] > 0)) else 1
        def cmpf(x, y):
            i1, i2 = x, y
            if half(co[i1]) != half(co[i2]): return -1 if half(co[i1]) < half(co[i2]) else 1
            cr = co[i1][0] * co[i2][1] - co[i1][1] * co[i2][0]
            return -1 if cr > 0 else (1 if cr < 0 else 0)
        order = sorted(range(len(P)), key=functools.cmp_to_key(cmpf))
        for t in range(1, len(order) - 1):
            p, q, rr = P[order[0]], P[order[t]], P[order[t + 1]]
            tot += abs(det3([[p[z] - c[z] for z in range(3)],
                             [q[z] - c[z] for z in range(3)],
                             [rr[z] - c[z] for z in range(3)]]))
    return tot

# ---------------------------------------------------------------- brute count
def count_lattice(ds, bs, n):
    if n == 0: return 1
    bb = [x * n for x in bs]
    V = verts(ds, bs)
    if not V: return 0
    lo = [min(v[t] for v in V) * n for t in range(3)]
    hi = [max(v[t] for v in V) * n for t in range(3)]
    R0 = [(a, r) for a, r in zip(ds, bb) if a[1] == 0 and a[2] == 0]
    R1 = [(a, r) for a, r in zip(ds, bb) if a[1] != 0 and a[2] == 0]
    R2 = [(a, r) for a, r in zip(ds, bb) if a[2] != 0]
    tot = 0
    for h0 in range(math.ceil(lo[0]), math.floor(hi[0]) + 1):
        ok = True
        for a, r in R0:
            if a[0] * h0 > r: ok = False; break
        if not ok: continue
        l1, u1 = math.ceil(lo[1]), math.floor(hi[1])
        for a, r in R1:
            rem = r - a[0] * h0
            if a[1] > 0: u1 = min(u1, rem // a[1])
            else: l1 = max(l1, -(rem // (-a[1])))
        for h1 in range(l1, u1 + 1):
            l2, u2 = math.ceil(lo[2]), math.floor(hi[2])
            for a, r in R2:
                rem = r - a[0] * h0 - a[1] * h1
                if a[2] > 0: u2 = min(u2, rem // a[2])
                else: l2 = max(l2, -(rem // (-a[2])))
                if l2 > u2: break
            if u2 >= l2: tot += u2 - l2 + 1
    return tot

def lr_coeff(lam, mu, nu):
    A, b, bad = hive_rows(lam, mu, nu)
    if bad: return 0
    ds, bs = reduce_rows(A, b)
    return count_lattice(ds, bs, 1)

if __name__ == "__main__":
    print("rhombi:", len(RH))
    A, b, bad = hive_rows([2, 1], [2, 1], [3, 2, 1])
    ds, bs = reduce_rows(A, b)
    print("distinct dirs:", len(ds), ds)
    print("c(321;21,21) =", count_lattice(ds, bs, 1))
