#!/usr/bin/env python3
"""Emit sharded Lean modules for one O14 chunked-cone export."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Iterable


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def lean_rat(q: dict[str, int]) -> str:
    n = int(q["num"])
    d = int(q["den"])
    if d == 1:
        return f"({n} : ℚ)"
    return f"(({n} : ℚ) / ({d} : ℚ))"


def lean_pows(pows: list[list[int]]) -> str:
    if not pows:
        return "[]"
    return "[" + ", ".join(f"({int(v)}, {int(e)})" for v, e in pows) + "]"


def chunks(xs: list[Any], n: int) -> Iterable[tuple[int, list[Any]]]:
    for i in range(0, len(xs), n):
        yield i // n, xs[i:i + n]


def emit_nf_def(lines: list[str], name: str, terms: list[dict[str, Any]]) -> None:
    lines.append(f"def {name} : NF := [")
    for idx, term in enumerate(terms):
        comma = "," if idx + 1 < len(terms) else ""
        lines.append(f"  {{ coeff := {lean_rat(term['coeff'])}, pows := {lean_pows(term['pows'])} }}{comma}")
    lines.append("]")
    lines.append("")


def emit_list_def(lines: list[str], name: str, type_name: str, defs: list[str]) -> None:
    lines.append(f"def {name} : List {type_name} := [")
    for idx, d in enumerate(defs):
        comma = "," if idx + 1 < len(defs) else ""
        lines.append(f"  {d}{comma}")
    lines.append("]")
    lines.append("")


def write_module(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def module_header(module_ns: str, imports: list[str]) -> list[str]:
    lines: list[str] = []
    lines.append("/- Generated by _codex_o14_chunked_cone_to_lean_sharded.py; do not edit by hand. -/")
    for imp in imports:
        lines.append(f"import {imp}")
    lines.append("")
    lines.append("namespace Erdos23Delta0")
    lines.append("namespace O14")
    lines.append("namespace Generated")
    lines.append("namespace ChartPayloads")
    lines.append("namespace Chart000Cone")
    lines.append(f"namespace {module_ns}")
    lines.append("")
    lines.append("open PolyCert")
    lines.append("open ConeEvalBridge")
    lines.append("open ChunkedCone")
    lines.append("")
    lines.append("set_option maxHeartbeats 0")
    lines.append("set_option maxRecDepth 2000000")
    lines.append("")
    return lines


def module_footer(module_ns: str) -> list[str]:
    return [
        f"end {module_ns}",
        "end Chart000Cone",
        "end ChartPayloads",
        "end Generated",
        "end O14",
        "end Erdos23Delta0",
        "",
    ]


def emit_support(out_dir: Path) -> Path:
    lines = module_header("Support", ["Erdos23Delta0.O14.ChunkedConeWitness"])
    lines += [
        "theorem list_all_append_true {α : Type} (p : α → Bool) :",
        "    ∀ xs ys : List α, (xs.all p = true) → (ys.all p = true) → ((xs ++ ys).all p = true)",
        "  | [], ys, _, hy => by simpa using hy",
        "  | x :: xs, ys, hx, hy => by",
        "      simp only [List.all_cons, Bool.and_eq_true] at hx",
        "      change (p x && (xs ++ ys).all p) = true",
        "      rw [hx.1, list_all_append_true p xs ys hx.2 hy]",
        "      rfl",
        "",
        "theorem nf_allCoeffNonneg_append_true (f g : NF)",
        "    (hf : NF.allCoeffNonneg f = true) (hg : NF.allCoeffNonneg g = true) :",
        "    NF.allCoeffNonneg (f ++ g) = true := by",
        "  unfold NF.allCoeffNonneg at hf hg ⊢",
        "  exact list_all_append_true _ f g hf hg",
        "",
        "theorem nf_allCoeffNonneg_flatten_true :",
        "    ∀ chunks : List NF, chunks.all NF.allCoeffNonneg = true → NF.allCoeffNonneg chunks.flatten = true",
        "  | [], _ => by rfl",
        "  | c :: cs, h => by",
        "      simp only [List.all_cons, Bool.and_eq_true] at h",
        "      simp only [List.flatten_cons]",
        "      exact nf_allCoeffNonneg_append_true c cs.flatten h.1 (nf_allCoeffNonneg_flatten_true cs h.2)",
        "",
        "theorem all_nf_allCoeffNonneg_flatten_true :",
        "    ∀ chunks : List (List NF),",
        "      chunks.all (fun xs => xs.all NF.allCoeffNonneg) = true →",
        "      chunks.flatten.all NF.allCoeffNonneg = true",
        "  | [], _ => by rfl",
        "  | c :: cs, h => by",
        "      simp only [List.all_cons, Bool.and_eq_true] at h",
        "      simp only [List.flatten_cons]",
        "      exact list_all_append_true NF.allCoeffNonneg c cs.flatten h.1",
        "        (all_nf_allCoeffNonneg_flatten_true cs h.2)",
        "",
        "theorem checkEqPairs_append_true : ∀ xs ys : List (NF × NF),",
        "    checkEqPairs xs = true → checkEqPairs ys = true → checkEqPairs (xs ++ ys) = true",
        "  | [], ys, _, hy => by simpa [checkEqPairs] using hy",
        "  | p :: xs, ys, hx, hy => by",
        "      simp only [checkEqPairs, Bool.and_eq_true] at hx",
        "      change (checkEq p.1 p.2 && checkEqPairs (xs ++ ys)) = true",
        "      rw [hx.1, checkEqPairs_append_true xs ys hx.2 hy]",
        "      rfl",
        "",
        "theorem checkEqPairs_flatten_true :",
        "    ∀ chunks : List (List (NF × NF)), chunks.all checkEqPairs = true → checkEqPairs chunks.flatten = true",
        "  | [], _ => by rfl",
        "  | c :: cs, h => by",
        "      simp only [List.all_cons, Bool.and_eq_true] at h",
        "      simp only [List.flatten_cons]",
        "      exact checkEqPairs_append_true c cs.flatten h.1 (checkEqPairs_flatten_true cs h.2)",
        "",
        "#print axioms nf_allCoeffNonneg_flatten_true",
        "#print axioms all_nf_allCoeffNonneg_flatten_true",
        "#print axioms checkEqPairs_flatten_true",
        "",
    ]
    lines += module_footer("Support")
    path = out_dir / "Chart000ConeSupport.lean"
    write_module(path, lines)
    return path


def emit_base(out_dir: Path, data: dict[str, Any], term_chunk: int) -> Path:
    lines = module_header("Base", ["Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeSupport"])
    chunk_names: list[str] = []
    for idx, part in chunks(data["base"], term_chunk):
        name = f"chunk{idx:03d}"
        emit_nf_def(lines, name, part)
        lines.append(f"theorem h{name} : NF.allCoeffNonneg {name} = true := by")
        lines.append(f"  norm_num [NF.allCoeffNonneg, {name}]")
        lines.append("")
        chunk_names.append(name)
    emit_list_def(lines, "chunks", "NF", chunk_names)
    lines.append("theorem hchunks : chunks.all NF.allCoeffNonneg = true := by")
    simps = ", ".join(f"h{name}" for name in chunk_names)
    lines.append(f"  simp [chunks, {simps}]")
    lines.append("")
    lines.append("def base : NF := chunks.flatten")
    lines.append("")
    lines.append("theorem hbase : NF.allCoeffNonneg base = true := by")
    lines.append("  exact Support.nf_allCoeffNonneg_flatten_true chunks hchunks")
    lines.append("")
    lines.append("#print axioms hbase")
    lines.append("")
    lines += module_footer("Base")
    path = out_dir / "Chart000ConeBase.lean"
    write_module(path, lines)
    return path


def emit_ms_shards(out_dir: Path, data: dict[str, Any], src_chunk: int) -> list[Path]:
    paths: list[Path] = []
    records = list(zip(data["mults"], data["slacks"]))
    for shard_idx, part in chunks(records, src_chunk):
        ns = f"MS{shard_idx:03d}"
        lines = module_header(ns, ["Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeSupport"])
        mult_names: list[str] = []
        slack_names: list[str] = []
        start = shard_idx * src_chunk
        for local_idx, (mrec, srec) in enumerate(part):
            global_idx = start + local_idx
            mname = f"mult{global_idx:04d}"
            sname = f"slack{global_idx:04d}"
            emit_nf_def(lines, mname, mrec["nf"])
            emit_nf_def(lines, sname, srec["nf"])
            mult_names.append(mname)
            slack_names.append(sname)
        for mname in mult_names:
            lines.append(f"theorem h{mname} : NF.allCoeffNonneg {mname} = true := by")
            lines.append(f"  norm_num [NF.allCoeffNonneg, {mname}]")
            lines.append("")
        emit_list_def(lines, "mults", "NF", mult_names)
        emit_list_def(lines, "slacks", "NF", slack_names)
        lines.append("theorem hmults : mults.all NF.allCoeffNonneg = true := by")
        hnames = ", ".join(f"h{name}" for name in mult_names)
        lines.append(f"  simp [mults, {hnames}]")
        lines.append("")
        lines.append("#print axioms hmults")
        lines.append("")
        lines += module_footer(ns)
        path = out_dir / f"Chart000ConeMS{shard_idx:03d}.lean"
        write_module(path, lines)
        paths.append(path)
    return paths


def emit_pair_shards(out_dir: Path, data: dict[str, Any], pair_chunk: int) -> list[Path]:
    paths: list[Path] = []
    for shard_idx, part in chunks(data["combo_order_chunks"], pair_chunk):
        ns = f"Pairs{shard_idx:03d}"
        lines = module_header(ns, ["Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeSupport"])
        pair_names: list[str] = []
        pair_def_names: list[str] = []
        start = shard_idx * pair_chunk
        for local_idx, pair in enumerate(part):
            global_idx = start + local_idx
            lname = f"pair{global_idx:03d}Left"
            rname = f"pair{global_idx:03d}Right"
            pname = f"pair{global_idx:03d}"
            emit_nf_def(lines, lname, pair["left"])
            emit_nf_def(lines, rname, pair["right"])
            lines.append(f"def {pname} : NF × NF := ({lname}, {rname})")
            lines.append("")
            pair_names.append(pname)
            pair_def_names.extend([lname, rname, pname])
        emit_list_def(lines, "pairs", "(NF × NF)", pair_names)
        lines.append("theorem hchunks : checkEqPairs pairs = true := by")
        unfold_defs = ", ".join(["checkEqPairs", "checkEq", "isZeroNF", "collect", "insertAdd", "NF.sub", "NF.neg", "pairs"] + pair_def_names)
        lines.append(f"  norm_num [{unfold_defs}]")
        lines.append("")
        lines.append("#print axioms hchunks")
        lines.append("")
        lines += module_footer(ns)
        path = out_dir / f"Chart000ConePairs{shard_idx:03d}.lean"
        write_module(path, lines)
        paths.append(path)
    return paths


def emit_aggregator(out_dir: Path, data: dict[str, Any], ms_count: int, pair_count: int) -> Path:
    imports = [
        "Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeBase",
    ]
    imports += [f"Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConeMS{i:03d}" for i in range(ms_count)]
    imports += [f"Erdos23Delta0.O14.Generated.ChartPayloads.Chart000ConePairs{i:03d}" for i in range(pair_count)]
    lines = module_header("Main", imports)
    lines += [
        f"def slot : Nat := {int(data['slot'])}",
        f"def sourceChart : Nat := {int(data['chart'])}",
        f"def dominant : Nat := {int(data['dominant'])}",
        f"def sourceColumns : Nat := {int(data['nonzero_solution_columns'])}",
        f"def rawComboTerms : Nat := {int(data['raw_combo_terms'])}",
        f"def comboOrderChunks : Nat := {int(data['checks']['combo_order_chunk_count'])}",
        "",
        "def base : NF := Base.base",
        "theorem hbase : NF.allCoeffNonneg base = true := by exact Base.hbase",
        "",
    ]
    ms_names = [f"MS{i:03d}" for i in range(ms_count)]
    pair_names = [f"Pairs{i:03d}" for i in range(pair_count)]
    emit_list_def(lines, "multShards", "(List NF)", [f"{n}.mults" for n in ms_names])
    emit_list_def(lines, "slackShards", "(List NF)", [f"{n}.slacks" for n in ms_names])
    lines.append("def mults : List NF := multShards.flatten")
    lines.append("def slacks : List NF := slackShards.flatten")
    lines.append("")
    lines.append("theorem hmultShards : multShards.all (fun xs => xs.all NF.allCoeffNonneg) = true := by")
    lines.append("  simp [multShards, " + ", ".join(f"{n}.hmults" for n in ms_names) + "]")
    lines.append("")
    lines.append("theorem hmults : mults.all NF.allCoeffNonneg = true := by")
    lines.append("  exact Support.all_nf_allCoeffNonneg_flatten_true multShards hmultShards")
    lines.append("")
    emit_list_def(lines, "pairShards", "(List (NF × NF))", [f"{n}.pairs" for n in pair_names])
    lines.append("def pairs : List (NF × NF) := pairShards.flatten")
    lines.append("")
    lines.append("theorem hpairShards : pairShards.all checkEqPairs = true := by")
    lines.append("  simp [pairShards, " + ", ".join(f"{n}.hchunks" for n in pair_names) + "]")
    lines.append("")
    lines.append("theorem hchunks : checkEqPairs pairs = true := by")
    lines.append("  exact Support.checkEqPairs_flatten_true pairShards hpairShards")
    lines.append("")
    lines.append("def chart000Witness")
    lines.append("    {G : CertGraph.GraphData} {c : CertGraph.CutData}")
    lines.append("    {rows : CertGraph.RowDB} {Q : CertGraph.RowCert}")
    lines.append("    (core : ODLCoreData G c rows Q) (env : Var → ℚ)")
    lines.append("    (hvars : ∀ v, 0 ≤ env v)")
    lines.append("    (hslacks : ∀ s ∈ slacks, 0 ≤ NF.eval env s)")
    lines.append("    (hcombo :")
    lines.append("      NF.eval env ((pairs.map Prod.snd).flatten) =")
    lines.append("        NF.eval env (comboNF base mults slacks))")
    lines.append("    (htarget : NF.eval env ((pairs.map Prod.fst).flatten) = coreDefect core) :")
    lines.append("    Witness core where")
    lines.append("  pairs := pairs")
    lines.append("  base := base")
    lines.append("  mults := mults")
    lines.append("  slacks := slacks")
    lines.append("  env := env")
    lines.append("  hvars := hvars")
    lines.append("  hbase := hbase")
    lines.append("  hmults := hmults")
    lines.append("  hslacks := hslacks")
    lines.append("  hchunks := hchunks")
    lines.append("  hcombo := hcombo")
    lines.append("  htarget := htarget")
    lines.append("")
    lines.append("#print axioms hchunks")
    lines.append("#print axioms hmults")
    lines.append("#print axioms chart000Witness")
    lines.append("")
    lines += module_footer("Main")
    path = out_dir / "Chart000Cone.lean"
    write_module(path, lines)
    return path


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--export", type=Path, default=Path("tmp/codex_o14_chart000_chunked_cone_export_v2.json"))
    ap.add_argument("--out-dir", type=Path, default=Path("problems/23/lean/Erdos23Delta0/O14/Generated/ChartPayloads"))
    ap.add_argument("--base-term-chunk", type=int, default=64)
    ap.add_argument("--source-chunk", type=int, default=32)
    ap.add_argument("--pair-chunk", type=int, default=16)
    args = ap.parse_args()
    data = read_json(args.export)
    if data.get("checks", {}).get("ordinary_identity") is not True:
        raise ValueError("export did not certify ordinary identity")
    if not data.get("combo_order_chunks"):
        raise ValueError("export lacks combo_order_chunks")
    out_dir = args.out_dir
    support = emit_support(out_dir)
    base = emit_base(out_dir, data, args.base_term_chunk)
    ms_paths = emit_ms_shards(out_dir, data, args.source_chunk)
    pair_paths = emit_pair_shards(out_dir, data, args.pair_chunk)
    agg = emit_aggregator(out_dir, data, len(ms_paths), len(pair_paths))
    summary = {
        "schema": "codex_o14_chunked_cone_sharded_lean_emit_v1",
        "input": str(args.export),
        "out_dir": str(out_dir),
        "support": str(support),
        "base": str(base),
        "aggregator": str(agg),
        "ms_shards": len(ms_paths),
        "pair_shards": len(pair_paths),
        "base_term_chunk": args.base_term_chunk,
        "source_chunk": args.source_chunk,
        "pair_chunk": args.pair_chunk,
        "mults": len(data["mults"]),
        "pairs": len(data["combo_order_chunks"]),
        "raw_combo_terms": data["raw_combo_terms"],
    }
    print(json.dumps(summary, sort_keys=True))


if __name__ == "__main__":
    main()
