#!/usr/bin/env python3
"""Emit tau_0 MCERT polynomials as Lean RawPoly literal lists."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

VAR_NAMES = [*(f"w{i}" for i in range(10)), "z"]
VAR_INDEX = {name: idx for idx, name in enumerate(VAR_NAMES)}


def parse_monomial(m: str) -> list[int]:
    exps = [0] * len(VAR_NAMES)
    if m == "1":
        return exps
    for part in m.split("*"):
        if "^" in part:
            name, pow_s = part.split("^", 1)
            power = int(pow_s)
        else:
            name = part
            power = 1
        if name not in VAR_INDEX:
            raise ValueError(f"unknown variable {name!r} in monomial {m!r}")
        exps[VAR_INDEX[name]] += power
    return exps


def lean_list(xs) -> str:
    return "[" + ", ".join(str(x) for x in xs) + "]"


def lean_str(s: str) -> str:
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def emit_rawpoly_base(out_path: Path) -> None:
    lines = [
        "/- Generated/shared RawPoly structures for exact certificate data. -/",
        "import Mathlib",
        "",
        "namespace Erdos23Delta0",
        "namespace Cert",
        "",
        "structure RawTerm where",
        "  coeff : Nat",
        "  exps : List Nat",
        "deriving Repr",
        "",
        "abbrev RawPoly := List RawTerm",
        "",
        "end Cert",
        "end Erdos23Delta0",
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def emit_tau0(data: dict, out_path: Path) -> dict:
    if data.get("verdict") != "PASS":
        raise ValueError("tau0 source verdict is not PASS")
    if not data.get("all_denominators_cleared"):
        raise ValueError("tau0 denominators are not all cleared")
    if not data.get("all_coefficients_nonnegative"):
        raise ValueError("tau0 coefficients are not all nonnegative")

    row_entries: list[str] = []
    term_counts: list[int] = []
    max_degrees: list[int] = []
    for row in data["rows"]:
        coeffs = row.get("coefficients")
        if not coeffs:
            raise ValueError(f"row {row['index']} has no coefficient dump")
        terms = []
        for monom, coeff_s in coeffs.items():
            coeff = int(coeff_s)
            if coeff < 0:
                raise ValueError(f"negative coefficient in row {row['index']}: {coeff}")
            terms.append("{ coeff := %d, exps := %s }" % (coeff, lean_list(parse_monomial(monom))))
        if len(terms) != int(row["terms"]):
            raise ValueError(f"term count mismatch in row {row['index']}")
        term_counts.append(len(terms))
        max_degrees.append(int(row["total_degree"]))
        row_entries.append(
            "{ index := %d, row := %s, totalDegree := %d, termCount := %d, terms := [%s] }"
            % (
                int(row["index"]),
                lean_list(row["row"]),
                int(row["total_degree"]),
                len(terms),
                ", ".join(terms),
            )
        )

    lines: list[str] = []
    lines.append("/- Generated by _codex_tau0_rawpoly_to_lean.py.")
    lines.append("   tau_0 MCERT RawPoly literal lists; do not edit by hand. -/")
    lines.append("")
    lines.append("import Mathlib")
    lines.append("")
    lines.append("namespace Erdos23Delta0")
    lines.append("namespace Cert")
    lines.append("")
    lines.append("structure Tau0RawTerm where")
    lines.append("  coeff : Nat")
    lines.append("  exps : List Nat")
    lines.append("deriving Repr")
    lines.append("")
    lines.append("abbrev Tau0RawPoly := List Tau0RawTerm")
    lines.append("")
    lines.append("structure Tau0RowRawPoly where")
    lines.append("  index : Nat")
    lines.append("  row : List Nat")
    lines.append("  totalDegree : Nat")
    lines.append("  termCount : Nat")
    lines.append("  terms : Tau0RawPoly")
    lines.append("deriving Repr")
    lines.append("")
    lines.append(f"def tau0Graph : String := {lean_str(data['graph'])}")
    lines.append(f"def tau0Side : String := {lean_str(data['side'])}")
    lines.append(f"def tau0VariableNames : List String := [{', '.join(lean_str(v) for v in VAR_NAMES)}]")
    lines.append(f"def tau0ActiveRow : List Nat := {lean_list(data['active_row'])}")
    bad_edges = ["(%d, %d)" % (a, b) for a, b in data["bad_edges"]]
    lines.append(f"def tau0BadEdges : List (Nat × Nat) := [{', '.join(bad_edges)}]")
    lines.append("")
    lines.append("def tau0Rows : List Tau0RowRawPoly := [")
    lines.append(",\n".join("  " + entry for entry in row_entries))
    lines.append("]")
    lines.append("")
    lines.append(f"theorem tau0Rows_length : tau0Rows.length = {len(row_entries)} := by")
    lines.append("  rfl")
    lines.append("")
    lines.append("end Cert")
    lines.append("end Erdos23Delta0")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return {
        "schema": "tau0_rawpoly_lean_emit_v1",
        "source_verdict": data.get("verdict"),
        "row_count": len(row_entries),
        "term_counts": term_counts,
        "total_terms": sum(term_counts),
        "max_total_degree": max(max_degrees) if max_degrees else 0,
        "variables": VAR_NAMES,
        "output": str(out_path),
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default="tmp/mcert_tau0_v1_coefficients.json")
    ap.add_argument("--rawpoly-out", default="problems/23/lean/Erdos23Delta0/Cert/RawPoly.lean")
    ap.add_argument("--tau0-out", default="problems/23/lean/Erdos23Delta0/Cert/Tau0Data.lean")
    ap.add_argument("--manifest", default="tmp/tau0_rawpoly_lean_emit_v1_manifest.json")
    args = ap.parse_args()
    data = json.loads(Path(args.input).read_text())
    emit_rawpoly_base(Path(args.rawpoly_out))
    manifest = emit_tau0(data, Path(args.tau0_out))
    Path(args.manifest).write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(
        "PASS tau0 rawpoly lean emit",
        f"rows={manifest['row_count']}",
        f"terms={manifest['total_terms']}",
        f"max_degree={manifest['max_total_degree']}",
    )


if __name__ == "__main__":
    main()
