#!/usr/bin/env python3
"""Emit proof-critical Branch-B core operation signatures as small Lean data.

The source JSON contains the 24 op-level core signatures extracted from the
accepted Branch-B Gate-B assembly.  This emitter keeps only the small finite
certificate payload intended for import by the universal proof path: op class,
role, boundary counts, exchange_q, rho_a, occurrence count, and the dictionary
(nonnegative unit-exchange) decomposition whose contributions sum to rho_a.
"""

from __future__ import annotations

import argparse
import json
from fractions import Fraction
from pathlib import Path
from typing import Any

OP_CLASS_TO_LEAN = {
    "empty": "CoreOpClass.empty",
    "terminal-prefix-raw-extraction": "CoreOpClass.terminalPrefixRawExtraction",
    "terminal-prefix-lane-addition": "CoreOpClass.terminalPrefixLaneAddition",
    "noncrossing-coB-extraction": "CoreOpClass.noncrossingCoBExtraction",
    "noncrossing-coB-component-addition": "CoreOpClass.noncrossingCoBComponentAddition",
}

DICT_CLASS_TO_LEAN = {
    "empty": "CoreDictClass.empty",
    "terminal-prefix-raw-extraction": "CoreDictClass.terminalPrefixRawExtraction",
    "terminal-prefix-lane-addition": "CoreDictClass.terminalPrefixLaneAddition",
    "noncrossing-coB-extraction": "CoreDictClass.noncrossingCoBExtraction",
    "noncrossing-coB-component-addition": "CoreDictClass.noncrossingCoBComponentAddition",
}

STEP_ROLE_TO_LEAN = {
    "add_final_part": "CoreStepRole.addFinalPart",
    "remove_raw_extra_via_complement": "CoreStepRole.removeRawExtraViaComplement",
}


def lean_str(s: str) -> str:
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def parse_int(v: Any) -> int:
    q = Fraction(str(v))
    if q.denominator != 1:
        raise ValueError(f"expected integer, got {v!r}")
    return q.numerator


def emit_decomp(row: dict[str, Any]) -> str:
    coeff = parse_int(row["coeff"])
    contribution = parse_int(row["contribution"])
    value = parse_int(row["value"])
    if contribution != coeff * value:
        raise ValueError(f"bad contribution identity: {row}")
    dictionary_class = row["dictionary_class"]
    if dictionary_class not in DICT_CLASS_TO_LEAN:
        raise ValueError(f"unknown dictionary class {dictionary_class!r}")
    return (
        "{ "
        f"coeff := {coeff}, "
        f"contribution := {contribution}, "
        f"dictionaryClass := {DICT_CLASS_TO_LEAN[dictionary_class]}, "
        f"generator := {lean_str(row['generator'])}, "
        f"value := {value} "
        "}"
    )


def emit_signature(sig: dict[str, Any]) -> tuple[str, int, int]:
    key = sig["key"]
    op_class = key["op_class"]
    step_role = key["step_role"]
    if op_class not in OP_CLASS_TO_LEAN:
        raise ValueError(f"unknown op class {op_class!r}")
    if step_role not in STEP_ROLE_TO_LEAN:
        raise ValueError(f"unknown step role {step_role!r}")
    decomp_rows = key.get("dictionary_decomposition", [])
    decomp = [emit_decomp(r) for r in decomp_rows]
    decomp_sum = sum(parse_int(r["contribution"]) for r in decomp_rows)
    rho = parse_int(key["rho_a"])
    if decomp_sum != rho:
        raise ValueError(
            f"decomposition sum mismatch for signature {sig.get('signature_id')}: {decomp_sum} != {rho}"
        )
    sid = str(sig["signature_id"])
    count = int(sig["count"])
    body = (
        "{ "
        f"signatureId := {lean_str(sid)}, "
        f"occurrences := {count}, "
        f"opClass := {OP_CLASS_TO_LEAN[op_class]}, "
        f"stepRole := {STEP_ROLE_TO_LEAN[step_role]}, "
        f"eB_XS := {int(key['eB_XS'])}, "
        f"eM_XS := {int(key['eM_XS'])}, "
        f"eB_XO := {int(key['eB_XO'])}, "
        f"eM_XO := {int(key['eM_XO'])}, "
        f"exchangeQ := {int(key['exchange_q'])}, "
        f"rhoA := {rho}, "
        f"decomp := [{', '.join(decomp)}] "
        "}"
    )
    return body, decomp_sum, rho


def emit_lean(data: dict[str, Any], out_path: Path) -> dict[str, Any]:
    sigs = data["signatures"]
    if len(sigs) != int(data["signature_count"]):
        raise ValueError("signature_count mismatch")
    positive = sum(1 for s in sigs if parse_int(s["key"]["rho_a"]) > 0)
    if positive != int(data["positive_signature_count"]):
        raise ValueError("positive_signature_count mismatch")

    emitted: list[str] = []
    audit_pairs: list[tuple[int, int]] = []
    margins: list[int] = []
    for sig in sigs:
        body, total, rho = emit_signature(sig)
        emitted.append(body)
        audit_pairs.append((total, rho))
        margins.append(rho - total)

    lines: list[str] = []
    lines.append("/- Generated by _codex_core_signatures_to_lean.py.")
    lines.append("   Proof-critical Branch-B core operation signatures; do not edit by hand. -/")
    lines.append("")
    lines.append("import Mathlib")
    lines.append("")
    lines.append("namespace Erdos23Delta0")
    lines.append("namespace Cert")
    lines.append("")
    lines.append("inductive CoreOpClass where")
    lines.append("  | empty")
    lines.append("  | terminalPrefixRawExtraction")
    lines.append("  | terminalPrefixLaneAddition")
    lines.append("  | noncrossingCoBExtraction")
    lines.append("  | noncrossingCoBComponentAddition")
    lines.append("deriving DecidableEq, Repr")
    lines.append("")
    lines.append("inductive CoreDictClass where")
    lines.append("  | empty")
    lines.append("  | terminalPrefixRawExtraction")
    lines.append("  | terminalPrefixLaneAddition")
    lines.append("  | noncrossingCoBExtraction")
    lines.append("  | noncrossingCoBComponentAddition")
    lines.append("deriving DecidableEq, Repr")
    lines.append("")
    lines.append("inductive CoreStepRole where")
    lines.append("  | addFinalPart")
    lines.append("  | removeRawExtraViaComplement")
    lines.append("deriving DecidableEq, Repr")
    lines.append("")
    lines.append("structure CoreDictDecomp where")
    lines.append("  coeff : Int")
    lines.append("  contribution : Int")
    lines.append("  dictionaryClass : CoreDictClass")
    lines.append("  generator : String")
    lines.append("  value : Int")
    lines.append("deriving Repr")
    lines.append("")
    lines.append("def decompTotal : List CoreDictDecomp -> Int")
    lines.append("  | [] => 0")
    lines.append("  | d :: ds => d.contribution + decompTotal ds")
    lines.append("")
    lines.append("structure CoreOpSignature where")
    lines.append("  signatureId : String")
    lines.append("  occurrences : Nat")
    lines.append("  opClass : CoreOpClass")
    lines.append("  stepRole : CoreStepRole")
    lines.append("  eB_XS : Int")
    lines.append("  eM_XS : Int")
    lines.append("  eB_XO : Int")
    lines.append("  eM_XO : Int")
    lines.append("  exchangeQ : Int")
    lines.append("  rhoA : Int")
    lines.append("  decomp : List CoreDictDecomp")
    lines.append("deriving Repr")
    lines.append("")
    lines.append("def coreSignatures : List CoreOpSignature := [")
    lines.append(",\n".join("  " + row for row in emitted))
    lines.append("]")
    lines.append("")
    lines.append(f"theorem coreSignatures_length : coreSignatures.length = {len(sigs)} := by")
    lines.append("  rfl")
    lines.append("")
    lines.append("def coreSignatureDecompAudit : List (Int × Int) :=")
    lines.append("  coreSignatures.map (fun s => (decompTotal s.decomp, s.rhoA))")
    lines.append("")
    pair_text = ", ".join(f"({a}, {b})" for a, b in audit_pairs)
    lines.append("theorem coreSignatureDecompAudit_expected :")
    lines.append(f"    coreSignatureDecompAudit = [{pair_text}] := by")
    lines.append("  rfl")
    lines.append("")
    lines.append("def coreSignatureDecompMargins : List Int :=")
    lines.append("  coreSignatures.map (fun s => s.rhoA - decompTotal s.decomp)")
    lines.append("")
    margin_text = ", ".join(str(m) for m in margins)
    lines.append("theorem coreSignatureDecompMargins_zero :")
    lines.append(f"    coreSignatureDecompMargins = [{margin_text}] := by")
    lines.append("  rfl")
    lines.append("")
    lines.append("end Cert")
    lines.append("end Erdos23Delta0")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return {
        "schema": "core_signatures_lean_emit_v1",
        "input_schema": data.get("schema"),
        "signature_count": len(sigs),
        "positive_signature_count": positive,
        "output": str(out_path),
        "audit_pairs": audit_pairs,
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default="tmp/bankl_completion_op_sequence_core_signatures_v1.json")
    ap.add_argument("--output", default="problems/23/lean/Erdos23Delta0/Cert/CoreSignatures.lean")
    ap.add_argument("--manifest", default="tmp/core_signatures_lean_emit_v1_manifest.json")
    args = ap.parse_args()
    data = json.loads(Path(args.input).read_text())
    manifest = emit_lean(data, Path(args.output))
    Path(args.manifest).write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(
        "PASS core signatures lean emit",
        f"signatures={manifest['signature_count']}",
        f"positive={manifest['positive_signature_count']}",
        f"output={manifest['output']}",
    )


if __name__ == "__main__":
    main()