#!/usr/bin/env python3
"""Emit tau_0 MCERT polynomials as standalone per-row Lean RawPoly shards."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

VAR_NAMES = [*(f"w{i}" for i in range(10)), "z"]
VAR_INDEX = {name: idx for idx, name in enumerate(VAR_NAMES)}


def parse_monomial(m: str) -> list[int]:
    exps = [0] * len(VAR_NAMES)
    if m == "1":
        return exps
    for part in m.split("*"):
        if "^" in part:
            name, pow_s = part.split("^", 1)
            power = int(pow_s)
        else:
            name = part
            power = 1
        if name not in VAR_INDEX:
            raise ValueError(f"unknown variable {name!r} in monomial {m!r}")
        exps[VAR_INDEX[name]] += power
    return exps


def lean_list(xs) -> str:
    return "[" + ", ".join(str(x) for x in xs) + "]"


def lean_str(s: str) -> str:
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def term_literal(monom: str, coeff_s: str) -> str:
    coeff = int(coeff_s)
    if coeff < 0:
        raise ValueError(f"negative coefficient {coeff_s} at {monom}")
    return "{ coeff := %d, exps := %s }" % (coeff, lean_list(parse_monomial(monom)))


def shard_header() -> list[str]:
    return [
        "/- Generated by _codex_tau0_rawpoly_shards_to_lean.py.",
        "   One tau_0 MCERT RawPoly row shard; do not edit by hand. -/",
        "",
        "import Mathlib",
        "",
        "set_option maxRecDepth 100000",
        "",
        "namespace Erdos23Delta0",
        "namespace Cert",
        "",
        "structure Tau0RawTerm where",
        "  coeff : Nat",
        "  exps : List Nat",
        "deriving Repr",
        "",
        "abbrev Tau0RawPoly := List Tau0RawTerm",
        "",
    ]


def emit_row(row: dict, out_path: Path) -> dict:
    coeffs = row.get("coefficients")
    if not coeffs:
        raise ValueError(f"row {row['index']} missing coefficient dump")
    terms = [term_literal(m, c) for m, c in coeffs.items()]
    if len(terms) != int(row["terms"]):
        raise ValueError(f"row {row['index']} term count mismatch")
    idx = int(row["index"])
    lines = shard_header()
    lines.append(f"def tau0Row{idx:02d}Index : Nat := {idx}")
    lines.append(f"def tau0Row{idx:02d}Vertices : List Nat := {lean_list(row['row'])}")
    lines.append(f"def tau0Row{idx:02d}TotalDegree : Nat := {int(row['total_degree'])}")
    lines.append(f"def tau0Row{idx:02d}TermCount : Nat := {len(terms)}")
    lines.append("")
    lines.append(f"def tau0Row{idx:02d}Terms : Tau0RawPoly := [")
    lines.append(",\n".join("  " + t for t in terms))
    lines.append("]")
    lines.append("")
    lines.append("end Cert")
    lines.append("end Erdos23Delta0")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return {
        "index": idx,
        "row": row["row"],
        "terms": len(terms),
        "total_degree": int(row["total_degree"]),
        "output": str(out_path),
    }


def emit_index(data: dict, rows_meta: list[dict], out_path: Path) -> None:
    lines = [
        "/- Generated by _codex_tau0_rawpoly_shards_to_lean.py.",
        "   tau_0 MCERT shard manifest data; term payloads live in RowXX.lean. -/",
        "",
        "import Mathlib",
        "",
        "namespace Erdos23Delta0",
        "namespace Cert",
        "",
        "structure Tau0RowMeta where",
        "  index : Nat",
        "  row : List Nat",
        "  termCount : Nat",
        "  totalDegree : Nat",
        "deriving Repr",
        "",
        f"def tau0Graph : String := {lean_str(data['graph'])}",
        f"def tau0Side : String := {lean_str(data['side'])}",
        f"def tau0VariableNames : List String := [{', '.join(lean_str(v) for v in VAR_NAMES)}]",
        f"def tau0ActiveRow : List Nat := {lean_list(data['active_row'])}",
        "",
        "def tau0RowsMeta : List Tau0RowMeta := [",
    ]
    entries = []
    for r in rows_meta:
        entries.append(
            "{ index := %d, row := %s, termCount := %d, totalDegree := %d }"
            % (r["index"], lean_list(r["row"]), r["terms"], r["total_degree"])
        )
    lines.append(",\n".join("  " + e for e in entries))
    lines.append("]")
    lines.append("")
    lines.append(f"theorem tau0RowsMeta_length : tau0RowsMeta.length = {len(rows_meta)} := by")
    lines.append("  rfl")
    lines.append("")
    lines.append("end Cert")
    lines.append("end Erdos23Delta0")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default="tmp/mcert_tau0_v1_coefficients.json")
    ap.add_argument("--out-dir", default="problems/23/lean/Erdos23Delta0/Cert/Tau0Data")
    ap.add_argument("--index-out", default="problems/23/lean/Erdos23Delta0/Cert/Tau0Data.lean")
    ap.add_argument("--manifest", default="tmp/tau0_rawpoly_shards_lean_emit_v1_manifest.json")
    args = ap.parse_args()
    data = json.loads(Path(args.input).read_text())
    if data.get("verdict") != "PASS" or not data.get("all_denominators_cleared") or not data.get("all_coefficients_nonnegative"):
        raise ValueError("tau0 source is not an accepted exact coefficient artifact")
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    rows_meta = []
    for row in data["rows"]:
        idx = int(row["index"])
        rows_meta.append(emit_row(row, out_dir / f"Row{idx:02d}.lean"))
    emit_index(data, rows_meta, Path(args.index_out))
    manifest = {
        "schema": "tau0_rawpoly_shards_lean_emit_v1",
        "row_count": len(rows_meta),
        "total_terms": sum(r["terms"] for r in rows_meta),
        "max_total_degree": max(r["total_degree"] for r in rows_meta),
        "index_output": args.index_out,
        "rows": rows_meta,
    }
    Path(args.manifest).write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(
        "PASS tau0 rawpoly shard emit",
        f"rows={manifest['row_count']}",
        f"terms={manifest['total_terms']}",
        f"max_degree={manifest['max_total_degree']}",
    )


if __name__ == "__main__":
    main()
