"""Gate a closed-tail switch for P-contained position-flow deficits.

For a unique bad edge f with unique B-geodesic P, consider only P-contained
atoms: shortest B-geodesics Q of other bad edges with V(Q) contained in V(P).
Build the position-flow with demand equal to the contained atom load at each
position and off-path B-component capacities |C| over attachment spans.

Candidate lemma:

  If the P-contained position-flow is infeasible and there is no bracket hub
  (no path position is both a left endpoint and a right endpoint of
  P-contained atom intervals), then one of the closed prefix/suffix switches
  generated by an atom endpoint has positive cut gain.

The switch closes a raw prefix/suffix by absorbing every off-path B-component
whose attachments to P all lie in the raw switched path set.
"""

from __future__ import annotations

import argparse
import subprocess
from concurrent.futures import ProcessPoolExecutor
from fractions import Fraction as F

from _closed_tail_switch_gate import b_closed_tail
from _codex_net_globalmax_probe import contained_flow_failures
from _h import Bconn, GENG, dec
from _M_tailswitch_gate import boundary_gain
from _overlap_switch_probe import contained_intervals
from _satzmu_conn import struct_for_side


def has_bracket(intervals: list[tuple[int, int, tuple[int, int]]]) -> bool:
    starts = {lo for lo, _hi, _g in intervals}
    ends = {hi for _lo, hi, _g in intervals}
    return bool(starts & ends)


def best_atom_tail(n: int, adj, side: list[int], path: list[int], intervals):
    best = -10**9
    best_arg = None
    candidates = set()
    L = len(path)
    for lo, hi, _g in intervals:
        for k in range(lo, hi + 1):
            candidates.add(("prefix", k))
            candidates.add(("suffix", k))
        for k in (lo - 1, hi + 1):
            if 0 <= k < L:
                candidates.add(("prefix", k))
                candidates.add(("suffix", k))

    for typ, k in candidates:
        raw = set(path[: k + 1]) if typ == "prefix" else set(path[k:])
        if not raw:
            continue
        W = b_closed_tail(n, adj, side, path, raw)
        gain = boundary_gain(n, adj, side, W)
        if gain > best:
            best = gain
            best_arg = (typ, k, tuple(sorted(W)))
    return best, best_arg


def graph_probe(g6: str):
    n, edges = dec(g6)
    adj = [set() for _ in range(n)]
    for a, b in edges:
        adj[a].add(b)
        adj[b].add(a)

    deficits = brackets = switch_ok = misses = 0
    first = None
    for mask in range(1 << (n - 1)):
        side = [(mask >> v) & 1 for v in range(n)]
        if not Bconn(n, adj, side):
            continue
        st = struct_for_side(n, adj, side)
        if st is None:
            continue
        M, _ell, _T, _mu, cyc = st
        for fail in contained_flow_failures(n, adj, side):
            deficits += 1
            f, path, _chords, _spans, _total, _flow = fail
            intervals = contained_intervals(M, cyc, f, path)
            if has_bracket(intervals):
                brackets += 1
                continue
            best, arg = best_atom_tail(n, adj, side, path, intervals)
            if best > 0:
                switch_ok += 1
            else:
                misses += 1
                if first is None:
                    first = (g6, "".join(map(str, side)), fail, best, arg, intervals)
    return {
        "graphs": 1,
        "deficits": deficits,
        "brackets": brackets,
        "switch_ok": switch_ok,
        "misses": misses,
        "first": first,
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--max-n", type=int, default=9)
    ap.add_argument("--workers", type=int, default=1)
    ap.add_argument("--chunksize", type=int, default=16)
    args = ap.parse_args()

    totals = {k: 0 for k in ("graphs", "deficits", "brackets", "switch_ok", "misses")}
    first = None
    for nn in range(6, args.max_n + 1):
        graphs = subprocess.run([GENG, "-tc", str(nn)], capture_output=True, text=True, check=True).stdout.split()
        part = {k: 0 for k in totals}
        if args.workers > 1:
            with ProcessPoolExecutor(max_workers=args.workers) as ex:
                iterator = ex.map(graph_probe, graphs, chunksize=args.chunksize)
                for res in iterator:
                    for k in part:
                        part[k] += res[k]
                    if first is None and res["first"] is not None:
                        first = res["first"]
        else:
            for g6 in graphs:
                res = graph_probe(g6)
                for k in part:
                    part[k] += res[k]
                if first is None and res["first"] is not None:
                    first = res["first"]
        for k in totals:
            totals[k] += part[k]
        print(f"N={nn} {part}", flush=True)
        if first is not None:
            break
    print("TOTAL", totals, flush=True)
    print("FIRST", first, flush=True)


if __name__ == "__main__":
    main()
