#!/usr/bin/env python3
"""Emit a Lean module from a codex_o14_chunked_cone_export_v1 JSON file."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def lean_rat(q: dict[str, int]) -> str:
    n = int(q["num"])
    d = int(q["den"])
    if d == 1:
        return f"({n} : ℚ)"
    return f"(({n} : ℚ) / ({d} : ℚ))"


def lean_pows(pows: list[list[int]]) -> str:
    if not pows:
        return "[]"
    return "[" + ", ".join(f"({int(v)}, {int(e)})" for v, e in pows) + "]"


def emit_nf_def(lines: list[str], name: str, terms: list[dict[str, Any]]) -> None:
    lines.append("set_option maxRecDepth 2000000 in")
    lines.append(f"def {name} : NF := [")
    for idx, term in enumerate(terms):
        comma = "," if idx + 1 < len(terms) else ""
        lines.append(f"  {{ coeff := {lean_rat(term['coeff'])}, pows := {lean_pows(term['pows'])} }}{comma}")
    lines.append("]")
    lines.append("")


def emit_nf_list_def(lines: list[str], name: str, defs: list[str]) -> None:
    lines.append("set_option maxRecDepth 2000000 in")
    lines.append(f"def {name} : List NF := [")
    for idx, d in enumerate(defs):
        comma = "," if idx + 1 < len(defs) else ""
        lines.append(f"  {d}{comma}")
    lines.append("]")
    lines.append("")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--export", type=Path, default=Path("tmp/codex_o14_chart000_chunked_cone_export_v2.json"))
    ap.add_argument("--out", type=Path, default=Path("problems/23/lean/Erdos23Delta0/O14/Generated/ChartPayloads/Chart000Cone.lean"))
    ap.add_argument("--module-name", default="Chart000Cone")
    args = ap.parse_args()
    data = read_json(args.export)
    if data.get("checks", {}).get("ordinary_identity") is not True:
        raise ValueError("export did not certify ordinary identity")
    if not data.get("combo_order_chunks"):
        raise ValueError("export lacks combo_order_chunks")

    lines: list[str] = []
    lines.append("/- Generated by _codex_o14_chunked_cone_to_lean.py; do not edit by hand. -/")
    lines.append("import Erdos23Delta0.O14.ChunkedConeWitness")
    lines.append("")
    lines.append("namespace Erdos23Delta0")
    lines.append("namespace O14")
    lines.append("namespace Generated")
    lines.append(f"namespace {args.module_name}")
    lines.append("")
    lines.append("open PolyCert")
    lines.append("open ODLFull")
    lines.append("open ConeEvalBridge")
    lines.append("open ChunkedCone")
    lines.append("")
    lines.append(f"def slot : Nat := {int(data['slot'])}")
    lines.append(f"def sourceChart : Nat := {int(data['chart'])}")
    lines.append(f"def dominant : Nat := {int(data['dominant'])}")
    lines.append(f"def sourceColumns : Nat := {int(data['nonzero_solution_columns'])}")
    lines.append(f"def rawComboTerms : Nat := {int(data['raw_combo_terms'])}")
    lines.append(f"def comboOrderChunks : Nat := {int(data['checks']['combo_order_chunk_count'])}")
    lines.append("")

    emit_nf_def(lines, "base", data["base"])

    mult_names: list[str] = []
    slack_names: list[str] = []
    for idx, rec in enumerate(data["mults"]):
        name = f"mult{idx:04d}"
        emit_nf_def(lines, name, rec["nf"])
        mult_names.append(name)
    for idx, rec in enumerate(data["slacks"]):
        name = f"slack{idx:04d}"
        emit_nf_def(lines, name, rec["nf"])
        slack_names.append(name)

    emit_nf_list_def(lines, "mults", mult_names)
    emit_nf_list_def(lines, "slacks", slack_names)

    pair_names: list[str] = []
    for idx, pair in enumerate(data["combo_order_chunks"]):
        lname = f"pair{idx:03d}Left"
        rname = f"pair{idx:03d}Right"
        pname = f"pair{idx:03d}"
        emit_nf_def(lines, lname, pair["left"])
        emit_nf_def(lines, rname, pair["right"])
        lines.append(f"def {pname} : NF × NF := ({lname}, {rname})")
        lines.append("")
        pair_names.append(pname)

    lines.append("set_option maxRecDepth 2000000 in")
    lines.append("def pairs : List (NF × NF) := [")
    for idx, p in enumerate(pair_names):
        comma = "," if idx + 1 < len(pair_names) else ""
        lines.append(f"  {p}{comma}")
    lines.append("]")
    lines.append("")
    lines.append("set_option maxRecDepth 2000000 in")
    lines.append("theorem hbase : base.allCoeffNonneg = true := by")
    lines.append("  rfl")
    lines.append("")
    lines.append("set_option maxRecDepth 2000000 in")
    lines.append("theorem hmults : mults.all NF.allCoeffNonneg = true := by")
    lines.append("  rfl")
    lines.append("")
    lines.append("set_option maxRecDepth 2000000 in")
    lines.append("theorem hchunks : checkEqPairs pairs = true := by")
    lines.append("  rfl")
    lines.append("")
    lines.append("set_option maxRecDepth 2000000 in")
    lines.append("theorem hcombo_list :")
    lines.append("    (pairs.map Prod.snd).flatten = comboNF base mults slacks := by")
    lines.append("  rfl")
    lines.append("")
    lines.append("theorem hcombo (env : Var → ℚ) :")
    lines.append("    NF.eval env ((pairs.map Prod.snd).flatten) =")
    lines.append("      NF.eval env (comboNF base mults slacks) := by")
    lines.append("  rw [hcombo_list]")
    lines.append("")
    lines.append("def chart000Witness")
    lines.append("    {G : CertGraph.GraphData} {c : CertGraph.CutData}")
    lines.append("    {rows : CertGraph.RowDB} {Q : CertGraph.RowCert}")
    lines.append("    (core : ODLCoreData G c rows Q) (env : Var → ℚ)")
    lines.append("    (hvars : ∀ v, 0 ≤ env v)")
    lines.append("    (hslacks : ∀ s ∈ slacks, 0 ≤ NF.eval env s)")
    lines.append("    (htarget : NF.eval env ((pairs.map Prod.fst).flatten) = coreDefect core) :")
    lines.append("    Witness core where")
    lines.append("  pairs := pairs")
    lines.append("  base := base")
    lines.append("  mults := mults")
    lines.append("  slacks := slacks")
    lines.append("  env := env")
    lines.append("  hvars := hvars")
    lines.append("  hbase := hbase")
    lines.append("  hmults := hmults")
    lines.append("  hslacks := hslacks")
    lines.append("  hchunks := hchunks")
    lines.append("  hcombo := hcombo env")
    lines.append("  htarget := htarget")
    lines.append("")
    lines.append("#print axioms hchunks")
    lines.append("#print axioms hcombo")
    lines.append("#print axioms chart000Witness")
    lines.append("")
    lines.append(f"end {args.module_name}")
    lines.append("end Generated")
    lines.append("end O14")
    lines.append("end Erdos23Delta0")
    lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="utf-8")
    summary = {
        "schema": "codex_o14_chunked_cone_lean_emit_v1",
        "input": str(args.export),
        "out": str(args.out),
        "mults": len(mult_names),
        "slacks": len(slack_names),
        "pairs": len(pair_names),
        "raw_combo_terms": data["raw_combo_terms"],
    }
    print(json.dumps(summary, sort_keys=True))


if __name__ == "__main__":
    main()
