#!/usr/bin/env python3
"""Emit Lean data modules for the repaired Rung-2 exact certificate.

The exact full residual check remains the Python/Fraction acceptance gate.  These
positive rational coefficients, bounded source-column ids, manifest metadata, and
record counts.  No native_decide is used by the generated Lean code.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


SUPPORT_MODULE = "Erdos23Delta0.Cert.Rung2Support"
DATA_MODULE_PREFIX = "Erdos23Delta0.Cert.Rung2Data"


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def read_solution(path: Path) -> list[dict[str, int]]:
    rows: list[dict[str, int]] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            rec = json.loads(line)
            rows.append({
                "source_col": int(rec["source_col"]),
                "num": int(rec["num"]),
                "den": int(rec["den"]),
            })
    rows.sort(key=lambda r: r["source_col"])
    return rows


def lean_str(s: str) -> str:
    return json.dumps(s)


def lean_nat_list(xs: list[int]) -> str:
    return "[" + ", ".join(str(x) for x in xs) + "]"


def support_lines() -> list[str]:
    return [
        "/- Shared support for generated Rung-2 exact certificate data. -/",
        "import Mathlib",
        "",
        "namespace Erdos23Delta0",
        "namespace Cert",
        "",
        "structure Rung2Coeff where",
        "  sourceCol : Nat",
        "  num : Int",
        "  den : Nat",
        "deriving Repr",
        "",
        "def Rung2Coeff.check (columnsChecked : Nat) (c : Rung2Coeff) : Bool :=",
        "  decide (c.sourceCol < columnsChecked) && decide (0 <= c.num) && decide (0 < c.den)",
        "",
        "def rung2CoeffListCheck (columnsChecked : Nat) : List Rung2Coeff -> Bool",
        "  | [] => true",
        "  | c :: cs => Rung2Coeff.check columnsChecked c && rung2CoeffListCheck columnsChecked cs",
        "",
        "def natListSum : List Nat -> Nat",
        "  | [] => 0",
        "  | x :: xs => x + natListSum xs",
        "",
        "structure Rung2Meta where",
        "  chart : Nat",
        "  dominant : Nat",
        "  band : String",
        "  support : String",
        "  columnsChecked : Nat",
        "  nonzeroSourceColumns : Nat",
        "  solutionRecords : Nat",
        "  solutionNegativeCount : Nat",
        "  fullNegativeResidualCount : Nat",
        "  fullMinResidual : String",
        "  badRow : Nat",
        "  badBeta : List Nat",
        "  repairSourceCol : Nat",
        "  repairColumnName : String",
        "  repairColumnKind : String",
        "  repairMultiplierExp : List Nat",
        "  solutionSha256 : String",
        "  repairSummarySha256 : String",
        "  checkSummarySha256 : String",
        "deriving Repr",
        "",
        "def Rung2Meta.check (m : Rung2Meta) : Bool :=",
        "  (m.chart == 0) &&",
        "  (m.dominant == 7) &&",
        "  (m.band == \"near_2s_minus_1\") &&",
        "  (m.support == \"negative\") &&",
        "  (m.columnsChecked == 43128) &&",
        "  (m.nonzeroSourceColumns == m.solutionRecords) &&",
        "  (m.solutionNegativeCount == 0) &&",
        "  (m.fullNegativeResidualCount == 0) &&",
        "  (m.fullMinResidual == \"0\") &&",
        "  (m.badRow == 71491) &&",
        "  (m.badBeta == [1, 1, 0, 0, 2, 2, 1, 0, 3, 1]) &&",
        "  (m.repairSourceCol == 5251) &&",
        "  (m.repairColumnName == \"F5\") &&",
        "  (m.repairColumnKind == \"gen\") &&",
        "  (m.repairMultiplierExp == [1, 0, 0, 0, 2, 2, 1, 0, 3, 0])",
        "",
        "end Cert",
        "end Erdos23Delta0",
        "",
    ]


def emit_support(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(support_lines()), encoding="utf-8")


def emit_shard(path: Path, shard_index: int, records: list[dict[str, int]], columns_checked: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    name = f"rung2CoeffsShard{shard_index:03d}"
    lines: list[str] = []
    lines.append("/- Generated by _codex_eq_odl1_rung2_solution_to_lean.py; do not edit by hand. -/")
    lines.append(f"import {SUPPORT_MODULE}")
    lines.append("")
    lines.append("namespace Erdos23Delta0")
    lines.append("namespace Cert")
    lines.append("")
    lines.append(f"def {name} : List Rung2Coeff := [")
    row_lines = []
    for rec in records:
        row_lines.append(
            "  { "
            f"sourceCol := {rec['source_col']}, "
            f"num := {rec['num']}, "
            f"den := {rec['den']} "
            "}"
        )
    lines.append(",\n".join(row_lines))
    lines.append("]")
    lines.append("")
    lines.append(f"theorem {name}_length : {name}.length = {len(records)} := by")
    lines.append("  rfl")
    lines.append("")
    lines.append("set_option maxRecDepth 200000 in")
    lines.append(f"theorem {name}_check : rung2CoeffListCheck {columns_checked} {name} = true := by")
    lines.append("  rfl")
    lines.append("")
    lines.append("end Cert")
    lines.append("end Erdos23Delta0")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def emit_index(path: Path, manifest: dict[str, Any], shard_paths: list[Path], shard_lengths: list[int]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    def_names = [f"rung2CoeffsShard{idx:03d}" for idx in range(len(shard_paths))]
    lines: list[str] = []
    lines.append("/- Generated aggregate imports for repaired Rung-2 exact certificate data. -/")
    lines.append(f"import {SUPPORT_MODULE}")
    for idx in range(len(shard_paths)):
        lines.append(f"import {DATA_MODULE_PREFIX}.Shard{idx:03d}")
    lines.append("")
    lines.append("namespace Erdos23Delta0")
    lines.append("namespace Cert")
    lines.append("")
    lines.append("def rung2RepairedMeta : Rung2Meta := {")
    lines.append(f"  chart := {manifest['chart']},")
    lines.append(f"  dominant := {manifest['dominant']},")
    lines.append(f"  band := {lean_str(manifest['band'])},")
    lines.append(f"  support := {lean_str(manifest['support'])},")
    lines.append(f"  columnsChecked := {manifest['columns_checked']},")
    lines.append(f"  nonzeroSourceColumns := {manifest['nonzero_source_columns']},")
    lines.append(f"  solutionRecords := {manifest['solution_jsonl_records']},")
    lines.append(f"  solutionNegativeCount := {manifest['solution_negative_count']},")
    lines.append(f"  fullNegativeResidualCount := {manifest['full_negative_residual_count']},")
    lines.append(f"  fullMinResidual := {lean_str(manifest['full_min_residual'])},")
    lines.append(f"  badRow := {manifest['bad_row_repaired']},")
    lines.append(f"  badBeta := {lean_nat_list(manifest['bad_beta'])},")
    lines.append(f"  repairSourceCol := {manifest['repair_source_col']},")
    lines.append(f"  repairColumnName := {lean_str(manifest['repair_column_name'])},")
    lines.append(f"  repairColumnKind := {lean_str(manifest['repair_column_kind'])},")
    lines.append(f"  repairMultiplierExp := {lean_nat_list(manifest['repair_multiplier_exp'])},")
    lines.append(f"  solutionSha256 := {lean_str(manifest['solution_jsonl_sha256'])},")
    lines.append(f"  repairSummarySha256 := {lean_str(manifest['repair_summary_sha256'])},")
    lines.append(f"  checkSummarySha256 := {lean_str(manifest['check_summary_sha256'])}")
    lines.append("}")
    lines.append("")
    lines.append("theorem rung2RepairedMeta_check : Rung2Meta.check rung2RepairedMeta = true := by")
    lines.append("  rfl")
    lines.append("")
    lines.append("def rung2CoeffShardChecks : List Bool := [")
    lines.append("  " + ",\n  ".join(f"rung2CoeffListCheck rung2RepairedMeta.columnsChecked {d}" for d in def_names))
    lines.append("]")
    lines.append("")
    lines.append("set_option maxRecDepth 200000 in")
    lines.append("theorem rung2CoeffShardChecks_expected :")
    lines.append("    rung2CoeffShardChecks = [" + ", ".join(["true"] * len(def_names)) + "] := by")
    lines.append("  rfl")
    lines.append("")
    lines.append("def rung2CoeffShardLengths : List Nat := [")
    lines.append("  " + ",\n  ".join(f"{d}.length" for d in def_names))
    lines.append("]")
    lines.append("")
    lines.append("set_option maxRecDepth 200000 in")
    lines.append("theorem rung2CoeffShardLengths_expected :")
    lines.append("    rung2CoeffShardLengths = [" + ", ".join(str(x) for x in shard_lengths) + "] := by")
    lines.append("  rfl")
    lines.append("")
    lines.append("theorem rung2CoeffShardCount : rung2CoeffShardChecks.length = " + str(len(def_names)) + " := by")
    lines.append("  rfl")
    lines.append("")
    lines.append("set_option maxRecDepth 200000 in")
    lines.append("theorem rung2CoeffTotalRows : natListSum rung2CoeffShardLengths = " + str(sum(shard_lengths)) + " := by")
    lines.append("  rfl")
    lines.append("")
    lines.append("set_option maxRecDepth 200000 in")
    lines.append("theorem rung2CoeffTotalRows_matches_meta : natListSum rung2CoeffShardLengths = rung2RepairedMeta.solutionRecords := by")
    lines.append("  rfl")
    lines.append("")
    lines.append("end Cert")
    lines.append("end Erdos23Delta0")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", type=Path, default=Path("tmp/eq_odl1_rung2_repaired_certificate_manifest_v1.json"))
    ap.add_argument("--support-out", type=Path, default=Path("problems/23/lean/Erdos23Delta0/Cert/Rung2Support.lean"))
    ap.add_argument("--out-dir", type=Path, default=Path("problems/23/lean/Erdos23Delta0/Cert/Rung2Data"))
    ap.add_argument("--index-out", type=Path, default=Path("problems/23/lean/Erdos23Delta0/Cert/Rung2Data.lean"))
    ap.add_argument("--shard-size", type=int, default=500)
    ap.add_argument("--summary", type=Path, default=Path("tmp/eq_odl1_rung2_lean_transpile_v1_manifest.json"))
    args = ap.parse_args()

    manifest = read_json(args.manifest)
    if manifest.get("schema") != "eq_odl1_rung2_repaired_certificate_manifest_v1":
        raise ValueError("unexpected Rung-2 manifest schema")
    if manifest.get("exact_ok") is not True:
        raise ValueError("manifest is not exact_ok")
    records = read_solution(Path(manifest["solution_jsonl"]))
    if len(records) != int(manifest["solution_jsonl_records"]):
        raise ValueError("solution record count mismatch")
    if any(r["num"] < 0 or r["den"] <= 0 for r in records):
        raise ValueError("solution contains nonpositive denominator or negative numerator")
    if any(r["source_col"] >= int(manifest["columns_checked"]) for r in records):
        raise ValueError("solution source column exceeds checked column count")

    emit_support(args.support_out)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    shard_paths: list[Path] = []
    shard_lengths: list[int] = []
    for idx in range(0, len(records), args.shard_size):
        shard_no = len(shard_paths)
        chunk = records[idx : idx + args.shard_size]
        path = args.out_dir / f"Shard{shard_no:03d}.lean"
        emit_shard(path, shard_no, chunk, int(manifest["columns_checked"]))
        shard_paths.append(path)
        shard_lengths.append(len(chunk))
    emit_index(args.index_out, manifest, shard_paths, shard_lengths)

    out = {
        "schema": "eq_odl1_rung2_lean_transpile_v1",
        "input_manifest": str(args.manifest),
        "support_out": str(args.support_out),
        "index_out": str(args.index_out),
        "out_dir": str(args.out_dir),
        "shards": len(shard_paths),
        "shard_lengths": shard_lengths,
        "rows": len(records),
        "columns_checked": manifest["columns_checked"],
        "solution_sha256": manifest["solution_jsonl_sha256"],
        "emitted": [str(args.support_out), *[str(p) for p in shard_paths], str(args.index_out)],
    }
    args.summary.parent.mkdir(parents=True, exist_ok=True)
    args.summary.write_text(json.dumps(out, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps({"rows": out["rows"], "shards": out["shards"], "index_out": out["index_out"]}, sort_keys=True))


if __name__ == "__main__":
    main()

