"""Exact census gate for the R20 two-row exchange statement.

For each connected triangle-free graph generated by ``geng -tc``, ``loads``
selects the Gamma-minimum connected maximum cut.  On all-ell=5 instances this
gate enumerates the dependent product of one shortest row per bad edge.  A
tuple that fails the reserved-hit, sameOwner-or-rowCompanion collision matcher
must have a strictly smaller obligation-score tuple at Hamming distance one or
two.

All scores, matching capacities, and descent comparisons use integers.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections import Counter
from concurrent.futures import ProcessPoolExecutor
from itertools import combinations, product
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _codex_r19_global_base_census import (  # noqa: E402
    dec,
    edge,
    evaluate_rows,
    graph6_for_orders,
    loads,
    multiplicities,
)


STAT_FIELDS = (
    "graphs",
    "totalTuples",
    "failingTuples",
    "failingWithOneRowDescent",
    "failingWithOnlyTwoRowDescent",
    "failingWithNoAtMostTwoDescent",
    "failingOneLocalMinima",
)


def shortest_row_families(info) -> tuple[tuple[tuple[int, ...], ...], ...]:
    """Return the bad-edge-ordered coherent shortest-row families."""
    families = []
    for bad_edge in info["M"]:
        rows = tuple(tuple(row) for row in info["cyc"][bad_edge])
        assert rows
        for row in rows:
            assert len(row) == 5
            assert (row[0], row[-1]) == bad_edge
            assert all(edge(u, v) in info["Bset"] for u, v in zip(row, row[1:]))
        families.append(rows)
    return tuple(families)


def obligation_score(n: int, info, rows: tuple[tuple[int, ...], ...]) -> int:
    """Mirror MinimumDemandRowSelection.obligationScore exactly."""
    count = multiplicities(n, rows)
    collision_units = sum(
        max(0, count[x][y] - 1)
        for x in range(n)
        for y in range(n)
    )
    selected_vertices = {vertex for row in rows for vertex in row}
    selected_support = {
        edge(u, v)
        for row in rows
        for u, v in zip(row, row[1:])
    }
    active_edges = sum(
        u in selected_vertices
        and v in selected_vertices
        and (u, v) not in selected_support
        for u, v in info["Bset"]
    )
    return 2 * collision_units + 2 * active_edges


def minimum_neighbor_scores(choice, family_sizes, scores):
    """Return minimum scores at Hamming distance exactly one and exactly two."""
    one_row = None
    for index, size in enumerate(family_sizes):
        for replacement in range(size):
            if replacement == choice[index]:
                continue
            neighbor = choice[:index] + (replacement,) + choice[index + 1:]
            value = scores[neighbor]
            one_row = value if one_row is None else min(one_row, value)

    two_row = None
    for left, right in combinations(range(len(choice)), 2):
        for left_replacement in range(family_sizes[left]):
            if left_replacement == choice[left]:
                continue
            for right_replacement in range(family_sizes[right]):
                if right_replacement == choice[right]:
                    continue
                neighbor = list(choice)
                neighbor[left] = left_replacement
                neighbor[right] = right_replacement
                value = scores[tuple(neighbor)]
                two_row = value if two_row is None else min(two_row, value)
    return one_row, two_row


def evaluate_graph(g6: str):
    """Enumerate and classify every coherent row tuple of one graph."""
    n, graph_edges = dec(g6)
    info = loads(n, graph_edges)
    if info is None:
        return {"status": "skipNoCut", "g6": g6, "order": n}
    if any(length != 5 for length in info["ell"].values()):
        return {"status": "skipNotAll5", "g6": g6, "order": n}

    families = shortest_row_families(info)
    family_sizes = tuple(len(family) for family in families)
    choices = list(product(*(range(size) for size in family_sizes)))
    scores = {}
    failures = []

    for choice in choices:
        rows = tuple(families[index][row_index]
                     for index, row_index in enumerate(choice))
        score = obligation_score(n, info, rows)
        scores[choice] = score
        kind, returned_g6, detail = evaluate_rows(
            g6, n, info, rows, "row-reserved"
        )
        assert returned_g6 == g6
        if kind == "fail":
            failures.append((choice, rows, score, detail))
        else:
            assert kind == "pass"

    one_descent = 0
    only_two_descent = 0
    no_two_descent = 0
    failing_one_local_minima = 0
    counterexamples = []
    for choice, rows, score, detail in failures:
        best_one, best_two = minimum_neighbor_scores(
            choice, family_sizes, scores
        )
        has_one = best_one is not None and best_one < score
        has_two = best_two is not None and best_two < score
        if has_one:
            one_descent += 1
            continue

        failing_one_local_minima += 1
        if has_two:
            only_two_descent += 1
            continue

        no_two_descent += 1
        counterexamples.append({
            "g6": g6,
            "order": n,
            "badEdges": [list(bad_edge) for bad_edge in info["M"]],
            "familySizes": list(family_sizes),
            "rowChoices": list(choice),
            "rows": [list(row) for row in rows],
            "obligationScore": score,
            "bestOneRowScore": best_one,
            "bestTwoRowScore": best_two,
            "matchingFailure": detail,
        })

    assert len(failures) == one_descent + only_two_descent + no_two_descent
    assert failing_one_local_minima == only_two_descent + no_two_descent
    return {
        "status": "eligible",
        "g6": g6,
        "order": n,
        "graphs": 1,
        "totalTuples": len(choices),
        "failingTuples": len(failures),
        "failingWithOneRowDescent": one_descent,
        "failingWithOnlyTwoRowDescent": only_two_descent,
        "failingWithNoAtMostTwoDescent": no_two_descent,
        "failingOneLocalMinima": failing_one_local_minima,
        "counterexamples": counterexamples,
    }


def empty_stats():
    return {field: 0 for field in STAT_FIELDS}


def add_stats(target, source):
    for field in STAT_FIELDS:
        target[field] += source.get(field, 0)


def positive_int(value: str) -> int:
    parsed = int(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("must be a positive integer")
    return parsed


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--min-order", type=positive_int, default=5)
    parser.add_argument("--max-order", type=positive_int, default=10)
    parser.add_argument("--workers", type=positive_int, default=min(48, os.cpu_count() or 1))
    parser.add_argument(
        "--graph6",
        action="append",
        default=[],
        help="test this graph6 fixture instead of generating an order range; repeatable",
    )
    args = parser.parse_args()
    if args.min_order > args.max_order:
        parser.error("--min-order must not exceed --max-order")
    if args.workers > 64:
        parser.error("--workers must not exceed 64")
    return args


def main():
    args = parse_args()
    if args.graph6:
        graph6 = args.graph6
        generated = dict(sorted(Counter(dec(g6)[0] for g6 in graph6).items()))
    else:
        graph6, generated = graph6_for_orders(args.min_order, args.max_order)

    aggregate = empty_stats()
    by_order = {}
    status = Counter()
    counterexamples = []

    if args.workers == 1:
        results = map(evaluate_graph, graph6)
        pool = None
    else:
        pool = ProcessPoolExecutor(max_workers=args.workers)
        results = pool.map(evaluate_graph, graph6, chunksize=4)

    try:
        for result in results:
            status[result["status"]] += 1
            if result["status"] != "eligible":
                continue
            order_stats = by_order.setdefault(result["order"], empty_stats())
            add_stats(aggregate, result)
            add_stats(order_stats, result)
            counterexamples.extend(result["counterexamples"])
    finally:
        if pool is not None:
            pool.shutdown()

    payload = {
        "orders": [args.min_order, args.max_order],
        "workers": args.workers,
        "fixtureMode": bool(args.graph6),
        "generatedGraphs": len(graph6),
        "generatedByOrder": {str(k): v for k, v in sorted(generated.items())},
        "status": dict(sorted(status.items())),
        **aggregate,
        "byOrder": {
            str(order): values for order, values in sorted(by_order.items())
        },
        "counterexamples": counterexamples,
    }
    print(json.dumps(payload, sort_keys=True, separators=(",", ":")))


if __name__ == "__main__":
    main()
