"""Exact R20 two-row exchange gate over every connected maximum cut.

For every connected triangle-free graph generated by ``geng -tc``, enumerate
all maximum cuts (up to complementary sides), retain the B-connected cuts with
a nonempty bad-edge set and ``ell = 5`` on every bad edge, and enumerate the
full dependent product of coherent shortest rows.  Every failure of the
row-reserved sameOwner/rowCompanion matcher must admit a strict obligation-
score descent after replacing one or two rows.

Cut identities are canonical side bitmasks: bit ``v`` is the side of vertex
``v``, and the smaller of a mask and its complement is used.  Matching,
scores, cut masks, and all reported counts use integers only.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections import Counter, deque
from concurrent.futures import ProcessPoolExecutor
from itertools import product, repeat
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _codex_r19_global_base_census import (  # noqa: E402
    dec,
    edge,
    evaluate_rows,
    graph6_for_orders,
)
from _codex_r20_two_row_exchange_gate import (  # noqa: E402
    minimum_neighbor_scores,
    obligation_score,
    shortest_row_families,
)
from _h import Bconn, bdist_restr, geos, maxcut_all  # noqa: E402


STAT_FIELDS = (
    "graphs",
    "connectedTriangleFreeGraphs",
    "graphsWithEligibleCuts",
    "maximumCuts",
    "bConnectedMaximumCuts",
    "bConnectedCutsWithBadEdges",
    "eligibleCuts",
    "totalTuples",
    "failingTuples",
    "failingWithOneRowDescent",
    "failingWithOnlyTwoRowDescent",
    "failingWithNoAtMostTwoDescent",
)


def empty_stats() -> dict[str, int]:
    return {field: 0 for field in STAT_FIELDS}


def add_stats(target: dict[str, int], source: dict[str, int]) -> None:
    for field in STAT_FIELDS:
        target[field] += source.get(field, 0)


def graph_status(n: int, adjacency: list[set[int]]) -> str:
    """Check the domain promised by ``geng -tc`` for fixture-mode inputs."""
    seen = {0}
    queue = deque([0])
    while queue:
        u = queue.popleft()
        for v in adjacency[u]:
            if v not in seen:
                seen.add(v)
                queue.append(v)
    if len(seen) != n:
        return "skipDisconnected"
    if any(
        adjacency[u] & adjacency[v]
        for u in range(n)
        for v in adjacency[u]
        if u < v
    ):
        return "skipNotTriangleFree"
    return "connectedTriangleFree"


def canonical_side(side: list[int] | tuple[int, ...]) -> tuple[int, tuple[int, ...]]:
    """Return the complement-invariant mask and its represented side."""
    n = len(side)
    mask = sum(int(bit) << vertex for vertex, bit in enumerate(side))
    complement = ((1 << n) - 1) ^ mask
    canonical = min(mask, complement)
    represented = tuple((canonical >> vertex) & 1 for vertex in range(n))
    return canonical, represented


def literal_cut_info(
    n: int,
    adjacency: list[set[int]],
    side: tuple[int, ...],
    side_bitmask: int,
):
    """Construct the exact per-cut fields used by the R20 matcher and score."""
    graph_edges = tuple(
        (u, v)
        for u in range(n)
        for v in sorted(adjacency[u])
        if u < v
    )
    bad_edges = tuple(
        graph_edge
        for graph_edge in graph_edges
        if side[graph_edge[0]] == side[graph_edge[1]]
    )
    if not bad_edges:
        return "emptyBadSet", None

    lengths = {}
    for bad_edge in bad_edges:
        distance = bdist_restr(
            adjacency, side, bad_edge[0], bad_edge[1]
        )
        assert distance >= 0
        lengths[bad_edge] = distance + 1
    if any(length != 5 for length in lengths.values()):
        return "notAll5", None

    blue = {
        graph_edge
        for graph_edge in graph_edges
        if side[graph_edge[0]] != side[graph_edge[1]]
    }
    bad = set(bad_edges)
    rows_by_edge = {}
    for bad_edge in bad_edges:
        rows = tuple(sorted(
            tuple(row)
            for row in geos(adjacency, side, bad_edge[0], bad_edge[1])
        ))
        assert rows
        assert all(len(row) == lengths[bad_edge] for row in rows)
        rows_by_edge[bad_edge] = rows

    return "eligible", {
        "n": n,
        "adj": adjacency,
        "side": side,
        "sideBitmask": side_bitmask,
        "M": bad_edges,
        "ell": lengths,
        "Bset": blue,
        "Mset": bad,
        "cyc": rows_by_edge,
        "G": sum(length * length for length in lengths.values()),
    }


def falsifier_record(
    g6: str,
    n: int,
    info,
    family_sizes: tuple[int, ...],
    choice: tuple[int, ...],
    rows: tuple[tuple[int, ...], ...],
    score: int,
    best_one: int | None,
    best_two: int | None,
    detail,
):
    return {
        "g6": g6,
        "order": n,
        "sideBitmask": info["sideBitmask"],
        "badEdges": [list(bad_edge) for bad_edge in info["M"]],
        "familySizes": list(family_sizes),
        "rowChoices": list(choice),
        "rows": [list(row) for row in rows],
        "obligationScore": score,
        "bestOneRowScore": best_one,
        "bestTwoRowScore": best_two,
        "matchingFailure": detail,
    }


def evaluate_cut(g6: str, n: int, info, falsifier_limit: int):
    """Classify every coherent row tuple for one eligible maximum cut."""
    families = shortest_row_families(info)
    family_sizes = tuple(len(family) for family in families)
    choices = list(product(*(range(size) for size in family_sizes)))
    scores = {}
    failures = []

    for choice in choices:
        rows = tuple(
            families[index][row_index]
            for index, row_index in enumerate(choice)
        )
        score = obligation_score(n, info, rows)
        assert isinstance(score, int)
        scores[choice] = score
        kind, returned_g6, detail = evaluate_rows(
            g6, n, info, rows, "row-reserved"
        )
        assert returned_g6 == g6
        if kind == "fail":
            failures.append((choice, rows, score, detail))
        else:
            assert kind == "pass"

    one_descent = 0
    only_two_descent = 0
    no_descent = 0
    first_falsifiers = []
    for choice, rows, score, detail in failures:
        best_one, best_two = minimum_neighbor_scores(
            choice, family_sizes, scores
        )
        if best_one is not None and best_one < score:
            one_descent += 1
        elif best_two is not None and best_two < score:
            only_two_descent += 1
        else:
            no_descent += 1
            if len(first_falsifiers) < falsifier_limit:
                first_falsifiers.append(falsifier_record(
                    g6,
                    n,
                    info,
                    family_sizes,
                    choice,
                    rows,
                    score,
                    best_one,
                    best_two,
                    detail,
                ))

    assert len(failures) == one_descent + only_two_descent + no_descent
    return {
        "totalTuples": len(choices),
        "failingTuples": len(failures),
        "failingWithOneRowDescent": one_descent,
        "failingWithOnlyTwoRowDescent": only_two_descent,
        "failingWithNoAtMostTwoDescent": no_descent,
    }, first_falsifiers


def evaluate_graph(g6: str, falsifier_limit: int):
    """Enumerate every canonical B-connected maximum cut of one graph."""
    n, graph_edges = dec(g6)
    adjacency = [set() for _ in range(n)]
    for u, v in graph_edges:
        adjacency[u].add(v)
        adjacency[v].add(u)

    stats = empty_stats()
    stats["graphs"] = 1
    status = graph_status(n, adjacency)
    if status != "connectedTriangleFree":
        return {
            "g6": g6,
            "order": n,
            "graphStatus": status,
            **stats,
            "firstFalsifiers": [],
        }
    stats["connectedTriangleFreeGraphs"] = 1

    canonical_cuts = {}
    for raw_side in maxcut_all(n, adjacency):
        mask, side = canonical_side(raw_side)
        canonical_cuts.setdefault(mask, side)
    stats["maximumCuts"] = len(canonical_cuts)

    first_falsifiers = []
    for side_bitmask, side in sorted(canonical_cuts.items()):
        if not Bconn(n, adjacency, side):
            continue
        stats["bConnectedMaximumCuts"] += 1
        cut_status, info = literal_cut_info(
            n, adjacency, side, side_bitmask
        )
        if cut_status == "emptyBadSet":
            continue
        stats["bConnectedCutsWithBadEdges"] += 1
        if cut_status == "notAll5":
            continue
        assert cut_status == "eligible" and info is not None
        stats["eligibleCuts"] += 1
        cut_stats, cut_falsifiers = evaluate_cut(
            g6, n, info, falsifier_limit
        )
        add_stats(stats, cut_stats)
        remaining = falsifier_limit - len(first_falsifiers)
        if remaining > 0:
            first_falsifiers.extend(cut_falsifiers[:remaining])

    stats["graphsWithEligibleCuts"] = int(stats["eligibleCuts"] > 0)
    return {
        "g6": g6,
        "order": n,
        "graphStatus": status,
        **stats,
        "firstFalsifiers": first_falsifiers,
    }


def positive_int(value: str) -> int:
    parsed = int(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("must be a positive integer")
    return parsed


def nonnegative_int(value: str) -> int:
    parsed = int(value)
    if parsed < 0:
        raise argparse.ArgumentTypeError("must be a nonnegative integer")
    return parsed


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--min-order", type=positive_int, default=5)
    parser.add_argument("--max-order", type=positive_int, default=10)
    parser.add_argument(
        "--workers",
        type=positive_int,
        default=min(61, os.cpu_count() or 1),
    )
    parser.add_argument(
        "--max-falsifiers",
        type=nonnegative_int,
        default=20,
        help="maximum number of first no-descent witnesses to include",
    )
    parser.add_argument(
        "--graph6",
        action="append",
        default=[],
        help="test a connected triangle-free graph6 fixture; repeatable",
    )
    args = parser.parse_args()
    if args.min_order > args.max_order:
        parser.error("--min-order must not exceed --max-order")
    if args.workers > 61:
        parser.error("--workers must not exceed 61")
    return args


def main() -> None:
    args = parse_args()
    if args.graph6:
        graph6 = args.graph6
        generated = dict(sorted(Counter(dec(g6)[0] for g6 in graph6).items()))
    else:
        graph6, generated = graph6_for_orders(
            args.min_order, args.max_order
        )

    aggregate = empty_stats()
    by_order = {}
    graph_statuses = Counter()
    first_falsifiers = []

    if args.workers == 1:
        results = map(evaluate_graph, graph6, repeat(args.max_falsifiers))
        pool = None
    else:
        pool = ProcessPoolExecutor(max_workers=args.workers)
        results = pool.map(
            evaluate_graph,
            graph6,
            repeat(args.max_falsifiers),
            chunksize=4,
        )

    try:
        for result in results:
            graph_statuses[result["graphStatus"]] += 1
            order_stats = by_order.setdefault(result["order"], empty_stats())
            add_stats(aggregate, result)
            add_stats(order_stats, result)
            remaining = args.max_falsifiers - len(first_falsifiers)
            if remaining > 0:
                first_falsifiers.extend(
                    result["firstFalsifiers"][:remaining]
                )
    finally:
        if pool is not None:
            pool.shutdown()

    payload = {
        "orders": [args.min_order, args.max_order],
        "workers": args.workers,
        "fixtureMode": bool(args.graph6),
        "generatedByOrder": {
            str(order): count for order, count in sorted(generated.items())
        },
        "graphStatus": dict(sorted(graph_statuses.items())),
        "cutIdConvention": "sideBitmask=sum(side[v]*2^v),min(complements)",
        **aggregate,
        "byOrder": {
            str(order): stats for order, stats in sorted(by_order.items())
        },
        "firstFalsifiersLimit": args.max_falsifiers,
        "firstFalsifiersTruncated": (
            aggregate["failingWithNoAtMostTwoDescent"]
            > len(first_falsifiers)
        ),
        "firstFalsifiers": first_falsifiers,
    }
    print(json.dumps(payload, sort_keys=True, separators=(",", ":")))


if __name__ == "__main__":
    main()
