import Erdos23Delta0.Gamma.MinimumDemandCollisionHall

/-!
# Collision Hall reduction to owner-saturated shores

The source relation for a collision half depends on the half only through its
owner.  Consequently, an arbitrary demand shore can be enlarged to all
demands having one of its owners without changing the source neighborhood.
Thus the full collision Hall condition is equivalent to checking only these
owner-saturated shores.
-/

namespace Erdos23Delta0
namespace Gamma
namespace CanonicalCollisionHall

open CertGraph
open MinimumDemandRowSelection

/-- All collision demands whose owner lies in `A`. -/
def ownerDemandSet {G : GraphData} {bads : List BadEdgeData}
    {omega : RowChoice bads} (A : Finset (Fin G.n)) :
    Finset (CollisionHalf G omega) :=
  Finset.univ.filter fun d => d.owner ∈ A

/-- All free sources available to at least one demand in the owner-saturated
shore generated by `A`. -/
def ownerSourceSet (G : GraphData) (c : CutData)
    {bads : List BadEdgeData} {omega : RowChoice bads}
    (A : Finset (Fin G.n)) : Finset (FreeHalf G omega) :=
  Finset.univ.filter fun s =>
    ∃ d ∈ ownerDemandSet (G := G) (omega := omega) A,
      Available G c d s

/-- Hall inequalities restricted to owner-saturated collision shores. -/
def OwnerHallCondition (G : GraphData) (c : CutData)
    {bads : List BadEdgeData} (omega : RowChoice bads) : Prop :=
  ∀ A : Finset (Fin G.n),
    (ownerDemandSet (G := G) (omega := omega) A).card ≤
      (ownerSourceSet G c (omega := omega) A).card

/-- The owner image of an arbitrary collision-demand shore. -/
def demandOwners {G : GraphData} {bads : List BadEdgeData}
    {omega : RowChoice bads} (D : Finset (CollisionHalf G omega)) :
    Finset (Fin G.n) :=
  D.image fun d => d.owner

theorem mem_demandOwners_iff
    {G : GraphData} {bads : List BadEdgeData}
    {omega : RowChoice bads} {D : Finset (CollisionHalf G omega)}
    {owner : Fin G.n} :
    owner ∈ demandOwners (G := G) (omega := omega) D ↔
      ∃ d ∈ D, d.owner = owner := by
  simp [demandOwners]

/-- `Available` depends on a collision demand only through its owner. -/
theorem available_iff_of_owner_eq
    {G : GraphData} {c : CutData} {bads : List BadEdgeData}
    {omega : RowChoice bads} {d e : CollisionHalf G omega}
    (howner : d.owner = e.owner) (s : FreeHalf G omega) :
    Available G c d s ↔ Available G c e s := by
  simp only [Available, Eligible, SameOwner, RowCompanion, howner]

/-- Every shore is contained in the owner-saturated shore generated by its
owner image. -/
theorem demand_subset_ownerSaturation
    {G : GraphData} {bads : List BadEdgeData}
    {omega : RowChoice bads} (D : Finset (CollisionHalf G omega)) :
    D ⊆ ownerDemandSet (G := G) (omega := omega)
      (demandOwners (G := G) (omega := omega) D) := by
  intro d hd
  simp only [ownerDemandSet, Finset.mem_filter, Finset.mem_univ, true_and]
  exact mem_demandOwners_iff.mpr ⟨d, hd, rfl⟩

/-- Saturating a demand shore by its owner image does not change its source
neighborhood. -/
theorem ownerSourceSet_demandOwners
    {G : GraphData} {c : CutData} {bads : List BadEdgeData}
    {omega : RowChoice bads} (D : Finset (CollisionHalf G omega)) :
    ownerSourceSet G c (omega := omega)
        (demandOwners (G := G) (omega := omega) D) =
      (Finset.univ.filter fun s : FreeHalf G omega =>
        ∃ d ∈ D, Available G c d s) := by
  ext s
  simp only [ownerSourceSet, Finset.mem_filter, Finset.mem_univ, true_and]
  constructor
  · rintro ⟨d, hd, havailable⟩
    have howner :
        d.owner ∈ demandOwners (G := G) (omega := omega) D := by
      simpa only [ownerDemandSet, Finset.mem_filter, Finset.mem_univ,
        true_and] using hd
    rcases mem_demandOwners_iff.mp howner with ⟨e, he, heowner⟩
    refine ⟨e, he, ?_⟩
    exact (available_iff_of_owner_eq heowner.symm s).mp havailable
  · rintro ⟨d, hd, havailable⟩
    exact ⟨d, demand_subset_ownerSaturation D hd, havailable⟩

/-- Full Hall implies owner-saturated Hall by specialization. -/
theorem ownerHallCondition_of_collisionHallCondition
    {G : GraphData} {c : CutData} {bads : List BadEdgeData}
    {omega : RowChoice bads}
    (hHall : CollisionHallCondition G c omega) :
    OwnerHallCondition G c omega := by
  intro A
  simpa only [ownerSourceSet] using
    hHall (ownerDemandSet (G := G) (omega := omega) A)

/-- Owner-saturated Hall implies full Hall: enlarge an arbitrary shore to its
owner saturation, use Hall there, and identify the unchanged neighborhood. -/
theorem collisionHallCondition_of_ownerHallCondition
    {G : GraphData} {c : CutData} {bads : List BadEdgeData}
    {omega : RowChoice bads}
    (hHall : OwnerHallCondition G c omega) :
    CollisionHallCondition G c omega := by
  intro D
  calc
    D.card ≤
        (ownerDemandSet (G := G) (omega := omega)
          (demandOwners (G := G) (omega := omega) D)).card :=
      Finset.card_le_card (demand_subset_ownerSaturation D)
    _ ≤
        (ownerSourceSet G c (omega := omega)
          (demandOwners (G := G) (omega := omega) D)).card :=
      hHall (demandOwners (G := G) (omega := omega) D)
    _ =
        (Finset.univ.filter fun s : FreeHalf G omega =>
          ∃ d ∈ D, Available G c d s).card :=
      congrArg Finset.card (ownerSourceSet_demandOwners D)

/-- Collision Hall is equivalent to Hall on owner-saturated demand shores. -/
theorem collisionHallCondition_iff_ownerHallCondition
    {G : GraphData} {c : CutData} {bads : List BadEdgeData}
    {omega : RowChoice bads} :
    CollisionHallCondition G c omega ↔ OwnerHallCondition G c omega := by
  exact ⟨ownerHallCondition_of_collisionHallCondition,
    collisionHallCondition_of_ownerHallCondition⟩

/-- The exact number of collision-half demands owned by vertices in `A`. -/
def ownerDemandUnits {G : GraphData} {bads : List BadEdgeData}
    (omega : RowChoice bads) (A : Finset (Fin G.n)) : Nat :=
  ∑ v ∈ A, ∑ y : Fin G.n,
    2 * (pairCount omega v.1 y.1 - 1)

/-- The dependent fiber of collision halves with a fixed owner. -/
def OwnerDemandFiber {G : GraphData} {bads : List BadEdgeData}
    (omega : RowChoice bads) (v : Fin G.n) : Type :=
  Σ y : Fin G.n,
    Fin (pairCount omega v.1 y.1 - 1) × Fin 2

instance ownerDemandFiberFintype
    {G : GraphData} {bads : List BadEdgeData}
    (omega : RowChoice bads) (v : Fin G.n) :
    Fintype (OwnerDemandFiber (G := G) omega v) := by
  unfold OwnerDemandFiber
  infer_instance

/-- A filtered collision half is exactly an owner in `A`, another vertex, a
repeated-pair copy, and one of the two half-slots. -/
def ownerDemandEquiv {G : GraphData} {bads : List BadEdgeData}
    {omega : RowChoice bads} (A : Finset (Fin G.n)) :
    {d : CollisionHalf G omega //
      d ∈ ownerDemandSet (G := G) (omega := omega) A} ≃
      Σ v : {v : Fin G.n // v ∈ A},
        OwnerDemandFiber (G := G) omega v.1 where
  toFun d :=
    ⟨⟨d.1.owner, by
      simpa only [ownerDemandSet, Finset.mem_filter, Finset.mem_univ,
        true_and] using d.2⟩,
      ⟨d.1.other, (d.1.copy, d.1.half)⟩⟩
  invFun x :=
    ⟨{
      owner := x.1.1
      other := x.2.1
      copy := x.2.2.1
      half := x.2.2.2
    }, by
      simp only [ownerDemandSet, Finset.mem_filter, Finset.mem_univ,
        true_and]
      exact x.1.2⟩
  left_inv d := by
    apply Subtype.ext
    rfl
  right_inv x := by
    cases x with
    | mk v fiber =>
      cases v with
      | mk v hv =>
        cases fiber with
        | mk y slots =>
          cases slots
          rfl

theorem card_ownerDemandFiber
    {G : GraphData} {bads : List BadEdgeData}
    (omega : RowChoice bads) (v : Fin G.n) :
    Fintype.card (OwnerDemandFiber (G := G) omega v) =
      ∑ y : Fin G.n, 2 * (pairCount omega v.1 y.1 - 1) := by
  simp [OwnerDemandFiber, Fintype.card_sigma, Fintype.card_prod,
    Fintype.card_fin, Nat.mul_comm]

theorem card_ownerDemandSigma
    {G : GraphData} {bads : List BadEdgeData}
    (omega : RowChoice bads) (A : Finset (Fin G.n)) :
    Fintype.card
        (Σ v : {v : Fin G.n // v ∈ A},
          OwnerDemandFiber (G := G) omega v.1) =
      ownerDemandUnits (G := G) omega A := by
  rw [Fintype.card_sigma]
  simp_rw [card_ownerDemandFiber]
  simpa only [ownerDemandUnits] using
    (Finset.sum_coe_sort A fun v : Fin G.n =>
      ∑ y : Fin G.n, 2 * (pairCount omega v.1 y.1 - 1))

/-- The filtered owner demand shore has exactly the scalar repeated-pair
count prescribed by `ownerDemandUnits`. -/
theorem ownerDemandSet_card_eq_ownerDemandUnits
    {G : GraphData} {bads : List BadEdgeData}
    (omega : RowChoice bads) (A : Finset (Fin G.n)) :
    (ownerDemandSet (G := G) (omega := omega) A).card =
      ownerDemandUnits (G := G) omega A := by
  calc
    (ownerDemandSet (G := G) (omega := omega) A).card =
        Fintype.card ↥(ownerDemandSet (G := G) (omega := omega) A) :=
      (Fintype.card_coe
        (ownerDemandSet (G := G) (omega := omega) A)).symm
    _ = Fintype.card
        (Σ v : {v : Fin G.n // v ∈ A},
          OwnerDemandFiber (G := G) omega v.1) :=
      Fintype.card_congr (ownerDemandEquiv (G := G) (omega := omega) A)
    _ = ownerDemandUnits (G := G) omega A :=
      card_ownerDemandSigma omega A

/-- Scalar name for the owner-source neighborhood cardinality. -/
def ownerSourceUnits (G : GraphData) (c : CutData)
    {bads : List BadEdgeData} {omega : RowChoice bads}
    (A : Finset (Fin G.n)) : Nat :=
  (ownerSourceSet G c (omega := omega) A).card

/-- Owner Hall is exactly the scalar owner-demand/source inequality. -/
theorem ownerHallCondition_iff_ownerUnits
    {G : GraphData} {c : CutData} {bads : List BadEdgeData}
    {omega : RowChoice bads} :
    OwnerHallCondition G c omega ↔
      ∀ A : Finset (Fin G.n),
        ownerDemandUnits (G := G) omega A ≤
          ownerSourceUnits G c (omega := omega) A := by
  simp only [OwnerHallCondition, ownerSourceUnits,
    ownerDemandSet_card_eq_ownerDemandUnits]

#print axioms available_iff_of_owner_eq
#print axioms ownerSourceSet_demandOwners
#print axioms collisionHallCondition_of_ownerHallCondition
#print axioms collisionHallCondition_iff_ownerHallCondition
#print axioms ownerDemandSet_card_eq_ownerDemandUnits
#print axioms ownerHallCondition_iff_ownerUnits

end CanonicalCollisionHall
end Gamma
end Erdos23Delta0
