#!/usr/bin/env python3
"""Solver-free Horn characterization of root-specific image implications.

For a fixed cutoff X, let G be the least forward-closed source.  For a hard
root h and nonhard target r, the universal implication

    top(h) notin F(S)  ->  r notin F(S) and top(r) in F(S)

over every forward-closed S containing G is equivalent to:

  (i) top(r) is in G; and
  (ii) for every admissible pair {a,b} generating r, top(h) belongs to
       F(cl(G union {a,b})).

The proof is monotonicity plus the minimal closed source generated by each
pair.  This program reconstructs the exact implication graph and its matching.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from collections import deque
from pathlib import Path


def require(condition: bool, message: object) -> None:
    if not condition:
        raise RuntimeError(message)


def allowed(n: int) -> bool:
    return n >= 2 and n % 3 != 1


def admissible_pairs(n: int) -> tuple[tuple[int, int], ...]:
    out = []
    for a in range(2, math.isqrt(n + 1) + 1):
        if (n + 1) % a:
            continue
        b = (n + 1) // a
        if a < b and allowed(a) and allowed(b):
            out.append((a, b))
    return tuple(out)


class Model:
    def __init__(self, cutoff: int):
        self.cutoff = cutoff
        self.values = tuple(n for n in range(2, cutoff + 1) if allowed(n))
        self.pairs = {n: admissible_pairs(n) for n in self.values}
        self.generated = self.close({2, 3})
        self.hard = tuple(
            n for n in self.values
            if n % 2 == 0
            and n not in self.generated
            and self.hard_shape(n)
            and self.top(n) not in self.generated
        )
        self.targets = tuple(
            n for n in self.values
            if n % 2 == 0
            and n not in self.generated
            and not self.hard_shape(n)
            and self.top(n) > n
        )

    def hard_shape(self, n: int) -> bool:
        if n % 2 or not self.pairs[n]:
            return False
        if (n + 1) % 3:
            return True
        parent = (n + 1) // 3
        return not (allowed(parent) and parent != 3)

    def top(self, root: int) -> int:
        n = root
        while 2 * n - 1 <= self.cutoff:
            n = 2 * n - 1
        return n

    def close(self, seeds: set[int]) -> set[int]:
        result = set(seeds)
        for n in self.values:
            if any(a in result and b in result for a, b in self.pairs[n]):
                result.add(n)
        return result

    def image(self, source: set[int]) -> set[int]:
        result = {2, 3}
        for n in self.values:
            if any(a in source and b in source for a, b in self.pairs[n]):
                result.add(n)
        return result

    def pair_image(self, pair: tuple[int, int]) -> set[int]:
        return self.image(self.close(self.generated | set(pair)))

    def adjacency(self) -> tuple[dict[int, set[int]], dict[int, dict]]:
        adjacency = {h: set() for h in self.hard}
        target_data: dict[int, dict] = {}
        hard_by_top: dict[int, list[int]] = {}
        for h in self.hard:
            hard_by_top.setdefault(self.top(h), []).append(h)

        for r in self.targets:
            rt = self.top(r)
            if rt not in self.generated:
                target_data[r] = {
                    "top": rt,
                    "grounded_top": False,
                    "pair_count": len(self.pairs[r]),
                    "supported_hard_tops": [],
                }
                continue
            if not self.pairs[r]:
                common_tops = set(hard_by_top)
            else:
                common_tops = set(hard_by_top)
                for pair in self.pairs[r]:
                    common_tops &= self.pair_image(pair)
            for ht in common_tops:
                for h in hard_by_top[ht]:
                    adjacency[h].add(r)
            target_data[r] = {
                "top": rt,
                "grounded_top": True,
                "pair_count": len(self.pairs[r]),
                "supported_hard_tops": sorted(common_tops),
            }
        return adjacency, target_data


def maximum_matching(lefts: tuple[int, ...], adjacency: dict[int, set[int]]) -> dict[int, int]:
    owner: dict[int, int] = {}

    def augment(left: int, seen: set[int]) -> bool:
        for right in sorted(adjacency[left]):
            if right in seen:
                continue
            seen.add(right)
            previous = owner.get(right)
            if previous is None or augment(previous, seen):
                owner[right] = left
                return True
        return False

    for left in lefts:
        augment(left, set())
    return {left: right for right, left in owner.items()}


def hall_deficit(lefts: tuple[int, ...], adjacency: dict[int, set[int]], matching: dict[int, int]) -> dict:
    if len(matching) == len(lefts):
        return {"hard_set": [], "neighbor_set": [], "deficit": 0}
    reverse = {right: left for left, right in matching.items()}
    reached_left = {left for left in lefts if left not in matching}
    reached_right: set[int] = set()
    queue = deque(reached_left)
    while queue:
        left = queue.popleft()
        for right in adjacency[left]:
            if matching.get(left) == right or right in reached_right:
                continue
            reached_right.add(right)
            if right in reverse and reverse[right] not in reached_left:
                reached_left.add(reverse[right])
                queue.append(reverse[right])
    neighbors = set().union(*(adjacency[h] for h in reached_left))
    require(neighbors == reached_right, "alternating-neighborhood mismatch")
    return {
        "hard_set": sorted(reached_left),
        "neighbor_set": sorted(neighbors),
        "deficit": len(reached_left) - len(neighbors),
    }


def solve(cutoff: int) -> dict:
    model = Model(cutoff)
    adjacency, target_data = model.adjacency()
    matching = maximum_matching(model.hard, adjacency)
    common_neighbors = (
        set.intersection(*(set(adjacency[h]) for h in model.hard))
        if model.hard else set()
    )
    nested_pairs = 0
    incomparable_pairs = []
    for i, a in enumerate(model.hard):
        for b in model.hard[i + 1:]:
            if adjacency[a] <= adjacency[b] or adjacency[b] <= adjacency[a]:
                nested_pairs += 1
            else:
                incomparable_pairs.append([a, b])
    return {
        "schema": "C87-horn-implication-v1",
        "cutoff": cutoff,
        "grounded_size": len(model.generated),
        "hard_roots": list(model.hard),
        "target_roots": list(model.targets),
        "edge_count": sum(map(len, adjacency.values())),
        "common_neighbor_count": len(common_neighbors),
        "common_neighbors": sorted(common_neighbors),
        "adjacency": {str(h): sorted(adjacency[h]) for h in model.hard},
        "target_data": {str(r): target_data[r] for r in model.targets},
        "matching": [[h, matching[h]] for h in sorted(matching)],
        "matching_size": len(matching),
        "hall": hall_deficit(model.hard, adjacency, matching),
        "nested_hard_pairs": nested_pairs,
        "incomparable_hard_pairs": incomparable_pairs,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cutoff", type=int, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    result = solve(args.cutoff)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(result, indent=2) + "\n"
    args.output.write_text(text, encoding="utf-8")
    canonical = json.dumps(result, sort_keys=True, separators=(",", ":")).encode()
    print(
        f"X={args.cutoff} hard={len(result['hard_roots'])} "
        f"targets={len(result['target_roots'])} edges={result['edge_count']} "
        f"matching={result['matching_size']} "
        f"incomparable={len(result['incomparable_hard_pairs'])}"
    )
    print("canonical_sha256", hashlib.sha256(canonical).hexdigest().upper())


if __name__ == "__main__":
    main()
