#!/usr/bin/env python3
"""Exact finite-congruence audit for the canonical Erdos #424 F2 ray.

Words use the repository's outermost-first convention for

    L_2(t) = 2t,  L_3(t) = 3t + 1,  L_5(t) = 5t + 3.

For every length through ``--max-relation-length`` this program enumerates
all words, groups them by content and offset, and retains every member of
every non-singleton fiber.  Avoiding the inclusion-minimal members of that
set makes a word an isolated class in the contextual congruence generated by
all enumerated identities.

The second stage searches for a finite closed-word code in the avoidance DFA.
All code words have a fixed length and return to one state.  An exact
coefficient of the resulting content polynomial is therefore a certified
lower bound for isolated congruence classes on an infinite canonical
subsequence.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import math
from collections import defaultdict, deque
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np
from scipy.optimize import minimize


ALPHABET = "235"
LETTER_INDEX = {letter: index for index, letter in enumerate(ALPHABET)}
SHIFT = {"2": 0, "3": 1, "5": 3}
CANONICAL = (15, 10, 6)
Q = 2**15 * 3**10 * 5**6


def word_offset(word: str) -> int:
    value = 0
    for letter in reversed(word):
        value = int(letter) * value + SHIFT[letter]
    return value


def word_counts(word: str) -> tuple[int, int, int]:
    return word.count("2"), word.count("3"), word.count("5")


@dataclass
class RelationLevel:
    length: int
    formal_words: int
    affine_classes: int
    collision_excess: int
    relation_fibers: int
    relation_pairs: int
    relation_side_words: int
    singleton_words: int
    maximum_fiber: int
    new_minimal_sides: int = 0
    accepted_words: int = 0


class PatternAutomaton:
    def __init__(self, patterns: Iterable[str]):
        self.children: list[list[int]] = [[-1, -1, -1]]
        self.failure = [0]
        self.terminal = [False]
        self.label = [""]

        for pattern in patterns:
            state = 0
            for letter in pattern:
                index = LETTER_INDEX[letter]
                target = self.children[state][index]
                if target < 0:
                    target = len(self.children)
                    self.children[state][index] = target
                    self.children.append([-1, -1, -1])
                    self.failure.append(0)
                    self.terminal.append(False)
                    self.label.append(self.label[state] + letter)
                state = target
            self.terminal[state] = True

        self.transitions = [[0, 0, 0] for _ in self.children]
        queue: deque[int] = deque()
        for index in range(3):
            child = self.children[0][index]
            if child < 0:
                self.transitions[0][index] = 0
            else:
                self.transitions[0][index] = child
                queue.append(child)

        while queue:
            state = queue.popleft()
            self.terminal[state] = (
                self.terminal[state] or self.terminal[self.failure[state]]
            )
            for index in range(3):
                child = self.children[state][index]
                if child < 0:
                    self.transitions[state][index] = self.transitions[
                        self.failure[state]
                    ][index]
                else:
                    self.failure[child] = self.transitions[self.failure[state]][
                        index
                    ]
                    self.transitions[state][index] = child
                    queue.append(child)

    def contains_pattern(self, word: str) -> bool:
        state = 0
        for letter in word:
            state = self.transitions[state][LETTER_INDEX[letter]]
            if self.terminal[state]:
                return True
        return False

    def safe_dfa(self) -> tuple[np.ndarray, list[str], int]:
        safe = [
            state for state in range(len(self.children)) if not self.terminal[state]
        ]
        remap = {old: new for new, old in enumerate(safe)}
        transitions = np.full((len(safe), 3), -1, dtype=np.int32)
        for old in safe:
            source = remap[old]
            for index in range(3):
                target = self.transitions[old][index]
                if not self.terminal[target]:
                    transitions[source, index] = remap[target]
        return transitions, [self.label[state] for state in safe], remap[0]


def enumerate_relations(max_length: int):
    minimal_sides: list[str] = []
    levels: list[RelationLevel] = []
    fiber_digest = hashlib.sha256()

    for length in range(1, max_length + 1):
        first: dict[tuple[int, int, int], str] = {}
        collided: dict[tuple[int, int, int], list[str]] = {}

        for letters in itertools.product(ALPHABET, repeat=length):
            word = "".join(letters)
            counts = word_counts(word)
            key = counts[0], counts[1], word_offset(word)
            representative = first.get(key)
            if representative is None:
                first[key] = word
            else:
                members = collided.get(key)
                if members is None:
                    collided[key] = [representative, word]
                else:
                    members.append(word)

        prior_automaton = PatternAutomaton(minimal_sides)
        participants = [
            word for members in collided.values() for word in members
        ]
        new_sides = sorted(
            word
            for word in participants
            if not prior_automaton.contains_pattern(word)
        )
        minimal_sides.extend(new_sides)

        relation_pairs = 0
        maximum_fiber = 1
        for key in sorted(collided):
            members = collided[key]
            size = len(members)
            relation_pairs += size * (size - 1) // 2
            maximum_fiber = max(maximum_fiber, size)
            a, b, offset = key
            c = length - a - b
            fiber_digest.update(
                (
                    f"{length}:{a},{b},{c}:{offset}:"
                    + ",".join(members)
                    + "\n"
                ).encode("ascii")
            )

        affine_classes = len(first)
        level = RelationLevel(
            length=length,
            formal_words=3**length,
            affine_classes=affine_classes,
            collision_excess=3**length - affine_classes,
            relation_fibers=len(collided),
            relation_pairs=relation_pairs,
            relation_side_words=len(participants),
            singleton_words=affine_classes - len(collided),
            maximum_fiber=maximum_fiber,
            new_minimal_sides=len(new_sides),
        )
        levels.append(level)

    return levels, minimal_sides, fiber_digest.hexdigest()


def validate_singletons(
    transitions: np.ndarray, root: int, levels: list[RelationLevel]
) -> None:
    current = [0] * len(transitions)
    current[root] = 1
    for level in levels:
        following = [0] * len(transitions)
        for state, multiplicity in enumerate(current):
            if not multiplicity:
                continue
            for index in range(3):
                target = int(transitions[state, index])
                if target >= 0:
                    following[target] += multiplicity
        current = following
        level.accepted_words = sum(current)
        if level.accepted_words != level.singleton_words:
            raise AssertionError(
                f"length {level.length}: avoidance accepts "
                f"{level.accepted_words}, singleton census is "
                f"{level.singleton_words}"
            )


def apply_right(
    transitions: np.ndarray, weights: np.ndarray, vector: np.ndarray
) -> np.ndarray:
    result = np.zeros_like(vector)
    for index in range(3):
        targets = transitions[:, index]
        valid = targets >= 0
        result[valid] += weights[index] * vector[targets[valid]]
    return result


def apply_left(
    transitions: np.ndarray, weights: np.ndarray, vector: np.ndarray
) -> np.ndarray:
    result = np.zeros_like(vector)
    for index in range(3):
        targets = transitions[:, index]
        valid = targets >= 0
        np.add.at(result, targets[valid], weights[index] * vector[valid])
    return result


def perron(
    transitions: np.ndarray, theta: np.ndarray, iterations: int = 2000
):
    weights = np.array([1.0, math.exp(theta[0]), math.exp(theta[1])])
    right = np.ones(len(transitions))
    left = np.ones(len(transitions))
    for _ in range(iterations):
        following_right = apply_right(transitions, weights, right)
        following_left = apply_left(transitions, weights, left)
        following_right /= np.max(following_right)
        following_left /= np.max(following_left)
        error = max(
            float(np.max(np.abs(following_right - right))),
            float(np.max(np.abs(following_left - left))),
        )
        right, left = following_right, following_left
        if error < 1e-13:
            break
    image = apply_right(transitions, weights, right)
    eigenvalue = float(np.dot(left, image) / np.dot(left, right))
    return eigenvalue, left, right


def canonical_pressure(transitions: np.ndarray):
    cache: dict[tuple[float, float], float] = {}

    def objective(theta: np.ndarray) -> float:
        key = float(theta[0]), float(theta[1])
        if key not in cache:
            eigenvalue, _, _ = perron(transitions, theta, iterations=800)
            cache[key] = (
                31 * math.log(eigenvalue)
                - CANONICAL[1] * theta[0]
                - CANONICAL[2] * theta[1]
            )
        return cache[key]

    initial = np.array(
        [math.log(CANONICAL[1] / CANONICAL[0]), math.log(CANONICAL[2] / CANONICAL[0])]
    )
    result = minimize(
        objective,
        initial,
        method="Nelder-Mead",
        options={"maxiter": 180, "xatol": 1e-10, "fatol": 1e-11},
    )
    eigenvalue, left, right = perron(transitions, result.x, iterations=4000)
    base = math.exp(
        31 * math.log(eigenvalue)
        - CANONICAL[1] * result.x[0]
        - CANONICAL[2] * result.x[1]
    )
    centrality = left * right
    order = np.argsort(-centrality)
    return {
        "success": bool(result.success),
        "message": str(result.message),
        "theta_3": float(result.x[0]),
        "theta_5": float(result.x[1]),
        "lambda": eigenvalue,
        "canonical_base_per_k": base,
        "ratio_to_Q": base / Q,
        "iterations": int(result.nit),
        "central_states": [int(state) for state in order[:20]],
    }


def token_polynomial(
    transitions: np.ndarray,
    root: int,
    reset_index: int,
    token_length: int,
):
    start = int(transitions[root, reset_index])
    if start < 0:
        return start, {}, []
    internal_length = token_length - 1
    current: dict[tuple[int, int, int], int] = {(start, 0, 0): 1}
    layer_sizes = [1]
    for _ in range(internal_length):
        following: dict[tuple[int, int, int], int] = defaultdict(int)
        for (state, twos, threes), multiplicity in current.items():
            for index in range(3):
                target = int(transitions[state, index])
                if target < 0:
                    continue
                following[
                    (
                        target,
                        twos + (index == 0),
                        threes + (index == 1),
                    )
                ] += multiplicity
        current = following
        layer_sizes.append(len(current))

    polynomial: dict[tuple[int, int, int], int] = defaultdict(int)
    for (state, twos, threes), multiplicity in current.items():
        if int(transitions[state, reset_index]) != start:
            continue
        counts = [twos, threes, internal_length - twos - threes]
        counts[reset_index] += 1
        polynomial[tuple(counts)] += multiplicity
    return start, dict(polynomial), layer_sizes


def macro_coefficient(
    polynomial: dict[tuple[int, int, int], int], token_length: int
):
    factors = 31
    target = tuple(value * token_length for value in CANONICAL)
    current: dict[tuple[int, int], int] = {(0, 0): 1}
    layer_sizes = [1]
    types = sorted(polynomial.items())
    for used in range(factors):
        following: dict[tuple[int, int], int] = defaultdict(int)
        next_length = (used + 1) * token_length
        remaining = (factors - used - 1) * token_length
        for (twos, threes), multiplicity in current.items():
            for (da, db, dc), choices in types:
                a = twos + da
                b = threes + db
                c = next_length - a - b
                if a > target[0] or b > target[1] or c > target[2]:
                    continue
                if a + remaining < target[0]:
                    continue
                if b + remaining < target[1]:
                    continue
                if c + remaining < target[2]:
                    continue
                following[(a, b)] += multiplicity * choices
        current = following
        layer_sizes.append(len(current))
    coefficient = current.get((target[0], target[1]), 0)
    threshold = Q**token_length
    return {
        "canonical_k": token_length,
        "token_factors": factors,
        "target_counts": list(target),
        "coefficient": str(coefficient),
        "Q_power": str(threshold),
        "difference": str(coefficient - threshold),
        "exceeds_Q_power": coefficient > threshold,
        "log_ratio": (
            math.log(coefficient) - token_length * math.log(Q)
            if coefficient
            else None
        ),
        "coefficient_dp_layer_sizes": layer_sizes,
    }


def digest_strings(strings: Iterable[str]) -> str:
    digest = hashlib.sha256()
    for value in strings:
        digest.update(value.encode("ascii") + b"\n")
    return digest.hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--max-relation-length", type=int, default=14)
    parser.add_argument("--token-length", type=int, default=15)
    parser.add_argument("--reset-letters", default="235")
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    if not 1 <= args.max_relation_length <= 15:
        raise SystemExit("max relation length must lie in [1,15]")
    if args.token_length < 2:
        raise SystemExit("token length must be at least 2")
    if any(letter not in ALPHABET for letter in args.reset_letters):
        raise SystemExit("reset letters must come from 235")

    levels, minimal_sides, fiber_sha256 = enumerate_relations(
        args.max_relation_length
    )
    automaton = PatternAutomaton(minimal_sides)
    transitions, labels, root = automaton.safe_dfa()
    validate_singletons(transitions, root, levels)
    pressure = canonical_pressure(transitions)

    reset_results = []
    for reset_letter in args.reset_letters:
        reset_index = LETTER_INDEX[reset_letter]
        start, polynomial, layer_sizes = token_polynomial(
            transitions, root, reset_index, args.token_length
        )
        macro = macro_coefficient(polynomial, args.token_length)
        reset_results.append(
            {
                "reset_letter": reset_letter,
                "start_state": start,
                "start_label": labels[start] if start >= 0 else None,
                "token_length": args.token_length,
                "token_words": sum(polynomial.values()),
                "token_content_types": len(polynomial),
                "token_polynomial": [
                    {"counts": list(counts), "multiplicity": multiplicity}
                    for counts, multiplicity in sorted(polynomial.items())
                ],
                "token_dp_layer_sizes": layer_sizes,
                "macro": macro,
            }
        )

    payload = {
        "schema_version": 1,
        "script_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        "orientation": "outermost-first",
        "maps": {"2": "2t", "3": "3t+1", "5": "5t+3"},
        "canonical_counts": list(CANONICAL),
        "Q": Q,
        "max_relation_length": args.max_relation_length,
        "relation_levels": [vars(level) for level in levels],
        "relation_fibers_sha256": fiber_sha256,
        "minimal_relation_sides": len(minimal_sides),
        "minimal_sides_sha256": digest_strings(minimal_sides),
        "minimal_sides": minimal_sides,
        "automaton": {
            "trie_states": len(automaton.children),
            "safe_states": len(transitions),
            "root_state": root,
        },
        "numeric_pressure": pressure,
        "reset_codes": reset_results,
    }
    rendered = json.dumps(payload, indent=2, sort_keys=True)
    print(rendered)
    if args.output is not None:
        args.output.write_text(rendered + "\n", encoding="ascii")


if __name__ == "__main__":
    main()
