#include <bits/stdc++.h>
#include <boost/multiprecision/cpp_int.hpp>
using namespace std; using boost::multiprecision::cpp_int;
struct Val{uint32_t off;}; vector<vector<cpp_int>> sets; uint64_t states=0,hits=0; mt19937_64 rng(3072026); chrono::steady_clock::time_point ST; int LIM=0; bool timeout(){return chrono::duration_cast<chrono::seconds>(chrono::steady_clock::now()-ST).count()>=LIM;}
string s(const cpp_int& x){ return x.convert_to<string>(); }
string key(const cpp_int&a,const cpp_int&b){ return s(a)+"#"+s(b); }
cpp_int gcd_big(cpp_int a, cpp_int b){ while(b!=0){ cpp_int r=a%b; a=b; b=r; } return a<0?-a:a; }
void emit(vector<cpp_int>P,vector<cpp_int>Q){auto D=[](auto&S){cpp_int r=1;for(auto x:S)r*=x;return r;};auto N=[&](auto&S){cpp_int d=D(S),n=0;for(auto x:S)n+=d/x;return n;};cout<<"WITNESS_FOUND:\nP:";for(auto x:P)cout<<" "<<s(x);cout<<"\nDp: "<<s(D(P))<<"\nNp: "<<s(N(P))<<"\nQ:";for(auto x:Q)cout<<" "<<s(x);cout<<"\nDq: "<<s(D(Q))<<"\nNq: "<<s(N(Q))<<"\n";exit(0);} 
void proc(vector<cpp_int>const&g,const cpp_int&D,unordered_map<string,Val>&mp){if(g.size()<2)return;cpp_int N=0;for(auto &x:g)N+=D/x;if(N<=1)return;if(gcd_big(N,D)!=1)return;states++;string rk=key(N,D);auto it=mp.find(rk);if(it!=mp.end()){hits++;emit(g,sets[it->second.off]);}string k=key(D,N);if(!mp.contains(k)){uint32_t off=sets.size();sets.push_back(g);mp.emplace(k,Val{off});}}
void gen(int i,vector<cpp_int>&b,vector<cpp_int>&g,const cpp_int&D,unordered_map<string,Val>&mp){if(timeout())return;if(i==(int)b.size()){proc(g,D,mp);return;}cpp_int x=b[i];for(size_t j=0;j<g.size();j++){g[j]*=x;gen(i+1,b,g,D,mp);g[j]/=x;}g.push_back(x);gen(i+1,b,g,D,mp);g.pop_back();}
int main(int argc,char**argv){int seconds=argc>1?atoi(argv[1]):900;int samples=argc>2?atoi(argv[2]):200000;string boundStr=argc>3?argv[3]:"1000000000000000000000000000000";cpp_int bound(boundStr);vector<int> primes={2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,101,103,107,109,113};vector<cpp_int> base;for(int p:primes){cpp_int pp=p;for(int e=1;e<=12 && pp<=bound;e++,pp*=p)base.push_back(pp);}unordered_map<string,Val>mp;mp.reserve(5000000);sets.reserve(5000000);auto st=chrono::steady_clock::now();ST=chrono::steady_clock::now(); LIM=seconds; uniform_int_distribution<int> rdist(6,12);for(int sample=0;sample<samples && chrono::duration_cast<chrono::seconds>(chrono::steady_clock::now()-st).count()<seconds;sample++){shuffle(base.begin(),base.end(),rng);int r=rdist(rng);vector<cpp_int>b;cpp_int D=1;for(auto &x:base){if((int)b.size()>=r)break;if(D*x>bound)continue;b.push_back(x);D*=x;}if(b.size()<3)continue;sort(b.begin(),b.end());vector<cpp_int>g;gen(0,b,g,D,mp);}cout<<"NO_WITNESS_UP_TO:\nmethod: state-pair D/N search\nD_MAX: big_block_product_bound_"<<boundStr<<"\nstates_generated: "<<states<<"\nreciprocal_hits: "<<hits<<"\nnext_phase: continue big-int random sampled many-block D search\n";}

