#include <bits/stdc++.h>
using namespace std; using u64=uint64_t; using u128=__uint128_t;
struct K{u64 a,b;}; struct H{size_t operator()(K const&k)const noexcept{u64 x=k.a*11995408973635179863ULL^k.b*10150724397891781847ULL;x^=x>>30;x*=0xbf58476d1ce4e5b9ULL;x^=x>>27;return x;}}; struct E{bool operator()(K const&x,K const&y)const noexcept{return x.a==y.a&&x.b==y.b;}};
vector<vector<u64>> sets; uint64_t states=0,hits=0,Dcount=0; chrono::steady_clock::time_point st; int lim=0; u64 done=0; bool timeout(){return chrono::duration_cast<chrono::seconds>(chrono::steady_clock::now()-st).count()>=lim;} string s128(u128 x){if(!x)return"0";string s;while(x){s.push_back('0'+x%10);x/=10;}reverse(s.begin(),s.end());return s;}
void emit(vector<u64>P,vector<u64>Q){auto D=[](auto&S){u128 r=1;for(auto x:S)r*=x;return r;};auto N=[&](auto&S){u128 d=D(S),n=0;for(auto x:S)n+=d/x;return n;};cout<<"WITNESS_FOUND:\nP:";for(auto x:P)cout<<" "<<x;cout<<"\nDp: "<<s128(D(P))<<"\nNp: "<<s128(N(P))<<"\nQ:";for(auto x:Q)cout<<" "<<x;cout<<"\nDq: "<<s128(D(Q))<<"\nNq: "<<s128(N(Q))<<"\n";exit(0);} 
void proc(vector<u64>const&g,u64 D,unordered_map<K,uint32_t,H,E>&mp){if(g.size()<2)return;u128 N=0;for(auto x:g)N+=(u128)D/x;if(N<=1||N>numeric_limits<u64>::max())return;u64 n=(u64)N;if(gcd(D,n)!=1)return;states++;auto it=mp.find({n,D});if(it!=mp.end()){hits++;emit(g,sets[it->second]);}if(!mp.contains({D,n})){uint32_t off=sets.size();sets.push_back(g);mp.emplace(K{D,n},off);}}
void genpart(int i,vector<u64>&b,vector<u64>&g,u64 D,unordered_map<K,uint32_t,H,E>&mp){if(i==(int)b.size()){proc(g,D,mp);return;}u64 x=b[i];for(size_t j=0;j<g.size();j++){g[j]*=x;genpart(i+1,b,g,D,mp);g[j]/=x;if(timeout())return;}g.push_back(x);genpart(i+1,b,g,D,mp);g.pop_back();}
vector<int> primes(int n){vector<int>p;vector<char>c(n+1);for(int i=2;i<=n;i++)if(!c[i]){p.push_back(i);if(1LL*i*i<=n)for(long long j=1LL*i*i;j<=n;j+=i)c[j]=1;}return p;}
void recD(vector<int>&ps,int idx,u64 D,vector<u64>&blocks,u64 DMAX,unordered_map<K,uint32_t,H,E>&mp){if(timeout())return;if(blocks.size()>=6){Dcount++;done=max(done,D);vector<u64>g;genpart(0,blocks,g,D,mp);}if(idx==(int)ps.size())return;for(int i=idx;i<(int)ps.size();i++){u64 p=ps[i]; if(D>DMAX/p) break; u64 pp=p; while(D<=DMAX/pp){blocks.push_back(pp);recD(ps,i+1,D*pp,blocks,DMAX,mp);blocks.pop_back(); if(pp>DMAX/p)break; pp*=p;} }}
int main(int argc,char**argv){u64 DMAX=argc>1?strtoull(argv[1],0,10):1000000000ULL;lim=argc>2?atoi(argv[2]):900;auto ps=primes(100000);unordered_map<K,uint32_t,H,E>mp;mp.reserve(50000000);sets.reserve(50000000);st=chrono::steady_clock::now();vector<u64>b;recD(ps,0,1,b,DMAX,mp);cout<<"NO_WITNESS_UP_TO:\nmethod: state-pair D/N search\nD_MAX: "<<done<<"\nstates_generated: "<<states<<"\nreciprocal_hits: "<<hits<<"\nnext_phase: continue prioritized exact D generation\n";}
