#include <bits/stdc++.h>
using namespace std; using u64=uint64_t; using u128=__uint128_t;
struct PairKey{u64 a,b;}; struct Hash{size_t operator()(PairKey const&k)const noexcept{u64 x=k.a*11995408973635179863ULL ^ k.b*10150724397891781847ULL; x^=x>>30; x*=0xbf58476d1ce4e5b9ULL; x^=x>>27; return x;}}; struct Eq{bool operator()(PairKey const&x,PairKey const&y)const noexcept{return x.a==y.a&&x.b==y.b;}};
struct Val{uint32_t off;}; vector<vector<u64>> sets; uint64_t states=0,hits=0; chrono::steady_clock::time_point st; int lim=0;
bool timeout(){return lim>0&&chrono::duration_cast<chrono::seconds>(chrono::steady_clock::now()-st).count()>=lim;} string s128(u128 x){if(!x)return"0"; string s; while(x){s.push_back('0'+x%10);x/=10;} reverse(s.begin(),s.end());return s;}
void emit(vector<u64>P,vector<u64>Q){auto D=[](vector<u64>const&S){u128 r=1;for(auto x:S)r*=x;return r;};auto N=[&](vector<u64>const&S){u128 d=D(S),n=0;for(auto x:S)n+=d/x;return n;};cout<<"WITNESS_FOUND:\nP:";for(auto x:P)cout<<" "<<x;cout<<"\nDp: "<<s128(D(P))<<"\nNp: "<<s128(N(P))<<"\nQ:";for(auto x:Q)cout<<" "<<x;cout<<"\nDq: "<<s128(D(Q))<<"\nNq: "<<s128(N(Q))<<"\n";exit(0);} 
void process(vector<u64>const&g,u64 D,unordered_map<PairKey,Val,Hash,Eq>&mp){if(g.size()<2)return;u128 N=0;for(u64 x:g)N+=(u128)D/x;if(N<=1||N>numeric_limits<u64>::max())return;u64 n=(u64)N;if(gcd(D,n)!=1)return;states++;auto it=mp.find({n,D});if(it!=mp.end()){hits++;emit(g,sets[it->second.off]);} if(!mp.contains({D,n})){uint32_t off=sets.size();sets.push_back(g);mp.emplace(PairKey{D,n},Val{off});}}
void gen(int idx,vector<u64>const&b,vector<u64>&g,u64 D,unordered_map<PairKey,Val,Hash,Eq>&mp){if(idx==(int)b.size()){process(g,D,mp);return;}u64 x=b[idx];for(size_t i=0;i<g.size();i++){g[i]*=x;gen(idx+1,b,g,D,mp);g[i]/=x;if(timeout())return;}g.push_back(x);gen(idx+1,b,g,D,mp);g.pop_back();}
vector<int> primes(int n){vector<int>p;vector<char>c(n+1);for(int i=2;i<=n;i++)if(!c[i]){p.push_back(i);if(1LL*i*i<=n)for(long long j=1LL*i*i;j<=n;j+=i)c[j]=1;}return p;}
void rec(vector<u64>const&blocks,int idx,int rmax,u128 prod,u128 bound,vector<u64>&chosen,unordered_map<PairKey,Val,Hash,Eq>&mp){if(timeout())return;if(chosen.size()>=3&&prod<=numeric_limits<u64>::max()){vector<u64>g;gen(0,chosen,g,(u64)prod,mp);}if((int)chosen.size()>=rmax)return;for(int i=idx;i<(int)blocks.size();i++){u128 p2=prod*blocks[i];if(p2>bound)continue;chosen.push_back(blocks[i]);rec(blocks,i+1,rmax,p2,bound,chosen,mp);chosen.pop_back();}}
int main(int argc,char**argv){int pmax=argc>1?atoi(argv[1]):47,rmax=argc>2?atoi(argv[2]):14; unsigned long long bound=strtoull(argc>3?argv[3]:"10000000000000000000",0,10); lim=argc>4?atoi(argv[4]):900; st=chrono::steady_clock::now();vector<u64>blocks;for(int p:primes(pmax)){u128 pp=p;while(pp<=bound){blocks.push_back((u64)pp);pp*=p;}}sort(blocks.begin(),blocks.end());unordered_map<PairKey,Val,Hash,Eq>mp;mp.reserve(20000000);sets.reserve(20000000);vector<u64>ch;rec(blocks,0,rmax,1,bound,ch,mp);cout<<"NO_WITNESS_UP_TO:\nmethod: state-pair D/N search\nD_MAX: block_product_bound_"<<bound<<"\nstates_generated: "<<states<<"\nreciprocal_hits: "<<hits<<"\nnext_phase: random sampled many-block D search\n";}
