#include <bits/stdc++.h>
using namespace std; using u64=uint64_t; using u128=__uint128_t;
struct K{u64 a,b;}; struct H{size_t operator()(K const&k)const noexcept{u64 x=k.a*11995408973635179863ULL^k.b*10150724397891781847ULL;x^=x>>30;x*=0xbf58476d1ce4e5b9ULL;x^=x>>27;return x;}}; struct E{bool operator()(K const&x,K const&y)const noexcept{return x.a==y.a&&x.b==y.b;}};
vector<int> spf; vector<vector<u64>> sets; uint64_t states=0,hits=0,done=0; chrono::steady_clock::time_point st; int lim;
string s128(u128 x){if(!x)return"0"; string s; while(x){s.push_back('0'+x%10);x/=10;} reverse(s.begin(),s.end()); return s;} bool timeout(){return chrono::duration_cast<chrono::seconds>(chrono::steady_clock::now()-st).count()>=lim;}
void emit(vector<u64>P,vector<u64>Q){auto D=[](auto&S){u128 r=1;for(auto x:S)r*=x;return r;};auto N=[&](auto&S){u128 d=D(S),n=0;for(auto x:S)n+=d/x;return n;};cout<<"WITNESS_FOUND:\nP:";for(auto x:P)cout<<" "<<x;cout<<"\nDp: "<<s128(D(P))<<"\nNp: "<<s128(N(P))<<"\nQ:";for(auto x:Q)cout<<" "<<x;cout<<"\nDq: "<<s128(D(Q))<<"\nNq: "<<s128(N(Q))<<"\n";exit(0);} 
vector<u64> blocks(u64 n){vector<u64>b;while(n>1){u64 p=spf[n],pp=1;while(n%p==0){pp*=p;n/=p;}b.push_back(pp);}return b;}
void proc(vector<u64>const&g,u64 D,unordered_map<K,uint32_t,H,E>&mp){if(g.size()<2)return;u128 N=0;for(auto x:g)N+=(u128)D/x;if(N<=1||N>numeric_limits<u64>::max())return;u64 n=(u64)N;if(gcd(D,n)!=1)return;states++;auto it=mp.find({n,D});if(it!=mp.end()){hits++;emit(g,sets[it->second]);}if(!mp.contains({D,n})){uint32_t off=sets.size();sets.push_back(g);mp.emplace(K{D,n},off);}}
void gen(int i,vector<u64>&b,vector<u64>&g,u64 D,unordered_map<K,uint32_t,H,E>&mp){if(i==(int)b.size()){proc(g,D,mp);return;}u64 x=b[i];for(size_t j=0;j<g.size();j++){g[j]*=x;gen(i+1,b,g,D,mp);g[j]/=x;if(timeout())return;}g.push_back(x);gen(i+1,b,g,D,mp);g.pop_back();}
int main(int argc,char**argv){u64 DMAX=argc>1?strtoull(argv[1],0,10):1000000000ULL;lim=argc>2?atoi(argv[2]):900;spf.assign(DMAX+1,0);for(u64 i=2;i<=DMAX;i++)if(!spf[i]){spf[i]=i;if(i*i<=DMAX)for(u64 j=i*i;j<=DMAX;j+=i)if(!spf[j])spf[j]=i;}unordered_map<K,uint32_t,H,E>mp;mp.reserve(40000000);sets.reserve(40000000);st=chrono::steady_clock::now();for(u64 D=2;D<=DMAX&&!timeout();D++){auto b=blocks(D);if(b.size()<6)continue;vector<u64>g;gen(0,b,g,D,mp);done=D;}cout<<"NO_WITNESS_UP_TO:\nmethod: state-pair D/N search\nD_MAX: "<<done<<"\nstates_generated: "<<states<<"\nreciprocal_hits: "<<hits<<"\nnext_phase: continue prioritized many-prime-factor D search\n";}
