"""Search for a simple D22-orbit description of the rank-22 block-0 support.

This is a numerical identification probe only and calls no conic solver.  The
sealed first-face kernel gives an exact quotient parameter B with
Q = B R B^T.  The exported dual matrix has a stable 22-dimensional range in
the quotient coordinates.  We test whether that range is generated by the
D22 orbit of:

* one degree-three monomial coordinate; or
* a two-term vector with a small rational coefficient.

An apparent match must still be replayed by exact modular/rational algebra.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from collections import defaultdict
from fractions import Fraction
from pathlib import Path

import numpy as np
import scipy.linalg as la


HERE = Path(__file__).resolve().parent
BASE_PATH = HERE / "CODEX_R10_g11_d22_sdp.py"
CANONICAL_PATH = HERE / "CODEX_R10_c5_FACE_REDUCED_SDP_CANONICALIZE.py"
BLOWUP_PATH = HERE / "CODEX_R10_BLOWUP_FACE_data.npz"
DUAL_PATH = HERE / "CODEX_R10_g11_d22_reduced_sdp_scs_dual_numeric.npz"


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def block0_kernel(blowup, order: int) -> np.ndarray:
    rows = []
    for encoded in blowup["kernel_rows_json"]:
        block, row = json.loads(str(encoded))
        if int(block) == 0:
            rows.append([int(value) for value in row])
    matrix = np.asarray(rows, dtype=np.float64)
    if matrix.shape != (132, order):
        raise AssertionError(matrix.shape)
    return matrix


def quotient_parameter(kernel: np.ndarray, free: list[int]) -> np.ndarray:
    order = kernel.shape[1]
    pivot = sorted(set(range(order)) - set(free))
    kp = kernel[:, pivot]
    kf = kernel[:, free]
    if np.linalg.matrix_rank(kp) != len(pivot):
        raise AssertionError("pivot minor is singular")
    output = np.zeros((order, len(free)), dtype=np.float64)
    output[pivot, :] = -la.solve(kp, kf)
    output[free, :] = np.eye(len(free))
    residual = np.max(np.abs(kernel @ output))
    if residual > 1e-10:
        raise AssertionError(residual)
    return output


def raw_block0(dual) -> np.ndarray:
    position = int(np.flatnonzero(dual["psd_block_indices"] == 0)[0])
    order = int(dual["psd_orders"][position])
    offsets = dual["psd_flat_offsets"].astype(np.int64)
    return dual["dual_psd_matrices_flat"][
        int(offsets[position]) : int(offsets[position + 1])
    ].reshape((order, order))


def coordinate_orbits(builder, basis):
    index = {tuple(exponent): i for i, exponent in enumerate(basis)}
    unseen = set(range(len(basis)))
    output = []
    while unseen:
        seed = min(unseen)
        orbit = sorted(
            {
                index[builder.exponent_image(basis[seed], element)]
                for element in builder.GROUP
            }
        )
        output.append(orbit)
        unseen.difference_update(orbit)
    return output


def main() -> None:
    builder = load_module("codex_r10_block0_orbit_base", BASE_PATH)
    canonical = load_module(
        "codex_r10_block0_orbit_canonical", CANONICAL_PATH
    )
    model = builder.build_model()
    blowup = np.load(BLOWUP_PATH, allow_pickle=False)
    dual = np.load(DUAL_PATH, allow_pickle=False)
    basis = model.gram_orbits[0].basis
    free = canonical.free_coordinates(blowup, model)[0]
    quotient = quotient_parameter(block0_kernel(blowup, len(basis)), free)

    matrix = raw_block0(dual)
    eigenvalues, eigenvectors = np.linalg.eigh((matrix + matrix.T) / 2)
    target = eigenvectors[:, -22:]
    projector = target @ target.T
    residual_rows = quotient @ (np.eye(len(free)) - projector)
    row_relative = np.linalg.norm(residual_rows, axis=1) / np.maximum(
        np.linalg.norm(quotient, axis=1), 1e-300
    )

    print(
        "quotient"
        f" shape={quotient.shape}"
        f" denominator_hint=24"
        f" target_gap={eigenvalues[-22] / max(abs(eigenvalues[-23]), 1e-300):.3e}"
    )
    print(
        "coordinate_rows"
        f" best_relative={row_relative.min():.12e}"
        f" best_index={int(np.argmin(row_relative))}"
        f" exponent={tuple(int(v // 2) for v in basis[int(np.argmin(row_relative))])}"
    )

    orbits = coordinate_orbits(builder, basis)
    matches = []
    for orbit in orbits:
        rows = quotient[orbit, :]
        rank = np.linalg.matrix_rank(rows, tol=1e-10)
        outside = np.linalg.norm(rows @ (np.eye(len(free)) - projector))
        relative = outside / max(np.linalg.norm(rows), 1e-300)
        matches.append((relative, rank, orbit))
    for relative, rank, orbit in sorted(matches)[:15]:
        representative = tuple(int(v // 2) for v in basis[orbit[0]])
        print(
            "ORBIT"
            f" rel={relative:.12e}"
            f" size={len(orbit)} rank={rank}"
            f" rep={representative}"
        )

    # Two rows can cancel outside the target only when their residual rows are
    # nearly collinear.  Bucket normalized residuals by a coarse rounded key,
    # including both signs, then check all collisions precisely.
    norms = np.linalg.norm(residual_rows, axis=1)
    normalized = residual_rows / np.maximum(norms[:, None], 1e-300)
    buckets: dict[tuple[int, ...], list[tuple[int, int]]] = defaultdict(list)
    scale = 100
    for index, row in enumerate(normalized):
        # A 132-dimensional random projection to 12 fixed coordinates is
        # enough for candidate bucketing; precise residuals are checked below.
        sample = row[np.linspace(0, len(free) - 1, 12, dtype=int)]
        for sign in (1, -1):
            key = tuple(np.rint(sign * scale * sample).astype(int))
            buckets[key].append((index, sign))

    candidates = []
    seen = set()
    for bucket in buckets.values():
        if len(bucket) < 2:
            continue
        for a_position in range(len(bucket)):
            for b_position in range(a_position + 1, len(bucket)):
                left, left_sign = bucket[a_position]
                right, right_sign = bucket[b_position]
                if left == right:
                    continue
                pair = tuple(sorted((left, right)))
                if pair in seen:
                    continue
                seen.add(pair)
                rl = residual_rows[left]
                rr = residual_rows[right]
                coefficient = -float(rl @ rr) / float(rr @ rr)
                residual = rl + coefficient * rr
                relative = np.linalg.norm(residual) / max(
                    np.linalg.norm(quotient[left])
                    + abs(coefficient) * np.linalg.norm(quotient[right]),
                    1e-300,
                )
                candidates.append((relative, left, right, coefficient))

    print(f"two_term_candidates={len(candidates)}")
    for relative, left, right, coefficient in sorted(candidates)[:30]:
        rational = Fraction(coefficient).limit_denominator(1000)
        print(
            "PAIR"
            f" rel={relative:.12e}"
            f" left={left}:{tuple(int(v // 2) for v in basis[left])}"
            f" right={right}:{tuple(int(v // 2) for v in basis[right])}"
            f" coeff={coefficient:.12g} rational={rational}"
        )


if __name__ == "__main__":
    main()
