# Q2 — Discharging with a GLOBAL term

**Verdict: the mechanism is REFUTED, with an exact witness that also kills every
global term of the suggested kind.** Details, exact rationals and files below.

Everything below is integer / `Fraction` arithmetic. Floating point was used only
inside one exploratory search (`Q2_family.py`), whose answer was later found to be
an artefact of a wrong normalisation and is *not* used for any claim; every claim
here rests on `Q2_ledger.py`, `Q2_finite.cpp`, `Q2_witness.py`, `Q2_wstar*.py`,
`Q2_exhaust.cpp`, all exact.

---

## 0. Notation and the charge normalisation

`G` triangle-free, `N=|V|`. Fix a cut `(X,Y)`; `B` = crossing edges, `M` = mono
edges; `d(v)=d_B(v)+d_M(v)`, `sigma(v)=d_B(v)-d_M(v)`.

**Initial charge.**  `mu(v) := N - (25/2) d_M(v)`.  Then identically

    sum_v mu(v) = N^2 - 25|M|,

so the target `25|M| <= N^2` **is** `sum_v mu(v) >= 0`.  (Verified on every
maximum cut of all 278 maximal triangle-free graphs, `5 <= N <= 12`:
`FAIL-A(charge)` count 0.)

---

## 1. PROVED — the complete switching family (this is the whole supply of
##    max-cut inequalities; nothing else exists)

**Lemma 1 (switching identity).** For every `S ⊆ V`, switching `S` changes the cut by

    Delta(S) = - sum_{u in S} sigma(u) - 2 e_M(S) + 2 e_B(S),

where `e_M(S)`, `e_B(S)` are the mono / crossing edges *inside* `S`.  Hence
`(X,Y)` is a maximum cut **iff**

    (MC_S)     sum_{u in S} sigma(u) + 2 e_M(S)  >=  2 e_B(S)     for all S ⊆ V.

*Proof.* An edge with exactly one end in `S` flips status; one with both ends in
`S` does not.  Mono edges leaving `S` number `sum_{u∈S} d_M(u) − 2e_M(S)`, crossing
edges leaving `S` number `sum_{u∈S} d_B(u) − 2e_B(S)`; subtract. ∎

`S = {v} ∪ T` with `T ⊆ N_B(v)` gives `e_M=0`, `e_B=|T|`, i.e. exactly the accepted
switch-star `sigma(v) >= sum_{a∈T}(2 - sigma(a))`.  **Lemma 1 says the switch-star
family is not one tool among many: `{Delta(S) <= 0}` is the entire content of
"the cut is maximum".**  Any discharging scheme, local or global, must draw its
cut hypotheses from this family (plus facts about `G` alone).

**Lemma 2 (blow-up multilinearity).** In a blow-up `H[a]` the parts are independent
sets, so for a part-respecting cut both `|M|` and `Delta(S)` are **multilinear** in
the counts `s_i = |S ∩ V_i|`.  Consequences, both used as exact certificates:
* `maxcut(H[a])` is attained at a part-respecting cut;
* a part-respecting cut is a maximum cut **iff** `Delta(S) <= 0` for the `2^h`
  part-subsets `S` (corner check — no need to look at partial parts).

**Lemma 3 (the family (\*), new).** For every `v` and every independent
`T ⊆ V ∖ N(v)`, `S = N(v) ⊔ T` has all its internal edges between `N(v)` and `T`
(both are independent), so `(MC_S)` reads

    (*)  sum_{u∈N(v)} sigma(u) + sum_{w∈T} sigma(w) + 2 e_M(N(v),T) >= 2 e_B(N(v),T),

and it is **linear in the indicator of `T`**: with
`c_v(w) = -sigma(w) + 2 b_v(w) - 2 m_v(w)` (`b_v,m_v` = crossing / mono edges from
`w` to `N(v)`), the strongest instance is a maximum-weight independent set in
`G - N(v)` for the weights `c_v`.  This makes `(*)` a *computable* family, not a
family one has to enumerate.

---

## 2. C5[n] ledger (checked FIRST, as required) — `Q2_ledger.py`

Cut `X = c0 ∪ c2`, `Y = c1 ∪ c3 ∪ c4`.  Exact, `n = 1..6`, all verified with the
2^5-corner maximum-cut certificate of Lemma 2 (`PASS` at every n):

| n | N | \|E\| | \|M\| | 25\|M\| | N² | 25\|M\|−N² |
|---|---|---|---|---|---|---|
|1|5|5|1|25|25|**0**|
|2|10|20|4|100|100|**0**|
|3|15|45|9|225|225|**0**|
|4|20|80|16|400|400|**0**|
|5|25|125|25|625|625|**0**|
|6|30|180|36|900|900|**0**|

Per-class data (`n` generic): `c0,c1,c2`: `d = 2n`, `sigma = 2n`, `d_M = 0`,
`mu = +N`;  `c3,c4`: `d = 2n`, `sigma = 0`, `d_M = n`, `mu = -(3/2)N`.
Supply `3n·5n = 15n²` = demand `2n·7.5n = 15n²`: **zero slack anywhere.**

**Fact 2.1 (the transport on C5[n] is unique and has radius exactly 2).**
The `B`-graph is `c0−c1`, `c1−c2`, `c2−c3`, `c4−c0` (`c3−c4` is mono).  `c3`'s only
`B`-neighbours are in `c2`, so `c3`'s demand `7.5n²` must pass through `c2`, whose
own supply is only `5n²`; hence `c2` must receive `>= 2.5n²`, necessarily from `c1`.
Symmetrically for `c4 ← c0 ← c1`.  Since `c1` has exactly `5n²`, it must ship
**all** of it, `2.5n²` each way.  Per `B`-edge the flow is forced:
`c1→c2` and `c1→c0` carry `5/2`; `c2→c3` and `c0→c4` carry `15/2`.
So any admissible scheme is a **radius-2** scheme, and on `C5[n]` its rule
constants are pinned to `(5/2, 15/2)` with no freedom.

**Fact 2.2.** Family `(*)` is **exactly tight** on `C5[n]`: for each of the three
`sigma = 2n` classes there is an independent `T` with `Delta(N(v) ∪ T) = 0`
(e.g. `v ∈ c2`, `T = c2`; `v ∈ c4`, `T = c4`), and `Delta < 0` for the other classes.
Verified `n = 1..6`.  The switch-star is tight at `c0` and `c2`.

---

## 3. The recorded obstruction W_b — and an exact correction

`W_b = P4[b+1,b,b,b+1]` (path `A1−A2−A3−A4`).  Its unique locally-maximal
non-optimal part-cut is `X = A1 ∪ A4`, `Y = A2 ∪ A3`:

`|M| = b²`, `N = 4b+2`, `sigma = (b, 1, 1, b)`, `25|M| − N² = 9b² − 16b − 4 > 0`
for `b >= 3`; `bip(W_b) = 0` (P4 is bipartite).  The `±1` on the end parts is
essential: it makes `sigma = 1` rather than `0` on the middle, which is exactly
what defuses the switch-star (`sigma(A1) = b >= |T|·(2−1)`, tight at `T = A2`).

### REFUTED: "stable under every switching set below 0.27N"

Exact minimum improving switch (full integer search over the part-counts,
`Q2_ledger.py`):

| b | 3 | 4 | 5 | 6 | 8 | 10 | 12 |
|---|---|---|---|---|---|---|---|
| min \|S\| | 5 | 5 | 6 | 7 | 8 | 10 | 11 |
| \|S\|/N | 5/14=.357 | 5/18=.278 | 3/11=.273 | 7/26=.269 | 8/34=.235 | 10/42=.238 | 11/50=**.220** |

The improving set is `S = (p vertices of A1) ∪ (q vertices of A2)` with
`Delta = 2pq − pb − q`; minimising `p+q` gives
`|S| = (1+√b)²/2 + O(1)`, i.e. **`|S|/N → 1/8 = 0.125`**, not `0.27`.
`0.27N` is only correct at `b = 4,5`; the figure decays.  **So W_b only blocks
switching families below ≈ N/8**, and the level it certifies (`|M| <= N²/16`) is
itself not the true purely-local ceiling — §4 exhibits a 6-part LOC-feasible
configuration reaching `89N²/900 ≈ N²/10.11`.

`(*)` refutes `W_b`: `S = N(v) ∪ T` with `v ∈ A1`, `T = A1` gives `Delta = b² > 0`
(also `|T| = 2` already gives `Delta = b`).  Verified `b = 3..12`.

---

## 4. Mechanism ceilings over all blow-ups — `Q2_finite.cpp`

Exhaustive over every connected triangle-free pattern `H` (3..6 vertices, from
`geng -t -c`), every part-respecting cut, and **every** integer weight vector
summing to `N`.  `max 25|M|/N²` among configurations satisfying each family:

| family | N=24 | N=30 | N=36 | N=45 | N=48 | N=60 |
|---|---|---|---|---|---|---|
| **LOC** = `sigma>=0` + all switch-stars | 850/576 | 1950/900 | 2900/1296 | 2750/2025 (h≤5) | 5450/2304 | 8900/3600 |
| **STAR** = LOC + family `(*)` | **600/576** | 0 (none) | **1350/1296** | 0 (h≤5) | **2400/2304** | **3750/3600** |
| **ALL** = LOC + all `2^h` corners (= true max cut) | 0 | 0 | 0 | 0 | 0 | 0 |

`0` means *no* configuration with `25|M| > N²` survives.

**LOC is even weaker than the record's `1/16`.**  With `<= 5` parts its optimum is
the `P4` family (`W_b`), ceiling `1/16`.  With 6 parts the champion is the
*bipartite* pattern `EEj_` (parts `{0,1,2}|{3,4,5}`, edges `03,04,05,13,15,24,25`)
at `a = (14,4,12,4,12,14)`, `sigma = (2,10,2,10,2,2)`, all switch-stars slack `>= 2`:

    N = 24  30    36     48     60
    |M|/N^2 = 34/576  78/900  116/1296  218/2304  356/3600 = 89/900 ~ 1/10.11

so **purely local certificates cap no better than `|M| <= 89N^2/900`** on the
6-part level, and `bip = 0` for all of them (the pattern is bipartite).
Family `(*)` catches every one of these.

**STAR → exactly `25/24` at every `N ≡ 0 (mod 12)` tested (24, 36, 48, 60);
`0` at `N = 30, 45` because the witness needs `12 | N`.**
ALL → nothing, as it must.

---

## 5. THE OBSTRUCTION `W*(u,r)` — exact, and it kills the global term too

`Q2_wstar.py`, `Q2_wstar_scan.py`, `Q2_witness.py`; witness first found by
`Q2_finite.exe` as pattern `ECxo` and then identified in closed form.

> **`W*(u,r)`.**  `G = C5[2u, 2u, 3u, 2u, 3u]` with classes `c0~c1~c2~c3~c4~c0`;
> `N = 12u`, `|E| = 28u²`.
> Cut:  `X = c0 ∪ c2 ∪ (c3 ∖ R)`,  `Y = c1 ∪ c4 ∪ R`, where `R ⊆ c3`, `|R| = r`.

Exact closed forms (all verified independently at the vertex level, `u = 1..9`):

    |M| = 3u(2u-r) + 3u·r = 6u^2                (independent of r)
    25|M| - N^2 = 150u^2 - 144u^2 = 6u^2 > 0    |M|/N^2 = 1/24   (25|M|/N^2 = 25/24)
    sigma:  c0 = c1 = 5u,   c2 = 2r,   c3∖R = 0,   R = 0,   c4 = 4u - 2r
    bip(G) = min_i w_i w_{i+1} = 4u^2 = N^2/36        <-- G itself obeys the conjecture

and `W*(u,r)` satisfies, for every `r` in an exactly-computed range symmetric about
`r = u` (`u=1: r=1`; `u=2: 1..3`; `u=3: 1..5`; `u=4: 2..6`; `u=5: 2..8`;
`u=6: 2..10`; `u=7: 3..11`; in particular **`r = u` always works**, verified
`u = 1..9`):

* `sigma(v) >= 0` for every `v`;
* **every** switch-star inequality (tight at `c2`: `2r >= 2r`; tight at `c4`:
  `4u-2r >= 2(2u-r)`);
* **every** instance of the family `(*)`, i.e. `Delta(N(v) ∪ T) <= 0` for all `v`
  and all independent `T`;
* every instance of the strictly larger families `SUP` (any superset of some
  `N(v)`), `NBRU` (any union of neighbourhoods) and `PAIRNBR` (`N(u) ∪ N(v)`,
  `uv ∈ E`);
* every switching inequality `(MC_S)` for `|S|` below the exact bound in the table.

Minimum improving switch, exact (full integer search over the six twin-groups):

| u (=r) | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |
|---|---|---|---|---|---|---|---|---|---|
| N | 12 | 24 | 36 | 48 | 60 | 72 | 84 | 96 | 108 |
| min \|S\| | 5 | 9 | 12 | 16 | 19 | 23 | 26 | 30 | 33 |
| \|S\|/N | 5/12 | 3/8 | 1/3 | 1/3 | 19/60 | 23/72 | 13/42 | 5/16 | 11/36 |
| decimal | .4167 | .3750 | .3333 | .3333 | .3167 | .3194 | .3095 | .3125 | **.3056** |

The exact formula fitting all nine values is `min |S| = ceil((7u+3)/2)`, so

    min |S| / N  ->  7/24 = 0.291666...

**So `W*(u,u)` is stable under every switching set of size `< 0.3055 N` for every
`N <= 108` tested, and `< (7/24)N` asymptotically, while `25|M|/N² = 25/24`
exactly.**  (For comparison `W_b` decays to `0.125 N`; `W*` strictly supersedes it
as a stability obstruction, and its `1/24` is far closer to the target `1/25` than
anything the purely local level can reach — `1/16` for `W_b`, and in fact
`89/900 ≈ 1/10.11` for the true 6-part LOC champion of §4.)

### 5.1 Why this also kills the *global* term

`W*(u,r)` and the **maximum** cut of the **same graph** `C5[2u,2u,3u,2u,3u]`
(`|M| = 4u² = N²/36`) differ **only in the cut**.  Therefore:

> **Blocking Lemma.**  Let `Phi` be any functional of the graph `G` alone — the
> number of `C5`s through a vertex, degree sequence, edge count, odd girth,
> homomorphism counts, spectrum, anything.  Then `Phi` takes *identical* values on
> `W*(u,r)` and on the maximum cut of the same graph.  Hence no discharging scheme
> whose global term is a functional of `G` alone can separate them, and since the
> scheme's conclusion `25|M| <= N^2` is true at the maximum cut and false at the
> `W*` cut, no such scheme exists.
>
> Consequently the global term **must** be a functional of the *cut*, and by
> Lemma 1 the only such functionals available are the `Delta(S)`.  By the table
> above every `Delta(S)` with `|S| < (7/24)N` is satisfied by `W*(u,u)`.  So the
> global term must invoke a switching set of measure `>= 7/24 = 0.29166...` of `V(G)`, and
> any scheme that does not caps at `|M| <= N^2/24`.

This kills the specific suggestion in the task statement ("for example the number
of `C5`s through a vertex"): `W*` **is** a `C5` blow-up, so it is as `C5`-rich as
the extremal object; the `C5` count cannot see the difference between its good and
its bad cut.  The second suggestion ("deficiency of the cut from the `C5`-blow-up
structure") is a cut functional and therefore not excluded a priori, but on `W*`
the graph *is* a `C5` blow-up and the deficiency of the bad cut from the blow-up
structure is a single vertex class split `2u = (2u-r) + r` — a **`Theta(N)`**
perturbation that no bounded local rule detects, and detecting it is exactly the
`|S| >= (7/24)N` switch above.

---

## 6. Exhaustive test, all maximal triangle-free graphs `N <= 12` — `Q2_exhaust.cpp`

Generated with `geng -t -c n`, `n = 5..12`, filtered by "every non-adjacent pair has
a common neighbour".  Counts (independently reproduced in Python):
`n = 3..12` → `1, 2, 3, 4, 6, 10, 16, 31, 61, 147`; **278 graphs** for `5 <= n <= 12`.

**PART A (at the exact maximum cuts).** 587 maximum cuts examined.
`25|M| <= N^2`: **0 failures.**  Charge identity `sum mu = N^2 - 25|M|`: **0 failures.**
Every family-`(*)` inequality `Delta(N(v) ∪ T) <= 0`: **0 failures** (as Lemma 1
requires — this is the positive control that the implementation is correct).

**PART B (all cuts): every cut that satisfies `sigma >= 0`, all switch-stars and
all of `(*)`, yet violates `25|M| <= N^2`.**  Exactly **15**, on 6 graphs:

```
J?`F?|wlF_?   N=11 cut=0x47c  M=5  25M-N^2=+4
K??FF?^Fvw^_  N=12 cut=0x4f8  M=6  25M-N^2=+6     <-- champion, 25M/N^2 = 150/144 = 25/24
K??FF?^Fvw^_  N=12 cut=0x8f8  M=6  25M-N^2=+6
K?BD@j_QvoBs  N=12 cut=0x7e   M=6  25M-N^2=+6
K?BD@j_QvoBs  N=12 cut=0xcc2  M=6  25M-N^2=+6
K?BD@j_QvoBs  N=12 cut=0xe24  M=6  25M-N^2=+6
K?`@F?{UckBw  N=12 cut=0x5d2  M=6  25M-N^2=+6
K?`@F?{UckBw  N=12 cut=0x6b4  M=6  25M-N^2=+6
K?`@F?{UckBw  N=12 cut=0xc1e  M=6  25M-N^2=+6
K?`FE`wl?{Dg  N=12 cut=0x696  M=6  25M-N^2=+6
K?`FE`wl?{Dg  N=12 cut=0xa5a  M=6  25M-N^2=+6
K?`FAo]]DgSg  N=12 cut=0xfc   M=6  25M-N^2=+6
K?`FAo]]DgSg  N=12 cut=0x6f0  M=6  25M-N^2=+6
K?`FAo]]DgSg  N=12 cut=0xa78  M=6  25M-N^2=+6
K?`FAo]]DgSg  N=12 cut=0xd16  M=6  25M-N^2=+6
```
(`cut` = bitmask of the side-1 vertices, vertex 0 pinned to side 0.)

The champion `K??FF?^Fvw^_` has twin classes of sizes `3,2,2,3,2` forming a `C5`
(`A={0,1,2} ~ C={6,7} ~ D={8,9} ~ B={3,4,5} ~ E={10,11} ~ A`), i.e. it **is**
`C5[2,2,3,2,3] = W*(1,1)` — the smallest member of the family of §5 appears
already at `N = 12`.

---

## 7. VERDICT for the assigned mechanism

**(a) The scheme.**  Charge `mu(v) = N - (25/2)d_M(v)`; the sum is the target
identically.  On `C5[n]` the redistribution is forced, unique and of radius 2
(Fact 2.1).  The only admissible local rules are non-negative combinations of the
switch-stars; the only admissible *global* terms are non-negative combinations of
`Delta(S) <= 0` (Lemma 1) — anything else is a functional of `G` alone and is
excluded by the Blocking Lemma.

**(b) Tightness on `C5[n]`, `n = 1..6`:** exact, `25|M| - N² = 0` at every `n`, and
family `(*)` is tight there.  **Survival of `W_b`:** family `(*)` refutes `W_b` for
all `b >= 1` (`Delta = b² > 0`), and the recorded `0.27N` stability of `W_b` is
itself wrong (§3, it is `→ N/8`).

**(c) `N <= 12` exhaustive:** 0 failures at maximum cuts; 15 exact failures of the
mechanism at non-maximum cuts, listed above in graph6.

**The deliverable is therefore the exact configuration where it breaks:**
`W*(u,r) = C5[2u,2u,3u,2u,3u]` with `X = c0 ∪ c2 ∪ (c3∖R)`, `|R| = r`.
It satisfies every hypothesis a discharging scheme with a graph-global term can
use, and `25|M| = (25/24)N^2`.  A discharging scheme with a global term can prove
at best `bip(G) <= N^2/24` unless the global term is a cut functional using a
switching set of measure `>= 7/24 = 0.29166...` (exact minimum improving switch
`ceil((7u+3)/2)`, i.e. `>= 0.3055 N` for every `N <= 108` tested).

---

## 8. Files (all in `E:\Projects\ErdosProblems\problems\23\round7\`)

| file | what |
|---|---|
| `Q2.md` | this report |
| `Q2_ledger.py` / `Q2_ledger_out.txt` | exact `C5[n]` ledger `n=1..6`, `W_b` ledger `b=1..12`, minimum improving switches |
| `Q2_patterns.py`, `Q2_pat35.txt`, `Q2_pat6.txt` | `geng -t -c` patterns as adjacency matrices |
| `Q2_finite.cpp` / `.exe`, `Q2_finite_bigN.txt` | exact finite-blow-up mechanism-ceiling search (LOC / STAR / ALL) |
| `Q2_witness.py` | exact dissection of any blow-up witness (improving sets, families, min switch) |
| `Q2_wstar.py`, `Q2_wstar_scan.py`, `Q2_wstar_large.txt` | closed-form verification of `W*(u,r)`, twice, at vertex level |
| `Q2_exhaust.cpp` / `.exe`, `Q2_exhaust_out.txt`, `Q2_tf_all.g6` | exhaustive maximal-triangle-free test `N <= 12` |
| `Q2_family.py` | **superseded** — normalised (`N→∞`) LP; its `1/8` answer is an artefact of dropping the `O(1)` term in the switch-star, kept only as a recorded error |

### Recorded error (mine)
`Q2_family.py` normalises weights to `sum a_i = 1` and then treats the switch-star
as vacuous, because `Delta({v} ∪ T) = O(N)` while `Delta(S) = O(N^2)` for
`|S| = Theta(N)`.  That wrongly admits `K_{2n,2n}` (`|M|/N² = 1/8`, all `sigma = 0`),
which a 2-vertex switch kills at every finite `N`.  **Any continuous / normalised
relaxation of this problem must carry the `O(1)` offsets** — they are exactly what
makes `W_b` (`sigma = 1`, not `0`) and `W*` (`|R| = r`, an `O(1)`-to-`Theta(N)`
split of one class) work.  All conclusions here come from the exact finite search.
